import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { laboratoryMaintenance } from "@/src/db/schema-phase6";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { canReadResourceScope,canWriteResourceScope,getEquipmentScope } from "@/src/services/resource-scope";
const createInput=z.object({equipmentId:z.number().int().positive(),maintenanceType:z.string().min(2).max(80),description:z.string().min(3),scheduledDate:z.string().optional(),completedDate:z.string().optional(),cost:z.number().nonnegative().optional(),provider:z.string().max(255).optional(),status:z.enum(["PLANNED","IN_PROGRESS","COMPLETED","CANCELLED"]).default("PLANNED")});
const patchInput=z.object({maintenanceType:z.string().min(2).max(80).optional(),description:z.string().min(3).optional(),scheduledDate:z.string().nullable().optional(),completedDate:z.string().nullable().optional(),cost:z.number().nonnegative().nullable().optional(),provider:z.string().max(255).nullable().optional(),status:z.enum(["PLANNED","IN_PROGRESS","COMPLETED","CANCELLED","ARCHIVED"]).optional()});
function idParam(req:Request,key="id"){const n=Number(new URL(req.url).searchParams.get(key));return Number.isInteger(n)&&n>0?n:null;}
export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const equipmentId=idParam(req,"equipmentId");const db=requireDb();const rows=equipmentId?await db.select().from(laboratoryMaintenance).where(eq(laboratoryMaintenance.equipmentId,equipmentId)):await db.select().from(laboratoryMaintenance);const allowed=[];for(const row of rows){const scope=await getEquipmentScope(row.equipmentId);if(scope&&canReadResourceScope(s,scope.organizationId,null))allowed.push(row);}return NextResponse.json(allowed);}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const p=createInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const scope=await getEquipmentScope(p.data.equipmentId);if(!scope)return NextResponse.json({error:"Peralatan tidak ditemukan."},{status:404});if(!canWriteResourceScope(s,scope.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const x=await db.insert(laboratoryMaintenance).values({equipmentId:p.data.equipmentId,maintenanceType:p.data.maintenanceType,description:p.data.description,scheduledDate:p.data.scheduledDate,completedDate:p.data.completedDate,cost:p.data.cost?.toString(),provider:p.data.provider,recordedBy:s.userId,status:p.data.status});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_LAB_MAINTENANCE",subjectType:"LAB_MAINTENANCE",subjectId:id,after:p.data});return NextResponse.json({id,status:p.data.status},{status:201});}
export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patchInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(laboratoryMaintenance).where(eq(laboratoryMaintenance.id,id)).limit(1);if(!before)return NextResponse.json({error:"Record tidak ditemukan."},{status:404});const scope=await getEquipmentScope(before.equipmentId);if(!scope||!canWriteResourceScope(s,scope.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});const update={...p.data,cost:p.data.cost===undefined?undefined:p.data.cost===null?null:p.data.cost.toString(),updatedAt:new Date()};await db.update(laboratoryMaintenance).set(update).where(eq(laboratoryMaintenance.id,id));await audit({actorId:s.userId,action:"UPDATE_LAB_MAINTENANCE",subjectType:"LAB_MAINTENANCE",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(laboratoryMaintenance).where(eq(laboratoryMaintenance.id,id)).limit(1);if(!before)return NextResponse.json({error:"Record tidak ditemukan."},{status:404});const scope=await getEquipmentScope(before.equipmentId);if(!scope||!canWriteResourceScope(s,scope.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});await db.update(laboratoryMaintenance).set({status:"ARCHIVED",updatedAt:new Date()}).where(eq(laboratoryMaintenance.id,id));await audit({actorId:s.userId,action:"ARCHIVE_LAB_MAINTENANCE",subjectType:"LAB_MAINTENANCE",subjectId:id,before,after:{status:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
