import { and,eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { courses,curricula,curriculumCourses } from "@/src/db/schema-phase5";
import { getSession } from "@/src/lib/auth";
import { can } from "@/src/lib/rbac";
import { audit } from "@/src/lib/audit";
import { canAccessCurriculum } from "@/src/services/academic-scope";
const input=z.object({curriculumId:z.number().int().positive(),courseId:z.number().int().positive(),semester:z.number().int().min(1).max(14),creditsOverride:z.number().positive().optional()});
export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const curriculumId=Number(new URL(req.url).searchParams.get("curriculumId"));if(!curriculumId||!(await canAccessCurriculum(s,curriculumId)))return NextResponse.json({error:"Scope kurikulum tidak sesuai."},{status:403});const db=requireDb();return NextResponse.json(await db.select({id:curriculumCourses.id,curriculumId:curriculumCourses.curriculumId,courseId:curriculumCourses.courseId,semester:curriculumCourses.semester,creditsOverride:curriculumCourses.creditsOverride,courseCode:courses.code,courseName:courses.name,credits:courses.credits}).from(curriculumCourses).innerJoin(courses,eq(curriculumCourses.courseId,courses.id)).where(eq(curriculumCourses.curriculumId,curriculumId)));}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(s,"curriculum.manage")||can(s,"data.create")))return NextResponse.json({error:"Forbidden"},{status:403});const p=input.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});if(!(await canAccessCurriculum(s,p.data.curriculumId)))return NextResponse.json({error:"Scope kurikulum tidak sesuai."},{status:403});const db=requireDb();const [curriculum]=await db.select({studyProgramId:curricula.studyProgramId}).from(curricula).where(eq(curricula.id,p.data.curriculumId)).limit(1);const [course]=await db.select({studyProgramId:courses.studyProgramId}).from(courses).where(eq(courses.id,p.data.courseId)).limit(1);if(!curriculum||!course||curriculum.studyProgramId!==course.studyProgramId)return NextResponse.json({error:"Mata kuliah dan kurikulum harus berasal dari Program Studi yang sama."},{status:409});const x=await db.insert(curriculumCourses).values({...p.data,creditsOverride:p.data.creditsOverride?.toString()});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"MAP_COURSE_TO_CURRICULUM",subjectType:"CURRICULUM_COURSE",subjectId:id,after:p.data});return NextResponse.json({id},{status:201});}
