"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
type Row=Record<string,any>;
async function request(url:string,method="GET",body?:unknown){const response=await fetch(url,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Operasi gagal.");return data;}
export default function RtmConsole({organizations,periods,canManage,canApprove}:{organizations:Row[];periods:Row[];canManage:boolean;canApprove:boolean}){
 const[organizationId,setOrganizationId]=useState(organizations[0]?.id??0),[period,setPeriod]=useState(""),[data,setData]=useState<Row|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[open,setOpen]=useState<number|null>(null);
 const choices=useMemo(()=>periods.filter(row=>row.organizationId===organizationId),[periods,organizationId]);
 async function load(){if(!organizationId||!period)return setData(null);try{setData(await request(`/api/internal/rtm?organizationId=${organizationId}&period=${encodeURIComponent(period)}`));}catch(error){setMessage(error instanceof Error?error.message:"RTM gagal dimuat.");}}
 useEffect(()=>{if(!period&&choices[0])setPeriod(choices[0].label)},[choices,period]);useEffect(()=>{void load()},[organizationId,period]);
 async function saveSession(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);setBusy(true);try{await request("/api/internal/rtm","POST",{organizationId,period,title:f.get("title"),meetingDate:f.get("meetingDate"),summary:f.get("summary"),strengths:f.get("strengths"),gaps:f.get("gaps"),conclusion:f.get("conclusion"),signedDocumentKey:f.get("signedDocumentKey")});setMessage("Data RTM dan resume LED tersimpan.");await load();}catch(error){setMessage(error instanceof Error?error.message:"RTM gagal disimpan.");}finally{setBusy(false)}}
 async function saveItem(event:FormEvent<HTMLFormElement>,assessmentId:number){event.preventDefault();const f=new FormData(event.currentTarget);if(!data?.session)return setMessage("Simpan identitas RTM terlebih dahulu.");setBusy(true);try{await request("/api/internal/rtm","PUT",{sessionId:data.session.id,assessmentId,discussionNote:f.get("discussionNote"),finding:f.get("finding"),rootCause:f.get("rootCause"),recommendation:f.get("recommendation"),actionPlan:f.get("actionPlan"),ownerName:f.get("ownerName"),dueDate:f.get("dueDate"),followupStatus:f.get("followupStatus"),publicationDecision:f.get("publicationDecision")});setMessage("Pembahasan indikator dan tindak lanjut tersimpan.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Pembahasan gagal disimpan.");}finally{setBusy(false)}}
 async function action(value:"SUBMIT"|"APPROVE"|"REOPEN"){if(!data?.session)return;setBusy(true);try{const result=await request("/api/internal/rtm","PATCH",{sessionId:data.session.id,action:value});setMessage(`Status RTM menjadi ${result.status}.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Status RTM gagal diubah.");}finally{setBusy(false)}}
 const session=data?.session??{};return <main className="rtm-shell"><header className="rtm-hero"><div><span>RAPAT TINJAUAN MANAJEMEN JURUSAN</span><h1>Evaluasi semester dan resume LED</h1><p>Bandingkan hasil modul, sepakati temuan dan tindak lanjut bersama Kajur, kemudian tentukan informasi yang layak dipublikasikan.</p></div><Link href="/internal">← Ruang kerja</Link></header>
 <section className="rtm-filter"><label><span>Jurusan</span><select value={organizationId} onChange={e=>{setOrganizationId(Number(e.target.value));setPeriod("")}}>{organizations.map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select></label><label><span>Periode</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="">Pilih periode</option>{choices.map(row=><option value={row.label} key={row.id}>{row.label.replace("-"," ")} · {row.status}</option>)}</select></label>{data?.session&&<span className={`rtm-status ${String(session.status).toLowerCase()}`}>{session.status}</span>}</section>
 {message&&<div className="rtm-message">{message}<button onClick={()=>setMessage("")}>Tutup</button></div>}
 {!period?<section className="rtm-empty">Buat dan pilih periode pengisian terlebih dahulu.</section>:<><section className="rtm-summary">{[["Asesmen",data?.summary?.assessments??0],["Diajukan",data?.summary?.submitted??0],["Sudah dibahas",data?.summary?.discussed??0],["Tindak lanjut terbuka",data?.summary?.openFollowups??0]].map(([label,value])=><div key={String(label)}><b>{value}</b><span>{label}</span></div>)}</section>
 <section className="rtm-card"><div className="rtm-heading"><div><span>01</span><h2>Identitas rapat dan ringkasan LED</h2></div><p>Disimpan di database. Setelah ditandatangani, isi lokasi/URL dokumen final sebagai arsip.</p></div><form className="rtm-session-form" onSubmit={saveSession}><label><span>Judul rapat</span><input name="title" required defaultValue={session.title??`RTM Jurusan ${period.replace("-"," ")}`}/></label><label><span>Tanggal RTM</span><input type="date" name="meetingDate" defaultValue={session.meetingDate??""}/></label><label className="wide"><span>Ringkasan hasil</span><textarea name="summary" defaultValue={session.summary??""}/></label><label><span>Kekuatan utama</span><textarea name="strengths" defaultValue={session.strengths??""}/></label><label><span>Kesenjangan utama</span><textarea name="gaps" defaultValue={session.gaps??""}/></label><label className="wide"><span>Kesimpulan RTM</span><textarea name="conclusion" defaultValue={session.conclusion??""}/></label><label className="wide"><span>Lokasi/URL LED bertanda tangan</span><input name="signedDocumentKey" defaultValue={session.signedDocumentKey??""} placeholder="Diisi setelah PDF ditandatangani dan diunggah"/></label>{canManage&&session.status!=="APPROVED"&&<button disabled={busy}>Simpan RTM dan resume</button>}</form></section>
 <section className="rtm-card"><div className="rtm-heading"><div><span>02</span><h2>Pembahasan indikator</h2></div><p>Hanya asesmen yang sudah disimpan pada periode ini yang muncul. Nilai sebelumnya ditampilkan sebagai pembanding.</p></div><div className="rtm-items">{data?.items?.map((row:Row)=>{const item=row.item??{},expanded=open===row.id;return <article key={row.id}><button className="rtm-item-head" onClick={()=>setOpen(expanded?null:row.id)}><span><small>{row.program?.code} · {row.indicator?.criterionCode}</small><b>{row.indicator?.code} · {row.indicator?.name}</b></span><span><small>Semester lalu</small><b>{row.previous?.calculatedScore??"—"}</b></span><span><small>Semester ini</small><b>{row.calculatedScore??"—"}</b></span><span><small>Status</small><b>{row.workflowStatus}</b></span><strong>{expanded?"Tutup":"Bahas"}</strong></button>{expanded&&<form className="rtm-item-form" onSubmit={e=>saveItem(e,row.id)}><div className="comparison"><p><b>Analisis pengisi:</b> {row.analysis||"Belum diisi"}</p><p><b>Evaluasi awal:</b> {row.evaluationNote||"Belum diisi"}</p><p><b>Rencana awal:</b> {row.followupPlan||"Belum diisi"}</p></div><label className="wide"><span>Catatan pembahasan RTM</span><textarea name="discussionNote" defaultValue={item.discussionNote??""}/></label><label><span>Temuan</span><textarea name="finding" defaultValue={item.finding??""}/></label><label><span>Akar masalah</span><textarea name="rootCause" defaultValue={item.rootCause??""}/></label><label><span>Rekomendasi</span><textarea name="recommendation" defaultValue={item.recommendation??""}/></label><label><span>Rencana tindak lanjut</span><textarea name="actionPlan" defaultValue={item.actionPlan??""}/></label><label><span>Penanggung jawab</span><input name="ownerName" defaultValue={item.ownerName??""}/></label><label><span>Batas waktu</span><input type="date" name="dueDate" defaultValue={item.dueDate??""}/></label><label><span>Status tindak lanjut</span><select name="followupStatus" defaultValue={item.followupStatus??"OPEN"}><option value="OPEN">Belum dikerjakan</option><option value="IN_PROGRESS">Sedang dikerjakan</option><option value="CLOSED">Selesai</option></select></label><label><span>Keputusan publikasi Kajur</span><select name="publicationDecision" defaultValue={item.publicationDecision??"INTERNAL_ONLY"}><option value="INTERNAL_ONLY">Internal / LED saja</option><option value="PUBLIC_SUMMARY">Publikasikan ringkasan</option><option value="PUBLIC_SCORE">Publikasikan ringkasan dan capaian</option><option value="PUBLIC_EVIDENCE">Publikasikan ringkasan dan bukti terpilih</option></select></label>{canManage&&session.status!=="APPROVED"&&<button disabled={busy}>Simpan hasil pembahasan</button>}</form>}</article>})}{data&&!data.items?.length&&<p className="rtm-empty">Belum ada asesmen tersimpan. Selesaikan pengisian dan perhitungan indikator terlebih dahulu.</p>}</div></section>
 {session.id&&<section className="rtm-actions"><Link href={`/internal/rtm/print?organizationId=${organizationId}&period=${encodeURIComponent(period)}`}>Lihat dan cetak resume LED</Link>{session.status==="DRAFT"&&canManage&&<button disabled={busy} onClick={()=>void action("SUBMIT")}>Ajukan RTM ke Kajur</button>}{session.status==="SUBMITTED"&&canApprove&&<button disabled={busy} onClick={()=>void action("APPROVE")}>Sahkan RTM dan tutup periode</button>}{session.status==="APPROVED"&&canApprove&&<button className="secondary" disabled={busy} onClick={()=>void action("REOPEN")}>Buka kembali untuk revisi</button>}</section>}</>}</main>;
}
