import { and,eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { studyPrograms } from "@/src/db/schema";
import { accreditationAgencies,accreditationFrameworks,studyProgramAccreditationFrameworks } from "@/src/db/schema-accreditation";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { can,scopeAllows } from "@/src/lib/rbac";

const createInput=z.object({studyProgramId:z.number().int().positive(),frameworkId:z.number().int().positive(),isPrimary:z.boolean().default(true),assignedFrom:z.string().optional(),assignedTo:z.string().optional(),officialCoverageReference:z.string().max(1000).optional(),notes:z.string().optional()});
const patchInput=z.object({id:z.number().int().positive(),isPrimary:z.boolean().optional(),assignmentStatus:z.enum(["ACTIVE","INACTIVE","ARCHIVED"]).optional(),assignedFrom:z.string().nullable().optional(),assignedTo:z.string().nullable().optional(),officialCoverageReference:z.string().max(1000).nullable().optional(),notes:z.string().nullable().optional()});

export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.read"))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const rows=await db.select({id:studyProgramAccreditationFrameworks.id,studyProgramId:studyPrograms.id,studyProgramCode:studyPrograms.code,studyProgramName:studyPrograms.name,organizationId:studyPrograms.organizationId,frameworkId:accreditationFrameworks.id,frameworkCode:accreditationFrameworks.code,frameworkName:accreditationFrameworks.name,agencyId:accreditationAgencies.id,agencyCode:accreditationAgencies.code,agencyName:accreditationAgencies.name,isPrimary:studyProgramAccreditationFrameworks.isPrimary,assignmentStatus:studyProgramAccreditationFrameworks.assignmentStatus,assignedFrom:studyProgramAccreditationFrameworks.assignedFrom,assignedTo:studyProgramAccreditationFrameworks.assignedTo,officialCoverageReference:studyProgramAccreditationFrameworks.officialCoverageReference,notes:studyProgramAccreditationFrameworks.notes}).from(studyProgramAccreditationFrameworks).innerJoin(studyPrograms,eq(studyProgramAccreditationFrameworks.studyProgramId,studyPrograms.id)).innerJoin(accreditationFrameworks,eq(studyProgramAccreditationFrameworks.frameworkId,accreditationFrameworks.id)).innerJoin(accreditationAgencies,eq(accreditationFrameworks.agencyId,accreditationAgencies.id));return NextResponse.json(rows.filter(x=>scopeAllows(s,x.organizationId,x.studyProgramId)));}

export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.assign"))return NextResponse.json({error:"Forbidden"},{status:403});const p=createInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[program]=await db.select().from(studyPrograms).where(and(eq(studyPrograms.id,p.data.studyProgramId),eq(studyPrograms.status,"ACTIVE"))).limit(1);if(!program)return NextResponse.json({error:"Program Studi tidak ditemukan/aktif."},{status:404});const[framework]=await db.select().from(accreditationFrameworks).where(eq(accreditationFrameworks.id,p.data.frameworkId)).limit(1);if(!framework||framework.lifecycleStatus==="ARCHIVED")return NextResponse.json({error:"Framework tidak tersedia."},{status:404});const[found]=await db.select().from(studyProgramAccreditationFrameworks).where(and(eq(studyProgramAccreditationFrameworks.studyProgramId,p.data.studyProgramId),eq(studyProgramAccreditationFrameworks.frameworkId,p.data.frameworkId))).limit(1);if(found)return NextResponse.json({error:"Framework sudah ditautkan ke Prodi ini."},{status:409});if(p.data.isPrimary)await db.update(studyProgramAccreditationFrameworks).set({isPrimary:false}).where(and(eq(studyProgramAccreditationFrameworks.studyProgramId,p.data.studyProgramId),eq(studyProgramAccreditationFrameworks.assignmentStatus,"ACTIVE")));const x=await db.insert(studyProgramAccreditationFrameworks).values({...p.data,assignmentStatus:"ACTIVE"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"ASSIGN_ACCREDITATION_FRAMEWORK",subjectType:"PROGRAM_ACCREDITATION_FRAMEWORK",subjectId:id,after:p.data});return NextResponse.json({id,assignmentStatus:"ACTIVE",...p.data},{status:201});}

export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.assign"))return NextResponse.json({error:"Forbidden"},{status:403});const p=patchInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(studyProgramAccreditationFrameworks).where(eq(studyProgramAccreditationFrameworks.id,p.data.id)).limit(1);if(!before)return NextResponse.json({error:"Assignment tidak ditemukan."},{status:404});if(p.data.isPrimary===true)await db.update(studyProgramAccreditationFrameworks).set({isPrimary:false}).where(and(eq(studyProgramAccreditationFrameworks.studyProgramId,before.studyProgramId),eq(studyProgramAccreditationFrameworks.assignmentStatus,"ACTIVE")));const{id,...changes}=p.data;await db.update(studyProgramAccreditationFrameworks).set({...changes,updatedAt:new Date()}).where(eq(studyProgramAccreditationFrameworks.id,id));await audit({actorId:s.userId,action:"UPDATE_ACCREDITATION_ASSIGNMENT",subjectType:"PROGRAM_ACCREDITATION_FRAMEWORK",subjectId:id,before,after:changes});return NextResponse.json({id,...changes});}

export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.assign"))return NextResponse.json({error:"Forbidden"},{status:403});const id=Number(new URL(req.url).searchParams.get("id"));if(!Number.isInteger(id)||id<1)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(studyProgramAccreditationFrameworks).where(eq(studyProgramAccreditationFrameworks.id,id)).limit(1);if(!before)return NextResponse.json({error:"Assignment tidak ditemukan."},{status:404});await db.update(studyProgramAccreditationFrameworks).set({assignmentStatus:"ARCHIVED",isPrimary:false,updatedAt:new Date()}).where(eq(studyProgramAccreditationFrameworks.id,id));await audit({actorId:s.userId,action:"ARCHIVE_ACCREDITATION_ASSIGNMENT",subjectType:"PROGRAM_ACCREDITATION_FRAMEWORK",subjectId:id,before,after:{assignmentStatus:"ARCHIVED"}});return NextResponse.json({id,assignmentStatus:"ARCHIVED"});}
