import { and,eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { accreditationClusters,accreditationCriteria,accreditationEvidenceRequirements,accreditationFrameworks,accreditationIndicatorClusters,accreditationIndicators } from "@/src/db/schema-accreditation";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { can } from "@/src/lib/rbac";

const clusterInput=z.object({entity:z.literal("CLUSTER"),frameworkId:z.number().int().positive(),code:z.string().min(1).max(80),name:z.string().min(2).max(255),semanticGroup:z.string().max(50).optional(),description:z.string().optional(),sequence:z.number().int().positive().default(1)});
const criterionInput=z.object({entity:z.literal("CRITERION"),frameworkId:z.number().int().positive(),code:z.string().min(1).max(80),name:z.string().min(2).max(500),description:z.string().optional(),sequence:z.number().int().positive().default(1)});
const indicatorInput=z.object({entity:z.literal("INDICATOR"),frameworkId:z.number().int().positive(),criterionId:z.number().int().positive(),code:z.string().min(1).max(100),name:z.string().min(2).max(700),description:z.string().optional(),unit:z.string().max(80).optional(),weight:z.number().optional(),scoringRule:z.unknown().optional(),sequence:z.number().int().positive().default(1),clusterIds:z.array(z.number().int().positive()).default([]),primaryClusterId:z.number().int().positive().optional()});
const evidenceInput=z.object({entity:z.literal("EVIDENCE_REQUIREMENT"),indicatorId:z.number().int().positive(),code:z.string().min(1).max(100),description:z.string().min(2),required:z.boolean().default(true),acceptableSubjectTypes:z.array(z.string()).optional()});
const input=z.discriminatedUnion("entity",[clusterInput,criterionInput,indicatorInput,evidenceInput]);

const clusterPatch=z.object({entity:z.literal("CLUSTER"),id:z.number().int().positive(),name:z.string().optional(),description:z.string().nullable().optional(),semanticGroup:z.string().nullable().optional(),sequence:z.number().int().positive().optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional()});
const criterionPatch=z.object({entity:z.literal("CRITERION"),id:z.number().int().positive(),name:z.string().optional(),description:z.string().nullable().optional(),sequence:z.number().int().positive().optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional()});
const indicatorPatch=z.object({entity:z.literal("INDICATOR"),id:z.number().int().positive(),name:z.string().optional(),description:z.string().nullable().optional(),sequence:z.number().int().positive().optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional(),unit:z.string().nullable().optional(),weight:z.number().nullable().optional(),scoringRule:z.unknown().optional()});
const evidencePatch=z.object({entity:z.literal("EVIDENCE_REQUIREMENT"),id:z.number().int().positive(),description:z.string().optional(),required:z.boolean().optional(),acceptableSubjectTypes:z.array(z.string()).nullable().optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional()});
const patch=z.discriminatedUnion("entity",[clusterPatch,criterionPatch,indicatorPatch,evidencePatch]);

async function editableFramework(frameworkId:number){const db=requireDb();const[f]=await db.select().from(accreditationFrameworks).where(eq(accreditationFrameworks.id,frameworkId)).limit(1);return f&&f.lifecycleStatus!=="ARCHIVED"?f:null;}

export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.read"))return NextResponse.json({error:"Forbidden"},{status:403});const frameworkId=Number(new URL(req.url).searchParams.get("frameworkId"));if(!Number.isInteger(frameworkId)||frameworkId<1)return NextResponse.json({error:"frameworkId wajib."},{status:400});const db=requireDb();const[framework]=await db.select().from(accreditationFrameworks).where(eq(accreditationFrameworks.id,frameworkId)).limit(1);if(!framework)return NextResponse.json({error:"Framework tidak ditemukan."},{status:404});const[clusters,criteria,indicators]=await Promise.all([db.select().from(accreditationClusters).where(eq(accreditationClusters.frameworkId,frameworkId)),db.select().from(accreditationCriteria).where(eq(accreditationCriteria.frameworkId,frameworkId)),db.select().from(accreditationIndicators).where(eq(accreditationIndicators.frameworkId,frameworkId))]);const ids=new Set(indicators.map(x=>x.id));const indicatorClusters=(await db.select().from(accreditationIndicatorClusters)).filter(x=>ids.has(x.indicatorId));const evidence=(await db.select().from(accreditationEvidenceRequirements)).filter(x=>ids.has(x.indicatorId));return NextResponse.json({framework,clusters,criteria,indicators,indicatorClusters,evidenceRequirements:evidence});}

export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.framework.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const p=input.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();
if(p.data.entity==="CLUSTER"){if(!(await editableFramework(p.data.frameworkId)))return NextResponse.json({error:"Framework tidak dapat diedit."},{status:409});const code=p.data.code.toUpperCase();const[found]=await db.select({id:accreditationClusters.id}).from(accreditationClusters).where(and(eq(accreditationClusters.frameworkId,p.data.frameworkId),eq(accreditationClusters.code,code))).limit(1);if(found)return NextResponse.json({error:"Kode klaster sudah ada."},{status:409});const x=await db.insert(accreditationClusters).values({frameworkId:p.data.frameworkId,code,name:p.data.name,semanticGroup:p.data.semanticGroup,description:p.data.description,sequence:p.data.sequence,status:"ACTIVE"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_ACCREDITATION_CLUSTER",subjectType:"ACCREDITATION_CLUSTER",subjectId:id,after:{...p.data,code}});return NextResponse.json({id,code},{status:201});}
if(p.data.entity==="CRITERION"){if(!(await editableFramework(p.data.frameworkId)))return NextResponse.json({error:"Framework tidak dapat diedit."},{status:409});const code=p.data.code.toUpperCase();const[found]=await db.select({id:accreditationCriteria.id}).from(accreditationCriteria).where(and(eq(accreditationCriteria.frameworkId,p.data.frameworkId),eq(accreditationCriteria.code,code))).limit(1);if(found)return NextResponse.json({error:"Kode kriteria sudah ada."},{status:409});const x=await db.insert(accreditationCriteria).values({frameworkId:p.data.frameworkId,code,name:p.data.name,description:p.data.description,sequence:p.data.sequence,status:"ACTIVE"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_ACCREDITATION_CRITERION",subjectType:"ACCREDITATION_CRITERION",subjectId:id,after:{...p.data,code}});return NextResponse.json({id,code},{status:201});}
if(p.data.entity==="INDICATOR"){if(!(await editableFramework(p.data.frameworkId)))return NextResponse.json({error:"Framework tidak dapat diedit."},{status:409});const[criterion]=await db.select().from(accreditationCriteria).where(and(eq(accreditationCriteria.id,p.data.criterionId),eq(accreditationCriteria.frameworkId,p.data.frameworkId))).limit(1);if(!criterion)return NextResponse.json({error:"Kriteria tidak sesuai framework."},{status:400});const code=p.data.code.toUpperCase();const[found]=await db.select({id:accreditationIndicators.id}).from(accreditationIndicators).where(and(eq(accreditationIndicators.frameworkId,p.data.frameworkId),eq(accreditationIndicators.code,code))).limit(1);if(found)return NextResponse.json({error:"Kode indikator sudah ada."},{status:409});const x=await db.insert(accreditationIndicators).values({frameworkId:p.data.frameworkId,criterionId:p.data.criterionId,code,name:p.data.name,description:p.data.description,unit:p.data.unit,weight:p.data.weight==null?undefined:String(p.data.weight),scoringRule:p.data.scoringRule,sequence:p.data.sequence,status:"ACTIVE"});const id=Number(x[0].insertId);for(const clusterId of p.data.clusterIds){const[c]=await db.select({id:accreditationClusters.id}).from(accreditationClusters).where(and(eq(accreditationClusters.id,clusterId),eq(accreditationClusters.frameworkId,p.data.frameworkId))).limit(1);if(c)await db.insert(accreditationIndicatorClusters).values({indicatorId:id,clusterId,isPrimary:p.data.primaryClusterId===clusterId});}await audit({actorId:s.userId,action:"CREATE_ACCREDITATION_INDICATOR",subjectType:"ACCREDITATION_INDICATOR",subjectId:id,after:p.data});return NextResponse.json({id,code},{status:201});}
const[indicator]=await db.select().from(accreditationIndicators).where(eq(accreditationIndicators.id,p.data.indicatorId)).limit(1);if(!indicator)return NextResponse.json({error:"Indikator tidak ditemukan."},{status:404});const code=p.data.code.toUpperCase();const[found]=await db.select({id:accreditationEvidenceRequirements.id}).from(accreditationEvidenceRequirements).where(and(eq(accreditationEvidenceRequirements.indicatorId,p.data.indicatorId),eq(accreditationEvidenceRequirements.code,code))).limit(1);if(found)return NextResponse.json({error:"Kode kebutuhan evidence sudah ada."},{status:409});const x=await db.insert(accreditationEvidenceRequirements).values({indicatorId:p.data.indicatorId,code,description:p.data.description,required:p.data.required,acceptableSubjectTypes:p.data.acceptableSubjectTypes,status:"ACTIVE"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_ACCREDITATION_EVIDENCE_REQUIREMENT",subjectType:"ACCREDITATION_EVIDENCE_REQUIREMENT",subjectId:id,after:p.data});return NextResponse.json({id,code},{status:201});}

export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.framework.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const p=patch.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();
if(p.data.entity==="CLUSTER"){const{entity,id,...changes}=p.data;const[before]=await db.select().from(accreditationClusters).where(eq(accreditationClusters.id,id)).limit(1);if(!before)return NextResponse.json({error:"Klaster tidak ditemukan."},{status:404});await db.update(accreditationClusters).set(changes).where(eq(accreditationClusters.id,id));await audit({actorId:s.userId,action:"UPDATE_ACCREDITATION_CLUSTER",subjectType:"ACCREDITATION_CLUSTER",subjectId:id,before,after:changes});return NextResponse.json({id,...changes});}
if(p.data.entity==="CRITERION"){const{entity,id,...changes}=p.data;const[before]=await db.select().from(accreditationCriteria).where(eq(accreditationCriteria.id,id)).limit(1);if(!before)return NextResponse.json({error:"Kriteria tidak ditemukan."},{status:404});await db.update(accreditationCriteria).set(changes).where(eq(accreditationCriteria.id,id));await audit({actorId:s.userId,action:"UPDATE_ACCREDITATION_CRITERION",subjectType:"ACCREDITATION_CRITERION",subjectId:id,before,after:changes});return NextResponse.json({id,...changes});}
if(p.data.entity==="INDICATOR"){const{entity,id,weight,...changes}=p.data;const[before]=await db.select().from(accreditationIndicators).where(eq(accreditationIndicators.id,id)).limit(1);if(!before)return NextResponse.json({error:"Indikator tidak ditemukan."},{status:404});const values={...changes,...(weight===undefined?{}:{weight:weight===null?null:String(weight)})};await db.update(accreditationIndicators).set(values).where(eq(accreditationIndicators.id,id));await audit({actorId:s.userId,action:"UPDATE_ACCREDITATION_INDICATOR",subjectType:"ACCREDITATION_INDICATOR",subjectId:id,before,after:values});return NextResponse.json({id,...values});}
const{entity,id,...changes}=p.data;const[before]=await db.select().from(accreditationEvidenceRequirements).where(eq(accreditationEvidenceRequirements.id,id)).limit(1);if(!before)return NextResponse.json({error:"Evidence requirement tidak ditemukan."},{status:404});await db.update(accreditationEvidenceRequirements).set(changes).where(eq(accreditationEvidenceRequirements.id,id));await audit({actorId:s.userId,action:"UPDATE_ACCREDITATION_EVIDENCE_REQUIREMENT",subjectType:"ACCREDITATION_EVIDENCE_REQUIREMENT",subjectId:id,before,after:changes});return NextResponse.json({id,...changes});}
