import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { personnel } from "@/src/db/schema-phase6";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { canReadResourceScope,canWriteResourceScope,validateProgramUnderOrganization } from "@/src/services/resource-scope";
const createInput=z.object({organizationId:z.number().int().positive(),studyProgramId:z.number().int().positive().nullable().optional(),personnelType:z.enum(["LECTURER","STAFF","LAB_TECHNICIAN","OTHER"]),employeeCode:z.string().max(100).optional(),name:z.string().min(2).max(255),academicRank:z.string().max(150).optional(),functionalPosition:z.string().max(150).optional(),educationLevel:z.string().max(80).optional(),expertise:z.string().max(500).optional()});
const patchInput=createInput.omit({organizationId:true,studyProgramId:true}).partial().extend({status:z.enum(["ACTIVE","ARCHIVED"]).optional()});
function idParam(req:Request){const n=Number(new URL(req.url).searchParams.get("id"));return Number.isInteger(n)&&n>0?n:null;}
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const db=requireDb();const rows=await db.select().from(personnel);return NextResponse.json(rows.filter(row=>canReadResourceScope(s,row.organizationId,row.studyProgramId)));}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const p=createInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const studyProgramId=p.data.studyProgramId??null;if(studyProgramId&&!(await validateProgramUnderOrganization(studyProgramId,p.data.organizationId)))return NextResponse.json({error:"Program Studi tidak sesuai dengan organisasi."},{status:409});if(!canWriteResourceScope(s,p.data.organizationId,studyProgramId,false))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const x=await db.insert(personnel).values({...p.data,studyProgramId,status:"ACTIVE"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_PERSONNEL",subjectType:"PERSONNEL",subjectId:id,after:p.data});return NextResponse.json({id,status:"ACTIVE"},{status:201});}
export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patchInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(personnel).where(eq(personnel.id,id)).limit(1);if(!before)return NextResponse.json({error:"Personel tidak ditemukan."},{status:404});if(!canWriteResourceScope(s,before.organizationId,before.studyProgramId,false))return NextResponse.json({error:"Forbidden"},{status:403});await db.update(personnel).set({...p.data,updatedAt:new Date()}).where(eq(personnel.id,id));await audit({actorId:s.userId,action:"UPDATE_PERSONNEL",subjectType:"PERSONNEL",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(personnel).where(eq(personnel.id,id)).limit(1);if(!before)return NextResponse.json({error:"Personel tidak ditemukan."},{status:404});if(!canWriteResourceScope(s,before.organizationId,before.studyProgramId,false))return NextResponse.json({error:"Forbidden"},{status:403});await db.update(personnel).set({status:"ARCHIVED",updatedAt:new Date()}).where(eq(personnel.id,id));await audit({actorId:s.userId,action:"ARCHIVE_PERSONNEL",subjectType:"PERSONNEL",subjectId:id,before,after:{status:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
