import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { kpis } from "@/src/db/schema";
import { governanceScopes } from "@/src/db/schema-phase5";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { can,scopeAllows } from "@/src/lib/rbac";
import { attachGovernanceScope,governanceWriteAllows,validateGovernanceScope } from "@/src/services/governance-scope";
const input=z.object({strategicGoalId:z.number().int().positive(),ownerOrganizationId:z.number().int().positive(),studyProgramId:z.number().int().positive().nullable().optional(),code:z.string().min(2),name:z.string().min(3),definition:z.string().optional(),formula:z.string().optional(),unit:z.string().optional(),direction:z.enum(["HIGHER_IS_BETTER","LOWER_IS_BETTER","EXACT"]).default("HIGHER_IS_BETTER")});
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const db=requireDb();const rows=await db.select().from(kpis);const scopes=await db.select().from(governanceScopes);const map=new Map(scopes.filter(x=>x.subjectType==="KPI").map(x=>[x.subjectId,x]));return NextResponse.json(rows.filter(x=>{const sc=map.get(x.id);return scopeAllows(s,sc?.organizationId??x.ownerOrganizationId,sc?.studyProgramId??null)}).map(x=>({...x,studyProgramId:map.get(x.id)?.studyProgramId??null})));}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(s,"data.create")||can(s,"program.update")))return NextResponse.json({error:"Forbidden"},{status:403});const parsed=input.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});if(!(await validateGovernanceScope(parsed.data.ownerOrganizationId,parsed.data.studyProgramId)))return NextResponse.json({error:"Program Studi tidak berada pada organisasi pemilik."},{status:409});if(!governanceWriteAllows(s,parsed.data.ownerOrganizationId,parsed.data.studyProgramId))return NextResponse.json({error:"Scope write organisasi/Program Studi tidak sesuai."},{status:403});const db=requireDb();const {studyProgramId,...kpi}=parsed.data;const r=await db.insert(kpis).values({...kpi,lifecycleStatus:"DRAFT"});const newId=Number(r[0].insertId);await attachGovernanceScope({subjectType:"KPI",subjectId:newId,organizationId:parsed.data.ownerOrganizationId,studyProgramId});await audit({actorId:s.userId,action:"CREATE",subjectType:"KPI",subjectId:newId,after:parsed.data});return NextResponse.json({id:newId,status:"DRAFT",studyProgramId:studyProgramId??null},{status:201});}
