import { and, desc, eq } from "drizzle-orm";
import { requireDb } from "@/src/db";
import { approvals,evaluations,followups,kpiMeasurements,publicationPolicies,publications,strategicStatements } from "@/src/db/schema";
import { newsArticles } from "@/src/db/schema-admin";
import { curricula } from "@/src/db/schema-phase5";

export async function hasApprovedDecision(subjectType:string,subjectId:number){const db=requireDb();const rows=await db.select().from(approvals).where(and(eq(approvals.subjectType,subjectType),eq(approvals.subjectId,subjectId),eq(approvals.decision,"APPROVED"))).orderBy(desc(approvals.decidedAt)).limit(1);return rows[0]??null;}
async function activePolicy(subjectType:string){const db=requireDb();const rows=await db.select().from(publicationPolicies).where(and(eq(publicationPolicies.subjectType,subjectType),eq(publicationPolicies.status,"ACTIVE"))).orderBy(desc(publicationPolicies.policyVersion)).limit(1);return rows[0]??null;}
async function sourceStatus(subjectType:string,subjectId:number){const db=requireDb();if(subjectType==="STRATEGIC_STATEMENT"){const[x]=await db.select({status:strategicStatements.lifecycleStatus}).from(strategicStatements).where(eq(strategicStatements.id,subjectId)).limit(1);return x?.status;}if(subjectType==="KPI_MEASUREMENT"){const[x]=await db.select({status:kpiMeasurements.workflowStatus}).from(kpiMeasurements).where(eq(kpiMeasurements.id,subjectId)).limit(1);return x?.status;}if(subjectType==="EVALUATION"){const[x]=await db.select({status:evaluations.status}).from(evaluations).where(eq(evaluations.id,subjectId)).limit(1);return x?.status;}if(subjectType==="FOLLOWUP"){const[x]=await db.select({status:followups.status}).from(followups).where(eq(followups.id,subjectId)).limit(1);return x?.status;}if(subjectType==="NEWS_ARTICLE"){const[x]=await db.select({status:newsArticles.lifecycleStatus}).from(newsArticles).where(eq(newsArticles.id,subjectId)).limit(1);return x?.status;}if(subjectType==="CURRICULUM"){const[x]=await db.select({status:curricula.lifecycleStatus}).from(curricula).where(eq(curricula.id,subjectId)).limit(1);return x?.status;}return undefined;}
export async function publishApproved(input:{subjectType:string;subjectId:number;publicTitle?:string;publicSummary?:string;publishedBy:number}){const policy=await activePolicy(input.subjectType);if(!policy)throw new Error("Publication policy aktif tidak ditemukan untuk tipe objek ini.");const approval=policy.requiresApproval?await hasApprovedDecision(input.subjectType,input.subjectId):null;if(policy.requiresApproval&&!approval)throw new Error("Objek belum mempunyai approval yang sah.");const status=await sourceStatus(input.subjectType,input.subjectId);if(policy.requiredLifecycleStatus&&status!==policy.requiredLifecycleStatus)throw new Error(`Status sumber harus ${policy.requiredLifecycleStatus}; status saat ini ${status??"UNKNOWN"}.`);const db=requireDb();const now=new Date();const result=await db.insert(publications).values({subjectType:input.subjectType,subjectId:input.subjectId,policyId:policy.id,visibility:"PUBLIC",publicTitle:input.publicTitle,publicSummary:input.publicSummary,fieldPolicySnapshot:policy.allowedFields,approvedBy:approval?.approverId??null,publishedBy:input.publishedBy,publishedAt:now,publicationStart:now,status:"PUBLISHED"});if(input.subjectType==="NEWS_ARTICLE")await db.update(newsArticles).set({lifecycleStatus:"PUBLISHED",publishedAt:now,updatedAt:now}).where(eq(newsArticles.id,input.subjectId));if(input.subjectType==="CURRICULUM")await db.update(curricula).set({lifecycleStatus:"PUBLISHED",updatedAt:now}).where(eq(curricula.id,input.subjectId));return Number(result[0].insertId);}
