import { and,eq } from "drizzle-orm";
import { db } from "@/src/db";
import { publications,studyPrograms } from "@/src/db/schema";
import { communityServiceProjects,cooperations,graduateOutcomeStats,laboratories,laboratoryProfiles,researchProjects,studentAnnualStats } from "@/src/db/schema-phase6";
import { laboratoryProfilePrograms } from "@/src/db/schema-phase6-publication";

export async function getPublishedLaboratories(){const database=db;if(!database)return[];const rows=await database.select({publicationId:publications.id,profileId:laboratoryProfiles.id,laboratoryId:laboratories.id,organizationId:laboratories.organizationId,code:laboratories.code,name:laboratoryProfiles.name,description:laboratoryProfiles.description,location:laboratoryProfiles.location,versionNumber:laboratoryProfiles.versionNumber,publishedAt:publications.publishedAt}).from(publications).innerJoin(laboratoryProfiles,and(eq(publications.subjectType,"LABORATORY_PROFILE"),eq(publications.subjectId,laboratoryProfiles.id))).innerJoin(laboratories,eq(laboratoryProfiles.laboratoryId,laboratories.id)).where(and(eq(publications.status,"PUBLISHED"),eq(publications.visibility,"PUBLIC")));return Promise.all(rows.map(async row=>{const programs=await database.select({id:studyPrograms.id,code:studyPrograms.code,name:studyPrograms.name}).from(laboratoryProfilePrograms).innerJoin(studyPrograms,eq(laboratoryProfilePrograms.studyProgramId,studyPrograms.id)).where(eq(laboratoryProfilePrograms.laboratoryProfileId,row.profileId));return{...row,programs};}));}

export async function getPublishedResearch(){const database=db;if(!database)return[];return database.select({id:researchProjects.id,organizationId:researchProjects.organizationId,studyProgramId:researchProjects.studyProgramId,programName:studyPrograms.name,title:researchProjects.title,year:researchProjects.year,fundingSource:researchProjects.fundingSource,scheme:researchProjects.scheme,outputSummary:researchProjects.outputSummary,projectStatus:researchProjects.projectStatus,publishedAt:publications.publishedAt}).from(publications).innerJoin(researchProjects,and(eq(publications.subjectType,"RESEARCH_PROJECT"),eq(publications.subjectId,researchProjects.id))).leftJoin(studyPrograms,eq(researchProjects.studyProgramId,studyPrograms.id)).where(and(eq(publications.status,"PUBLISHED"),eq(publications.visibility,"PUBLIC")));}
export async function getPublishedCommunityService(){const database=db;if(!database)return[];return database.select({id:communityServiceProjects.id,organizationId:communityServiceProjects.organizationId,studyProgramId:communityServiceProjects.studyProgramId,programName:studyPrograms.name,title:communityServiceProjects.title,year:communityServiceProjects.year,partner:communityServiceProjects.partner,fundingSource:communityServiceProjects.fundingSource,outputSummary:communityServiceProjects.outputSummary,projectStatus:communityServiceProjects.projectStatus,publishedAt:publications.publishedAt}).from(publications).innerJoin(communityServiceProjects,and(eq(publications.subjectType,"COMMUNITY_SERVICE_PROJECT"),eq(publications.subjectId,communityServiceProjects.id))).leftJoin(studyPrograms,eq(communityServiceProjects.studyProgramId,studyPrograms.id)).where(and(eq(publications.status,"PUBLISHED"),eq(publications.visibility,"PUBLIC")));}
export async function getPublishedStudentStats(){const database=db;if(!database)return[];return database.select({id:studentAnnualStats.id,studyProgramId:studentAnnualStats.studyProgramId,programName:studyPrograms.name,academicYear:studentAnnualStats.academicYear,activeStudents:studentAnnualStats.activeStudents,newStudents:studentAnnualStats.newStudents,graduates:studentAnnualStats.graduates,dropoutStudents:studentAnnualStats.dropoutStudents,publishedAt:publications.publishedAt}).from(publications).innerJoin(studentAnnualStats,and(eq(publications.subjectType,"STUDENT_ANNUAL_STAT"),eq(publications.subjectId,studentAnnualStats.id))).innerJoin(studyPrograms,eq(studentAnnualStats.studyProgramId,studyPrograms.id)).where(and(eq(publications.status,"PUBLISHED"),eq(publications.visibility,"PUBLIC")));}
export async function getPublishedGraduateOutcomes(){const database=db;if(!database)return[];return database.select({id:graduateOutcomeStats.id,studyProgramId:graduateOutcomeStats.studyProgramId,programName:studyPrograms.name,graduationYear:graduateOutcomeStats.graduationYear,graduates:graduateOutcomeStats.graduates,trackedGraduates:graduateOutcomeStats.trackedGraduates,employed:graduateOutcomeStats.employed,entrepreneurship:graduateOutcomeStats.entrepreneurship,furtherStudy:graduateOutcomeStats.furtherStudy,averageWaitingMonths:graduateOutcomeStats.averageWaitingMonths,relevantEmploymentPercent:graduateOutcomeStats.relevantEmploymentPercent,publishedAt:publications.publishedAt}).from(publications).innerJoin(graduateOutcomeStats,and(eq(publications.subjectType,"GRADUATE_OUTCOME_STAT"),eq(publications.subjectId,graduateOutcomeStats.id))).innerJoin(studyPrograms,eq(graduateOutcomeStats.studyProgramId,studyPrograms.id)).where(and(eq(publications.status,"PUBLISHED"),eq(publications.visibility,"PUBLIC")));}
export async function getPublishedCooperations(){const database=db;if(!database)return[];return database.select({id:cooperations.id,organizationId:cooperations.organizationId,studyProgramId:cooperations.studyProgramId,programName:studyPrograms.name,partnerName:cooperations.partnerName,partnerType:cooperations.partnerType,scope:cooperations.scope,startDate:cooperations.startDate,endDate:cooperations.endDate,implementationSummary:cooperations.implementationSummary,cooperationStatus:cooperations.cooperationStatus,publishedAt:publications.publishedAt}).from(publications).innerJoin(cooperations,and(eq(publications.subjectType,"COOPERATION"),eq(publications.subjectId,cooperations.id))).leftJoin(studyPrograms,eq(cooperations.studyProgramId,studyPrograms.id)).where(and(eq(publications.status,"PUBLISHED"),eq(publications.visibility,"PUBLIC")));}
