import { eq } from "drizzle-orm";
import { requireDb } from "@/src/db";
import { evaluations,followups,kpiMeasurements,kpis,recommendations,strategicGoals,strategicPlans,strategicStatements,studyPrograms } from "@/src/db/schema";
import { newsArticles } from "@/src/db/schema-admin";
import { cpl,cpmk,courses,curricula,curriculumCourses } from "@/src/db/schema-phase5";
import { communityServiceProjects,cooperations,graduateOutcomeStats,laboratories,laboratoryEquipment,laboratoryK3lChecks,laboratoryMaintenance,laboratoryProfiles,laboratoryUsage,personnel,researchProjects,studentAnnualStats } from "@/src/db/schema-phase6";
import type { SessionUser } from "@/src/lib/auth";
import { scopeAllows } from "@/src/lib/rbac";
import { getGovernanceScope,governanceWriteAllows } from "@/src/services/governance-scope";

export type SubjectScope={organizationId:number;studyProgramId:number|null};
async function programScope(studyProgramId:number):Promise<SubjectScope|null>{const db=requireDb();const[p]=await db.select({organizationId:studyPrograms.organizationId}).from(studyPrograms).where(eq(studyPrograms.id,studyProgramId)).limit(1);return p?{organizationId:p.organizationId,studyProgramId}:null;}
async function laboratoryScope(laboratoryId:number):Promise<SubjectScope|null>{const db=requireDb();const[lab]=await db.select({organizationId:laboratories.organizationId}).from(laboratories).where(eq(laboratories.id,laboratoryId)).limit(1);return lab?{organizationId:lab.organizationId,studyProgramId:null}:null;}

export async function resolveSubjectScope(subjectType:string,subjectId:number,depth=0):Promise<SubjectScope|null>{
 if(depth>7)return null;const db=requireDb();
 if(["STRATEGIC_PLAN","STRATEGIC_STATEMENT","STRATEGIC_GOAL","KPI"].includes(subjectType)){const gs=await getGovernanceScope(subjectType,subjectId);if(gs)return{organizationId:gs.organizationId,studyProgramId:gs.studyProgramId??null};if(subjectType==="STRATEGIC_PLAN"){const[x]=await db.select({organizationId:strategicPlans.organizationId}).from(strategicPlans).where(eq(strategicPlans.id,subjectId)).limit(1);return x?{organizationId:x.organizationId,studyProgramId:null}:null;}if(subjectType==="STRATEGIC_STATEMENT"){const[x]=await db.select({organizationId:strategicStatements.organizationId}).from(strategicStatements).where(eq(strategicStatements.id,subjectId)).limit(1);return x?{organizationId:x.organizationId,studyProgramId:null}:null;}if(subjectType==="STRATEGIC_GOAL"){const[x]=await db.select({organizationId:strategicGoals.organizationId}).from(strategicGoals).where(eq(strategicGoals.id,subjectId)).limit(1);return x?{organizationId:x.organizationId,studyProgramId:null}:null;}const[x]=await db.select({organizationId:kpis.ownerOrganizationId}).from(kpis).where(eq(kpis.id,subjectId)).limit(1);return x?{organizationId:x.organizationId,studyProgramId:null}:null;}
 if(subjectType==="KPI_MEASUREMENT"){const[x]=await db.select({kpiId:kpiMeasurements.kpiId}).from(kpiMeasurements).where(eq(kpiMeasurements.id,subjectId)).limit(1);return x?resolveSubjectScope("KPI",x.kpiId,depth+1):null;}
 if(subjectType==="CURRICULUM"){const[x]=await db.select({studyProgramId:curricula.studyProgramId}).from(curricula).where(eq(curricula.id,subjectId)).limit(1);return x?programScope(x.studyProgramId):null;}
 if(subjectType==="COURSE"){const[x]=await db.select({studyProgramId:courses.studyProgramId}).from(courses).where(eq(courses.id,subjectId)).limit(1);return x?programScope(x.studyProgramId):null;}
 if(subjectType==="CPL"){const[x]=await db.select({curriculumId:cpl.curriculumId}).from(cpl).where(eq(cpl.id,subjectId)).limit(1);return x?resolveSubjectScope("CURRICULUM",x.curriculumId,depth+1):null;}
 if(subjectType==="CPMK"){const[x]=await db.select({curriculumCourseId:cpmk.curriculumCourseId}).from(cpmk).where(eq(cpmk.id,subjectId)).limit(1);if(!x)return null;const[cc]=await db.select({curriculumId:curriculumCourses.curriculumId}).from(curriculumCourses).where(eq(curriculumCourses.id,x.curriculumCourseId)).limit(1);return cc?resolveSubjectScope("CURRICULUM",cc.curriculumId,depth+1):null;}
 if(subjectType==="LABORATORY")return laboratoryScope(subjectId);
 if(subjectType==="LABORATORY_PROFILE"){const[x]=await db.select({laboratoryId:laboratoryProfiles.laboratoryId}).from(laboratoryProfiles).where(eq(laboratoryProfiles.id,subjectId)).limit(1);return x?laboratoryScope(x.laboratoryId):null;}
 if(subjectType==="LAB_EQUIPMENT"){const[x]=await db.select({laboratoryId:laboratoryEquipment.laboratoryId}).from(laboratoryEquipment).where(eq(laboratoryEquipment.id,subjectId)).limit(1);return x?laboratoryScope(x.laboratoryId):null;}
 if(subjectType==="LAB_USAGE"){const[x]=await db.select({laboratoryId:laboratoryUsage.laboratoryId,studyProgramId:laboratoryUsage.studyProgramId}).from(laboratoryUsage).where(eq(laboratoryUsage.id,subjectId)).limit(1);if(!x)return null;const lab=await laboratoryScope(x.laboratoryId);return lab?{organizationId:lab.organizationId,studyProgramId:x.studyProgramId??null}:null;}
 if(subjectType==="LAB_MAINTENANCE"){const[x]=await db.select({equipmentId:laboratoryMaintenance.equipmentId}).from(laboratoryMaintenance).where(eq(laboratoryMaintenance.id,subjectId)).limit(1);return x?resolveSubjectScope("LAB_EQUIPMENT",x.equipmentId,depth+1):null;}
 if(subjectType==="LAB_K3L"){const[x]=await db.select({laboratoryId:laboratoryK3lChecks.laboratoryId}).from(laboratoryK3lChecks).where(eq(laboratoryK3lChecks.id,subjectId)).limit(1);return x?laboratoryScope(x.laboratoryId):null;}
 if(subjectType==="PERSONNEL"){const[x]=await db.select({organizationId:personnel.organizationId,studyProgramId:personnel.studyProgramId}).from(personnel).where(eq(personnel.id,subjectId)).limit(1);return x?{organizationId:x.organizationId,studyProgramId:x.studyProgramId??null}:null;}
 if(subjectType==="RESEARCH_PROJECT"){const[x]=await db.select({organizationId:researchProjects.organizationId,studyProgramId:researchProjects.studyProgramId}).from(researchProjects).where(eq(researchProjects.id,subjectId)).limit(1);return x?{organizationId:x.organizationId,studyProgramId:x.studyProgramId??null}:null;}
 if(subjectType==="COMMUNITY_SERVICE_PROJECT"){const[x]=await db.select({organizationId:communityServiceProjects.organizationId,studyProgramId:communityServiceProjects.studyProgramId}).from(communityServiceProjects).where(eq(communityServiceProjects.id,subjectId)).limit(1);return x?{organizationId:x.organizationId,studyProgramId:x.studyProgramId??null}:null;}
 if(subjectType==="STUDENT_ANNUAL_STAT"){const[x]=await db.select({studyProgramId:studentAnnualStats.studyProgramId}).from(studentAnnualStats).where(eq(studentAnnualStats.id,subjectId)).limit(1);return x?programScope(x.studyProgramId):null;}
 if(subjectType==="GRADUATE_OUTCOME_STAT"){const[x]=await db.select({studyProgramId:graduateOutcomeStats.studyProgramId}).from(graduateOutcomeStats).where(eq(graduateOutcomeStats.id,subjectId)).limit(1);return x?programScope(x.studyProgramId):null;}
 if(subjectType==="COOPERATION"){const[x]=await db.select({organizationId:cooperations.organizationId,studyProgramId:cooperations.studyProgramId}).from(cooperations).where(eq(cooperations.id,subjectId)).limit(1);return x?{organizationId:x.organizationId,studyProgramId:x.studyProgramId??null}:null;}
 if(subjectType==="NEWS_ARTICLE"){const[x]=await db.select({organizationId:newsArticles.organizationId}).from(newsArticles).where(eq(newsArticles.id,subjectId)).limit(1);return x?{organizationId:x.organizationId,studyProgramId:null}:null;}
 if(subjectType==="EVALUATION"){const[x]=await db.select({subjectType:evaluations.subjectType,subjectId:evaluations.subjectId}).from(evaluations).where(eq(evaluations.id,subjectId)).limit(1);return x?resolveSubjectScope(x.subjectType,x.subjectId,depth+1):null;}
 if(subjectType==="FOLLOWUP"){const[x]=await db.select({recommendationId:followups.recommendationId}).from(followups).where(eq(followups.id,subjectId)).limit(1);if(!x)return null;const[r]=await db.select({evaluationId:recommendations.evaluationId}).from(recommendations).where(eq(recommendations.id,x.recommendationId)).limit(1);return r?resolveSubjectScope("EVALUATION",r.evaluationId,depth+1):null;}
 return null;
}
export async function subjectScopeAllows(user:SessionUser,subjectType:string,subjectId:number){const scope=await resolveSubjectScope(subjectType,subjectId);return !!scope&&scopeAllows(user,scope.organizationId,scope.studyProgramId);}
export async function subjectWriteScopeAllows(user:SessionUser,subjectType:string,subjectId:number){const scope=await resolveSubjectScope(subjectType,subjectId);return !!scope&&governanceWriteAllows(user,scope.organizationId,scope.studyProgramId);}
