import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { approvals, publications } from "@/src/db/schema";
import { newsArticles } from "@/src/db/schema-admin";
import { getSession } from "@/src/lib/auth";
import { can,scopeAllows } from "@/src/lib/rbac";
import { audit } from "@/src/lib/audit";

const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const patch=z.object({categoryId:z.number().int().positive().nullable().optional(),title:z.string().min(3).max(500).optional(),slug:z.string().max(550).optional(),excerpt:z.string().max(2000).nullable().optional(),body:z.string().min(1).optional(),coverImageUrl:z.string().url().nullable().optional(),featured:z.boolean().optional(),lifecycleStatus:z.enum(["DRAFT","SUBMITTED","ARCHIVED"]).optional()});
async function idOf(params:Promise<{id:string}>){const {id}=await params;const n=Number(id);return Number.isInteger(n)&&n>0?n:null;}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"news.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patch.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(newsArticles).where(eq(newsArticles.id,id)).limit(1);if(!before)return NextResponse.json({error:"Not found"},{status:404});if(!scopeAllows(s,before.organizationId))return NextResponse.json({error:"Scope organisasi tidak sesuai."},{status:403});if(before.lifecycleStatus==="APPROVED"||before.lifecycleStatus==="PUBLISHED")return NextResponse.json({error:"Berita yang sudah disetujui/published bersifat immutable. Buat revisi sebagai record baru agar jejak publikasi tetap auditable."},{status:409});const values={...p.data,...(p.data.slug?{slug:slugify(p.data.slug)}:{}),updatedAt:new Date()};await db.update(newsArticles).set(values).where(eq(newsArticles.id,id));await audit({actorId:s.userId,action:"UPDATE_NEWS_ARTICLE",subjectType:"NEWS_ARTICLE",subjectId:id,before,after:values});return NextResponse.json({id,...values});}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"news.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(newsArticles).where(eq(newsArticles.id,id)).limit(1);if(!before)return NextResponse.json({error:"Not found"},{status:404});if(!scopeAllows(s,before.organizationId))return NextResponse.json({error:"Scope organisasi tidak sesuai."},{status:403});if(before.lifecycleStatus!=="DRAFT")return NextResponse.json({error:"Hanya draft yang belum diajukan dapat dihapus permanen. Record proses/publikasi harus dipertahankan sebagai jejak audit."},{status:409});const[approval,publication]=await Promise.all([db.select({id:approvals.id}).from(approvals).where(and(eq(approvals.subjectType,"NEWS_ARTICLE"),eq(approvals.subjectId,id))).limit(1),db.select({id:publications.id}).from(publications).where(and(eq(publications.subjectType,"NEWS_ARTICLE"),eq(publications.subjectId,id))).limit(1)]);if(approval.length||publication.length)return NextResponse.json({error:"Berita sudah memiliki jejak persetujuan atau publikasi dan tidak dapat dihapus permanen."},{status:409});await db.delete(newsArticles).where(eq(newsArticles.id,id));await audit({actorId:s.userId,action:"DELETE_NEWS_ARTICLE",subjectType:"NEWS_ARTICLE",subjectId:id,before,after:null});return NextResponse.json({id,deleted:true});}
