import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { permissions,rolePermissions,roles } from "@/src/db/schema";
import { roleSettings } from "@/src/db/schema-admin";
import { getSession } from "@/src/lib/auth";
import { can } from "@/src/lib/rbac";
import { audit } from "@/src/lib/audit";

const patch=z.object({name:z.string().min(2).max(255).optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional(),permissionCodes:z.array(z.string().min(2)).optional()});
async function idOf(params:Promise<{id:string}>){const {id}=await params;const n=Number(id);return Number.isInteger(n)&&n>0?n:null;}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"roles.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patch.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const [before]=await db.select({id:roles.id,code:roles.code,name:roles.name,status:roleSettings.status,isSystemRole:roleSettings.isSystemRole}).from(roles).leftJoin(roleSettings,eq(roleSettings.roleId,roles.id)).where(eq(roles.id,id)).limit(1);if(!before)return NextResponse.json({error:"Not found"},{status:404});if(before.isSystemRole&&p.data.status==="ARCHIVED")return NextResponse.json({error:"Role inti sistem tidak dapat diarsipkan."},{status:409});if(p.data.name)await db.update(roles).set({name:p.data.name}).where(eq(roles.id,id));if(p.data.status)await db.update(roleSettings).set({status:p.data.status,updatedAt:new Date()}).where(eq(roleSettings.roleId,id));if(p.data.permissionCodes){await db.delete(rolePermissions).where(eq(rolePermissions.roleId,id));for(const code of p.data.permissionCodes){const [perm]=await db.select({id:permissions.id}).from(permissions).where(eq(permissions.code,code)).limit(1);if(perm)await db.insert(rolePermissions).values({roleId:id,permissionId:perm.id});}}await audit({actorId:s.userId,action:"UPDATE_ROLE",subjectType:"ROLE",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"roles.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const [role]=await db.select({id:roles.id,code:roles.code,isSystemRole:roleSettings.isSystemRole}).from(roles).leftJoin(roleSettings,eq(roleSettings.roleId,roles.id)).where(eq(roles.id,id)).limit(1);if(!role)return NextResponse.json({error:"Not found"},{status:404});if(role.isSystemRole)return NextResponse.json({error:"Role inti sistem tidak dapat dihapus."},{status:409});await db.update(roleSettings).set({status:"ARCHIVED",updatedAt:new Date()}).where(eq(roleSettings.roleId,id));await audit({actorId:s.userId,action:"ARCHIVE_ROLE",subjectType:"ROLE",subjectId:id,before:role,after:{status:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
