import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { requireDb } from "@/src/db";
import { organizations,publications,studyPrograms,users } from "@/src/db/schema";
import { accreditationAssessments,studyProgramAccreditationFrameworks } from "@/src/db/schema-accreditation";
import { validFederationExportToken } from "@/src/services/federation-security";

export const dynamic="force-dynamic";
export async function GET(req:Request){const token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")??"";if(!validFederationExportToken(token))return NextResponse.json({error:"Federation token tidak valid."},{status:401});const db=requireDb();const[orgRows,programRows,userRows,assignmentRows,assessmentRows,publicationRows]=await Promise.all([db.select({code:organizations.code,name:organizations.name,status:organizations.status}).from(organizations),db.select({status:studyPrograms.status}).from(studyPrograms),db.select({status:users.status}).from(users),db.select({status:studyProgramAccreditationFrameworks.assignmentStatus}).from(studyProgramAccreditationFrameworks),db.select({workflowStatus:accreditationAssessments.workflowStatus,readinessStatus:accreditationAssessments.readinessStatus}).from(accreditationAssessments),db.select({status:publications.status}).from(publications).where(eq(publications.status,"PUBLISHED"))]);const primary=orgRows.find(row=>row.status==="ACTIVE")??orgRows[0];const byWorkflow=(status:string)=>assessmentRows.filter(row=>row.workflowStatus===status).length;return NextResponse.json({schemaVersion:1,generatedAt:new Date().toISOString(),application:{code:process.env.FEDERATION_APPLICATION_CODE??primary?.code??"JURUSAN",name:process.env.FEDERATION_APPLICATION_NAME??primary?.name??"Aplikasi Jurusan"},organization:{code:primary?.code??null,name:primary?.name??null},counts:{studyPrograms:programRows.filter(row=>row.status==="ACTIVE").length,activeUsers:userRows.filter(row=>row.status==="ACTIVE").length,frameworkAssignments:assignmentRows.filter(row=>row.status==="ACTIVE").length,assessments:assessmentRows.length,draft:byWorkflow("DRAFT"),submitted:byWorkflow("SUBMITTED"),approved:byWorkflow("APPROVED"),publishedAssessments:byWorkflow("PUBLISHED"),publications:publicationRows.length,gaps:assessmentRows.filter(row=>row.readinessStatus==="GAP").length}});}
