import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { laboratoryUsage } from "@/src/db/schema-phase6";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { canReadResourceScope,canWriteResourceScope,getLaboratoryScope,laboratoryServesProgram,validateProgramUnderOrganization } from "@/src/services/resource-scope";
const createInput=z.object({laboratoryId:z.number().int().positive(),studyProgramId:z.number().int().positive().nullable().optional(),activityType:z.enum(["PRACTICUM","RESEARCH","COMMUNITY_SERVICE","TRAINING","OTHER"]),title:z.string().min(3).max(500),usageDate:z.string().min(8).max(20),participantCount:z.number().int().nonnegative().default(0),durationHours:z.number().nonnegative().optional()});
const patchInput=z.object({activityType:z.enum(["PRACTICUM","RESEARCH","COMMUNITY_SERVICE","TRAINING","OTHER"]).optional(),title:z.string().min(3).max(500).optional(),usageDate:z.string().min(8).max(20).optional(),participantCount:z.number().int().nonnegative().optional(),durationHours:z.number().nonnegative().nullable().optional(),status:z.enum(["RECORDED","VERIFIED","ARCHIVED"]).optional()});
function idParam(req:Request,key="id"){const n=Number(new URL(req.url).searchParams.get(key));return Number.isInteger(n)&&n>0?n:null;}
export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const laboratoryId=idParam(req,"laboratoryId");const db=requireDb();const rows=laboratoryId?await db.select().from(laboratoryUsage).where(eq(laboratoryUsage.laboratoryId,laboratoryId)):await db.select().from(laboratoryUsage);const allowed=[];for(const row of rows){const lab=await getLaboratoryScope(row.laboratoryId);if(lab&&canReadResourceScope(s,lab.organizationId,row.studyProgramId))allowed.push(row);}return NextResponse.json(allowed);}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const p=createInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const lab=await getLaboratoryScope(p.data.laboratoryId);if(!lab)return NextResponse.json({error:"Laboratorium tidak ditemukan."},{status:404});const programId=p.data.studyProgramId??null;if(programId){if(!(await validateProgramUnderOrganization(programId,lab.organizationId)))return NextResponse.json({error:"Program Studi tidak sesuai dengan UPPS laboratorium."},{status:409});if(!(await laboratoryServesProgram(lab.id,programId)))return NextResponse.json({error:"Laboratorium belum dipetakan sebagai fasilitas Program Studi ini."},{status:409});}if(!canWriteResourceScope(s,lab.organizationId,programId,false))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const x=await db.insert(laboratoryUsage).values({laboratoryId:p.data.laboratoryId,studyProgramId:programId,activityType:p.data.activityType,title:p.data.title,usageDate:p.data.usageDate,participantCount:p.data.participantCount,durationHours:p.data.durationHours?.toString(),recordedBy:s.userId,status:"RECORDED"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_LAB_USAGE",subjectType:"LAB_USAGE",subjectId:id,after:p.data});return NextResponse.json({id,status:"RECORDED"},{status:201});}
export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patchInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(laboratoryUsage).where(eq(laboratoryUsage.id,id)).limit(1);if(!before)return NextResponse.json({error:"Record tidak ditemukan."},{status:404});const lab=await getLaboratoryScope(before.laboratoryId);if(!lab||!canWriteResourceScope(s,lab.organizationId,before.studyProgramId,false))return NextResponse.json({error:"Forbidden"},{status:403});const update={...p.data,durationHours:p.data.durationHours===undefined?undefined:p.data.durationHours===null?null:p.data.durationHours.toString()};await db.update(laboratoryUsage).set(update).where(eq(laboratoryUsage.id,id));await audit({actorId:s.userId,action:"UPDATE_LAB_USAGE",subjectType:"LAB_USAGE",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(laboratoryUsage).where(eq(laboratoryUsage.id,id)).limit(1);if(!before)return NextResponse.json({error:"Record tidak ditemukan."},{status:404});const lab=await getLaboratoryScope(before.laboratoryId);if(!lab||!canWriteResourceScope(s,lab.organizationId,before.studyProgramId,false))return NextResponse.json({error:"Forbidden"},{status:403});await db.update(laboratoryUsage).set({status:"ARCHIVED"}).where(eq(laboratoryUsage.id,id));await audit({actorId:s.userId,action:"ARCHIVE_LAB_USAGE",subjectType:"LAB_USAGE",subjectId:id,before,after:{status:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
