import { and,eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { laboratoryPrograms } from "@/src/db/schema-phase6";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { canReadResourceScope,canWriteResourceScope,getLaboratoryScope,validateProgramUnderOrganization } from "@/src/services/resource-scope";
const input=z.object({laboratoryId:z.number().int().positive(),studyProgramId:z.number().int().positive()});
export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const laboratoryId=Number(new URL(req.url).searchParams.get("laboratoryId"));if(!Number.isInteger(laboratoryId)||laboratoryId<=0)return NextResponse.json({error:"laboratoryId wajib."},{status:400});const lab=await getLaboratoryScope(laboratoryId);if(!lab||!canReadResourceScope(s,lab.organizationId,null))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();return NextResponse.json(await db.select().from(laboratoryPrograms).where(eq(laboratoryPrograms.laboratoryId,laboratoryId)));}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const p=input.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const lab=await getLaboratoryScope(p.data.laboratoryId);if(!lab)return NextResponse.json({error:"Laboratorium tidak ditemukan."},{status:404});if(!canWriteResourceScope(s,lab.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});if(!(await validateProgramUnderOrganization(p.data.studyProgramId,lab.organizationId)))return NextResponse.json({error:"Program Studi tidak berada pada UPPS laboratorium ini."},{status:409});const db=requireDb();await db.insert(laboratoryPrograms).values(p.data).onDuplicateKeyUpdate({set:{studyProgramId:p.data.studyProgramId}});await audit({actorId:s.userId,action:"MAP_LABORATORY_PROGRAM",subjectType:"LABORATORY",subjectId:p.data.laboratoryId,after:{studyProgramId:p.data.studyProgramId}});return NextResponse.json(p.data,{status:201});}
export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const q=new URL(req.url).searchParams;const laboratoryId=Number(q.get("laboratoryId")),studyProgramId=Number(q.get("studyProgramId"));if(!Number.isInteger(laboratoryId)||!Number.isInteger(studyProgramId)||laboratoryId<=0||studyProgramId<=0)return NextResponse.json({error:"laboratoryId dan studyProgramId wajib."},{status:400});const lab=await getLaboratoryScope(laboratoryId);if(!lab||!canWriteResourceScope(s,lab.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();await db.delete(laboratoryPrograms).where(and(eq(laboratoryPrograms.laboratoryId,laboratoryId),eq(laboratoryPrograms.studyProgramId,studyProgramId)));await audit({actorId:s.userId,action:"UNMAP_LABORATORY_PROGRAM",subjectType:"LABORATORY",subjectId:laboratoryId,before:{studyProgramId}});return NextResponse.json({laboratoryId,studyProgramId,removed:true});}
