"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
type Row=Record<string,any>;
type Assignment={assignmentId:number;programCode:string;programName:string;organizationName:string;frameworkCode:string;frameworkName:string;frameworkYear:number|null;agencyCode:string;agencyName:string;isPrimary:boolean};
async function request(url:string,method="GET",body?:unknown){const response=await fetch(url,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Operasi gagal.");return data;}
const groupMeta:Record<string,{label:string;title:string;description:string}>={INPUT:{label:"01 · INPUT",title:"Masukan",description:"Data dasar, tata kelola, SDM, mahasiswa, sarana, dan dokumen yang menjadi prasyarat."},PROCESS:{label:"02 · PROCESS",title:"Proses",description:"Pelaksanaan pendidikan, penelitian, PkM, kerja sama, penjaminan mutu, dan evaluasi."},OUTPUT_OUTCOME:{label:"03 · OUTPUT / OUTCOME",title:"Luaran dan dampak",description:"Capaian, lulusan, produk, kinerja, tindak lanjut, dan hasil yang dapat dipertanggungjawabkan."}};

export default function AccreditationCockpit({assignments,permissions}:{assignments:Assignment[];permissions:string[]}){
  const primary=assignments.find(row=>row.isPrimary)??assignments[0];
  const[assignmentId,setAssignmentId]=useState(primary?.assignmentId??0),[period,setPeriod]=useState("2026"),[rows,setRows]=useState<Row[]>([]),[filter,setFilter]=useState("ALL"),[message,setMessage]=useState("");
  const selected=assignments.find(row=>row.assignmentId===assignmentId);
  const canAssess=permissions.includes("accreditation.assess"),canApprove=permissions.includes("accreditation.approve"),canPublish=permissions.includes("accreditation.publish");
  async function load(){if(!assignmentId)return setRows([]);try{const data=await request(`/api/internal/accreditation/assessments?assignmentId=${assignmentId}&period=${encodeURIComponent(period)}`);setRows(data.indicators);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Gagal memuat evaluasi");}}
  useEffect(()=>{void load()},[assignmentId,period]);
  const groups=useMemo(()=>Object.keys(groupMeta).map(code=>({code,rows:rows.filter(row=>(row.clusters??[]).some((cluster:Row)=>cluster.semanticGroup===code)&&(filter==="ALL"||row.criterionCode===filter))})),[rows,filter]);
  const criteria=[...new Map(rows.map(row=>[row.criterionCode,row.criterionName])).entries()];
  const totals={all:rows.length,draft:rows.filter(row=>!row.assessment||row.assessment.workflowStatus==="DRAFT").length,submitted:rows.filter(row=>row.assessment?.workflowStatus==="SUBMITTED").length,approved:rows.filter(row=>row.assessment?.workflowStatus==="APPROVED").length,published:rows.filter(row=>row.assessment?.workflowStatus==="PUBLISHED").length};
  return <div className="evaluation-workspace">
    <section className="evaluation-intro"><div><span className="eyebrow">Ruang kerja evaluasi akreditasi</span><h1>Isi → Hitung → Analisis → Evaluasi → Catatan LED → Setujui → Publikasikan</h1><p>Setiap indikator bergerak melalui satu alur. Nilai dihitung dari variabel dan rubrik registry; hanya hasil yang disetujui dan ditandai kandidat publik yang dapat diterbitkan.</p></div><ol><li><b>Admin/Kaprodi</b><span>mengisi data dan evidence</span></li><li><b>Sistem</b><span>menghitung nilai dan rubrik</span></li><li><b>Kaprodi/Kajur</b><span>menilai serta menyetujui</span></li><li><b>Kajur/UPPS</b><span>menetapkan publikasi</span></li></ol></section>
    <section className="cockpit-context"><label><span>Lingkup evaluasi</span><select value={assignmentId} onChange={event=>setAssignmentId(Number(event.target.value))}>{assignments.map(row=><option key={row.assignmentId} value={row.assignmentId}>{row.organizationName} · {row.programName} · {row.agencyCode}</option>)}</select></label><label><span>Periode</span><input value={period} onChange={event=>setPeriod(event.target.value)}/></label><label><span>Kriteria instrumen</span><select value={filter} onChange={event=>setFilter(event.target.value)}><option value="ALL">Semua kriteria</option>{criteria.map(([code,name])=><option key={String(code)} value={String(code)}>{String(code)} · {String(name)}</option>)}</select></label></section>
    {selected&&<div className="scope-banner"><strong>{selected.organizationName}</strong><span>{selected.programCode} · {selected.programName}</span><span>{selected.agencyName}</span><span>{selected.frameworkName} · {period}</span>{selected.frameworkCode.includes("DEMO")&&<em>Framework demo — ganti melalui Registry</em>}</div>}
    <section className="cockpit-summary"><div><strong>{totals.all}</strong><span>Total indikator</span></div><div><strong>{totals.draft}</strong><span>Belum diajukan</span></div><div><strong>{totals.submitted}</strong><span>Menunggu persetujuan</span></div><div><strong>{totals.approved}</strong><span>Disetujui</span></div><div><strong>{totals.published}</strong><span>Dipublikasikan</span></div></section>
    {message&&<p className="cockpit-message">{message}</p>}{!assignments.length&&<div className="cockpit-empty">Belum ada framework aktif yang ditautkan ke Program Studi.</div>}
    {groups.map(group=>{const meta=groupMeta[group.code];return <section className={`ipo-assessment ${group.code.toLowerCase()}`} key={group.code}><header><div><span>{meta.label}</span><h2>{meta.title}</h2><p>{meta.description}</p></div><strong>{group.rows.length} indikator</strong></header>{group.rows.length?group.rows.map(row=><IndicatorCard key={row.id} row={row} assignmentId={assignmentId} period={period} canAssess={canAssess} canApprove={canApprove} canPublish={canPublish} onDone={async text=>{setMessage(text);await load()}}/>):<p className="cockpit-empty">Tidak ada indikator pada kelompok ini.</p>}</section>})}
  </div>;
}

function IndicatorCard({row,assignmentId,period,canAssess,canApprove,canPublish,onDone}:{row:Row;assignmentId:number;period:string;canAssess:boolean;canApprove:boolean;canPublish:boolean;onDone:(text:string)=>Promise<void>}){
  const assessment=row.assessment??{},source=row.sources?.[0]??{};const stored=new Map((row.values??[]).map((value:Row)=>[value.variableId,value.rawValue]));const formulaMode=(row.scoringRule as Row)?.method!=="MANUAL"&&Boolean((row.scoringRule as Row)?.expression);
  async function saveForm(form:HTMLFormElement,workflowStatus:"DRAFT"|"SUBMITTED"){const data=new FormData(form);try{const result=await request("/api/internal/accreditation/assessments","POST",{assignmentId,indicatorId:row.id,period,readinessStatus:String(data.get("readinessStatus")),actualValue:String(data.get("actualValue")||""),manualScore:data.get("manualScore")===""?undefined:Number(data.get("manualScore")),calculationNote:String(data.get("calculationNote")||""),analysis:String(data.get("analysis")||""),evaluationNote:String(data.get("evaluationNote")||""),ledNote:String(data.get("ledNote")||""),publicationDecision:String(data.get("publicationDecision")),workflowStatus,values:(row.variables??[]).map((variable:Row)=>({variableId:variable.id,rawValue:String(data.get(`variable-${variable.id}`)??"")})),sourceSubjectType:String(data.get("sourceSubjectType")||""),sourceSubjectId:Number(data.get("sourceSubjectId"))||undefined,referenceTitle:String(data.get("referenceTitle")||""),sourceNote:String(data.get("sourceNote")||""),includeInPublic:data.get("includeInPublic")==="on"});await onDone(`Indikator ${row.code} tersimpan: ${result.status}.`);}catch(error){await onDone(error instanceof Error?error.message:"Gagal menyimpan");}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();await saveForm(event.currentTarget,"SUBMITTED");}
  async function action(name:string){try{const result=await request("/api/internal/accreditation/assessments","PATCH",{assessmentId:assessment.id,action:name});await onDone(`Indikator ${row.code}: ${result.status}.`);}catch(error){await onDone(error instanceof Error?error.message:"Operasi gagal");}}
  return <article className="indicator-card"><header><div><span>{row.criterionCode}</span><strong>{row.code}</strong></div><div><h3>{row.name}</h3><p>{row.description}</p></div><div className="indicator-state"><b>{assessment.readinessStatus??"NOT_ASSESSED"}</b><small>{assessment.workflowStatus??"DRAFT"}</small></div></header><form onSubmit={submit}>
    <section className="indicator-step"><div className="step-label"><b>1</b><span>Input data</span></div><div className="assessment-grid">{(row.variables??[]).map((variable:Row)=><label key={variable.id}><span>{variable.label}{variable.required?" *":""}</span>{variable.valueType==="BOOLEAN"?<select name={`variable-${variable.id}`} defaultValue={String(stored.get(variable.id)??variable.defaultValue??"")}><option value="">Pilih</option><option value="true">Ya</option><option value="false">Tidak</option></select>:<input name={`variable-${variable.id}`} type={variable.valueType==="NUMBER"?"number":"text"} step="any" defaultValue={String(stored.get(variable.id)??variable.defaultValue??"")} placeholder={variable.unit??undefined}/>}</label>)}{!(row.variables??[]).length&&<label><span>Nilai/fakta aktual</span><input name="actualValue" defaultValue={assessment.actualValue??""}/></label>}<label><span>Status kesiapan</span><select name="readinessStatus" defaultValue={assessment.readinessStatus??"NOT_ASSESSED"}><option>NOT_ASSESSED</option><option>IN_PROGRESS</option><option>COMPLETE</option><option>GAP</option></select></label></div></section>
    <section className="indicator-step"><div className="step-label"><b>2</b><span>Perhitungan</span></div><div className="calculation-panel"><div><small>Metode</small><strong>{formulaMode?"Otomatis dari rumus registry":"Skor manual sesuai rubrik"}</strong></div><div><small>Hasil</small><strong>{assessment.calculatedValue??"Belum dihitung"}{row.unit?` ${row.unit}`:""}</strong></div><div><small>Skor</small><strong>{assessment.calculatedScore??"—"}</strong></div><div><small>Skor berbobot</small><strong>{assessment.weightedScore??"—"}</strong></div>{!formulaMode&&<label><span>Skor manual</span><input name="manualScore" type="number" step="any" defaultValue={assessment.calculatedScore??""}/></label>}</div><label><span>Catatan/penjelasan perhitungan</span><textarea name="calculationNote" defaultValue={assessment.calculationNote??""}/></label></section>
    <section className="indicator-step"><div className="step-label"><b>3–5</b><span>Analisis, evaluasi, LED</span></div><div className="assessment-grid text"><label><span>Analisis hasil</span><textarea name="analysis" defaultValue={assessment.analysis??""} placeholder="Apa arti hasil ini terhadap indikator?"/></label><label><span>Evaluasi dan gap</span><textarea name="evaluationNote" defaultValue={assessment.evaluationNote??""} placeholder="Apa yang belum tercapai dan penyebabnya?"/></label><label><span>Catatan LED</span><textarea name="ledNote" defaultValue={assessment.ledNote??""} placeholder="Narasi yang perlu dimasukkan ke LED"/></label></div></section>
    <section className="indicator-step"><div className="step-label"><b>6</b><span>Evidence</span></div><div className="source-row"><label><span>Tipe sumber</span><input name="sourceSubjectType" defaultValue={source.sourceSubjectType??""} placeholder="KPI / VMTS / KURIKULUM / ..."/></label><label><span>ID data</span><input name="sourceSubjectId" type="number" defaultValue={source.sourceSubjectId??""}/></label><label><span>Judul evidence</span><input name="referenceTitle" defaultValue={source.referenceTitle??""}/></label><label><span>Catatan evidence</span><input name="sourceNote" defaultValue={source.note??""}/></label></div></section>
    <section className="indicator-step publication-step"><div className="step-label"><b>7</b><span>Keputusan</span></div><label><span>Keputusan publikasi</span><select name="publicationDecision" defaultValue={assessment.publicationDecision??"INTERNAL_ONLY"}><option value="INTERNAL_ONLY">Internal / LED saja</option><option value="PUBLIC_CANDIDATE">Ajukan sebagai kandidat publik</option></select></label><label className="check"><input type="checkbox" name="includeInPublic" defaultChecked={source.includeInPublic??false}/><span>Evidence ini boleh tampil publik</span></label></section>
    <footer>{canAssess&&assessment.workflowStatus!=="APPROVED"&&assessment.workflowStatus!=="PUBLISHED"&&<><button type="button" onClick={event=>void saveForm(event.currentTarget.form!,"DRAFT")}>Simpan draft</button><button type="submit">Ajukan evaluasi</button></>}{canApprove&&assessment.id&&assessment.workflowStatus==="SUBMITTED"&&<><button type="button" onClick={()=>void action("APPROVE")}>Setujui</button><button className="secondary" type="button" onClick={()=>void action("RETURN")}>Kembalikan</button></>}{canPublish&&assessment.id&&assessment.workflowStatus==="APPROVED"&&assessment.publicationDecision==="PUBLIC_CANDIDATE"&&<button className="publish" type="button" onClick={()=>void action("PUBLISH")}>Publikasikan</button>}</footer>
  </form></article>;
}
