"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
type Row=Record<string,any>;
type Assignment={assignmentId:number;programCode:string;programName:string;organizationName:string;frameworkCode:string;frameworkName:string;frameworkYear:number|null;agencyCode:string;agencyName:string;isPrimary:boolean};
async function request(url:string,method="GET",body?:unknown){const response=await fetch(url,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Operasi gagal.");return data;}
const groupMeta:Record<string,{label:string;title:string;description:string}>={INPUT:{label:"01 · INPUT",title:"Masukan",description:"Data dasar, tata kelola, SDM, mahasiswa, sarana, dan dokumen yang menjadi prasyarat."},PROCESS:{label:"02 · PROCESS",title:"Proses",description:"Pelaksanaan pendidikan, penelitian, PkM, kerja sama, penjaminan mutu, dan evaluasi."},OUTPUT_OUTCOME:{label:"03 · OUTPUT / OUTCOME",title:"Luaran dan dampak",description:"Capaian, lulusan, produk, kinerja, tindak lanjut, dan hasil yang dapat dipertanggungjawabkan."}};

export default function AccreditationCockpit({assignments,permissions}:{assignments:Assignment[];permissions:string[]}){
  const primary=assignments.find(row=>row.isPrimary)??assignments[0];
  const[assignmentId,setAssignmentId]=useState(primary?.assignmentId??0),[period,setPeriod]=useState(""),[periodOptions,setPeriodOptions]=useState<Row[]>([]),[rows,setRows]=useState<Row[]>([]),[filter,setFilter]=useState("ALL"),[message,setMessage]=useState(""),[showReport,setShowReport]=useState(false);
  const selected=assignments.find(row=>row.assignmentId===assignmentId);
  const canAssess=permissions.includes("accreditation.assess"),canApprove=permissions.includes("accreditation.approve"),canPublish=permissions.includes("accreditation.publish");
  async function load(){if(!assignmentId||!period)return setRows([]);try{const data=await request(`/api/internal/accreditation/assessments?assignmentId=${assignmentId}&period=${encodeURIComponent(period)}`);setRows(data.indicators);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Gagal memuat evaluasi");}}
  useEffect(()=>{void request("/api/internal/evaluation-periods").then(data=>{setPeriodOptions(data);if(data[0])setPeriod(data[0].label)}).catch(()=>setMessage("Periode belum dapat dimuat."))},[]);useEffect(()=>{void load()},[assignmentId,period]);
  const groups=useMemo(()=>Object.keys(groupMeta).map(code=>({code,rows:rows.filter(row=>(row.clusters??[]).some((cluster:Row)=>cluster.semanticGroup===code)&&(filter==="ALL"||row.criterionCode===filter))})),[rows,filter]);
  const criteria=[...new Map(rows.map(row=>[row.criterionCode,row.criterionName])).entries()];
  const totals={all:rows.length,draft:rows.filter(row=>!row.assessment||row.assessment.workflowStatus==="DRAFT").length,submitted:rows.filter(row=>row.assessment?.workflowStatus==="SUBMITTED").length,approved:rows.filter(row=>row.assessment?.workflowStatus==="APPROVED").length,published:rows.filter(row=>row.assessment?.workflowStatus==="PUBLISHED").length};
  return <div className="evaluation-workspace">
    <section className="evaluation-intro"><div><span className="eyebrow">Ruang kerja evaluasi akreditasi</span><h1>Mandat → Isi → Hitung → Evaluasi → Validasi → Publikasi</h1><p>Setiap indikator hanya dapat diisi oleh penanggung jawab yang ditetapkan Admin Jurusan. Kajur memvalidasi hasil dan menetapkan publikasi.</p></div><ol><li><b>Admin Jurusan</b><span>membagi indikator ke Prodi atau UPPS</span></li><li><b>Admin/Kaprodi</b><span>mengisi sesuai mandat dan scope</span></li><li><b>Sistem</b><span>menghitung nilai dari rubrik</span></li><li><b>Kajur</b><span>memvalidasi dan mempublikasikan</span></li></ol></section>
    <section className="cockpit-context"><label><span>Lingkup evaluasi</span><select value={assignmentId} onChange={event=>setAssignmentId(Number(event.target.value))}>{assignments.map(row=><option key={row.assignmentId} value={row.assignmentId}>{row.organizationName} · {row.programName} · {row.agencyCode}</option>)}</select></label><label><span>Periode dari Admin Jurusan</span><select value={period} onChange={event=>setPeriod(event.target.value)}><option value="">Pilih periode</option>{periodOptions.map(option=><option key={option.id} value={option.label}>{option.label.replace("-"," ")} · {option.status}</option>)}</select></label><label><span>Kriteria instrumen</span><select value={filter} onChange={event=>setFilter(event.target.value)}><option value="ALL">Semua kriteria</option>{criteria.map(([code,name])=><option key={String(code)} value={String(code)}>{String(code)} · {String(name)}</option>)}</select></label></section>
    {selected&&<div className="scope-banner"><strong>{selected.organizationName}</strong><span>{selected.programCode} · {selected.programName}</span><span>{selected.agencyName}</span><span>{selected.frameworkName} · {period}</span>{selected.frameworkCode.includes("DEMO")&&<em>Framework demo — ganti melalui Registry</em>}</div>}
    <section className="cockpit-summary"><div><strong>{totals.all}</strong><span>Total indikator</span></div><div><strong>{totals.draft}</strong><span>Belum diajukan</span></div><div><strong>{totals.submitted}</strong><span>Menunggu persetujuan</span></div><div><strong>{totals.approved}</strong><span>Disetujui</span></div><div><strong>{totals.published}</strong><span>Dipublikasikan</span></div></section>
    <section className="led-toolbar"><div><b>Laporan Evaluasi Diri (LED)</b><span>Rangkuman perhitungan, evaluasi, gap, dan rencana tindak lanjut periode terpilih.</span></div><button type="button" onClick={()=>setShowReport(value=>!value)}>{showReport?"Tutup laporan":"Lihat laporan LED"}</button>{showReport&&<button type="button" onClick={()=>window.print()}>Cetak / simpan PDF</button>}</section>
    {showReport&&<section className="led-report"><header><span>LAPORAN EVALUASI DIRI</span><h2>{selected?.programName} · {period.replace("-"," ")}</h2><p>{selected?.organizationName} · {selected?.frameworkName}</p></header>{rows.filter(row=>row.assessment).map(row=><article key={row.id}><h3>{row.code} · {row.name}</h3><div className="led-score"><span>Nilai: <b>{row.assessment.calculatedValue??"—"}</b></span><span>Skor: <b>{row.assessment.calculatedScore??"—"}</b></span><span>Status: <b>{row.assessment.readinessStatus}</b></span></div><p><b>Analisis:</b> {row.assessment.analysis||"Belum diisi"}</p><p><b>Evaluasi/gap:</b> {row.assessment.evaluationNote||"Belum diisi"}</p><p><b>Rencana tindak lanjut:</b> {row.assessment.followupPlan||"Belum diisi"}</p><p><b>Narasi LED:</b> {row.assessment.ledNote||"Belum diisi"}</p><small>Keputusan: {row.assessment.publicationDecision==="PUBLIC_CANDIDATE"?"Kandidat publikasi":"Internal/LED"}</small></article>)}{!rows.some(row=>row.assessment)&&<p>Belum ada hasil asesmen pada periode ini.</p>}</section>}
    {message&&<p className="cockpit-message">{message}</p>}{!assignments.length&&<div className="cockpit-empty">Belum ada framework aktif yang ditautkan ke Program Studi.</div>}
    {groups.map(group=>{const meta=groupMeta[group.code];return <section className={`ipo-assessment ${group.code.toLowerCase()}`} key={group.code}><header><div><span>{meta.label}</span><h2>{meta.title}</h2><p>{meta.description}</p></div><strong>{group.rows.length} indikator</strong></header>{group.rows.length?group.rows.map(row=><IndicatorCard key={row.id} row={row} assignmentId={assignmentId} period={period} canAssess={canAssess} canApprove={canApprove} canPublish={canPublish} onDone={async text=>{setMessage(text);await load()}}/>):<p className="cockpit-empty">Tidak ada indikator pada kelompok ini.</p>}</section>})}
  </div>;
}

function IndicatorCard({row,assignmentId,period,canAssess,canApprove,canPublish,onDone}:{row:Row;assignmentId:number;period:string;canAssess:boolean;canApprove:boolean;canPublish:boolean;onDone:(text:string)=>Promise<void>}){
  const assessment=row.assessment??{},source=row.sources?.[0]??{};
  async function saveForm(form:HTMLFormElement,workflowStatus:"DRAFT"|"SUBMITTED"){const data=new FormData(form);try{const result=await request("/api/internal/accreditation/assessments","POST",{assignmentId,indicatorId:row.id,period,readinessStatus:String(data.get("readinessStatus")),actualValue:"",manualScore:data.get("manualScore")===""?undefined:Number(data.get("manualScore")),scoreSource:String(data.get("scoreSource")||"MODULE"),manualOverrideReason:String(data.get("manualOverrideReason")||""),calculationNote:String(data.get("calculationNote")||""),analysis:String(data.get("analysis")||""),evaluationNote:String(data.get("evaluationNote")||""),followupPlan:String(data.get("followupPlan")||""),ledNote:String(data.get("ledNote")||""),publicationDecision:String(data.get("publicationDecision")||"INTERNAL_ONLY"),workflowStatus,values:[],sourceSubjectType:String(data.get("sourceSubjectType")||""),sourceSubjectId:Number(data.get("sourceSubjectId"))||undefined,referenceTitle:String(data.get("referenceTitle")||""),sourceNote:String(data.get("sourceNote")||""),includeInPublic:data.get("includeInPublic")==="on"});await onDone(`Indikator ${row.code} tersimpan: ${result.status}.`);}catch(error){await onDone(error instanceof Error?error.message:"Gagal menyimpan");}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();await saveForm(event.currentTarget,"SUBMITTED");}
  async function action(name:string){try{const result=await request("/api/internal/accreditation/assessments","PATCH",{assessmentId:assessment.id,action:name});await onDone(`Indikator ${row.code}: ${result.status}.`);}catch(error){await onDone(error instanceof Error?error.message:"Operasi gagal");}}
  return <article className="indicator-card"><header><div><span>{row.criterionCode}</span><strong>{row.code}</strong></div><div><h3>{row.name}</h3><p>{row.description}</p><p><b>{row.mandate?`Mandat: ${row.mandate.responsibilityScope==="PRODI"?"Kaprodi pada Prodi ini":"Admin Jurusan/UPPS"} · Validator: Kajur`:"Belum dipetakan oleh Admin Jurusan"}</b></p></div><div className="indicator-state"><b>{assessment.readinessStatus??"NOT_ASSESSED"}</b><small>{assessment.workflowStatus??"DRAFT"}</small></div></header><form onSubmit={submit}>
    <section className="indicator-step"><div className="step-label"><b>1</b><span>Sumber modul</span></div><div className="module-source-panel">{(row.moduleSources??[]).map((module:Row)=><article key={module.moduleId}><div><b>{module.moduleName}</b><small>{module.moduleCode}</small></div>{module.snapshot?<><span>Kelengkapan <b>{module.snapshot.sourceCompleteness}%</b></span><span>Skor sumber <b>{module.snapshot.sourceScore} / 4</b></span><span>{module.snapshot.sourceCount} fakta terukur</span></>:<strong>Snapshot periode ini belum dibuat</strong>}</article>)}{!(row.moduleSources??[]).length&&<p>Admin Jurusan belum memetakan indikator ini ke modul sumber.</p>}<label><span>Status kesiapan berdasarkan evaluasi</span><select name="readinessStatus" defaultValue={assessment.readinessStatus??"NOT_ASSESSED"}><option>NOT_ASSESSED</option><option>IN_PROGRESS</option><option>COMPLETE</option><option>GAP</option></select></label></div></section>
    <section className="indicator-step"><div className="step-label"><b>2</b><span>Skor modul dan pertimbangan</span></div><div><div className="calculation-panel"><div><small>Skor hasil modul</small><strong>{assessment.moduleCalculatedScore??row.moduleSources?.[0]?.snapshot?.sourceScore??"Belum dihitung"}</strong></div><div><small>Sumber skor akhir</small><strong>{assessment.scoreSource??"MODULE"}</strong></div><div><small>Skor akhir</small><strong>{assessment.calculatedScore??"—"}</strong></div><div><small>Skor berbobot</small><strong>{assessment.weightedScore??"—"}</strong></div></div><div className="score-choice"><label><span>Gunakan skor</span><select name="scoreSource" defaultValue={assessment.scoreSource??"MODULE"}><option value="MODULE">Hasil perhitungan modul</option><option value="MANUAL_OVERRIDE">Override manual setelah ditelaah</option></select></label><label><span>Skor override 0–4</span><input name="manualScore" type="number" min="0" max="4" step="0.01" defaultValue={assessment.scoreSource==="MANUAL_OVERRIDE"?assessment.calculatedScore:""}/></label><label><span>Alasan override manual</span><textarea name="manualOverrideReason" defaultValue={assessment.manualOverrideReason??""} placeholder="Wajib bila skor manual dipilih; jelaskan pertimbangan terhadap hasil modul"/></label></div><label><span>Catatan/penjelasan perhitungan</span><textarea name="calculationNote" defaultValue={assessment.calculationNote??""}/></label>{row.previousAssessment&&<div className="period-comparison"><b>Perbandingan dengan {row.previousPeriod?.replace("-"," ")}</b><span>Skor modul: {row.previousAssessment.moduleCalculatedScore??"—"} → {assessment.moduleCalculatedScore??"—"}</span><span>Skor akhir: {row.previousAssessment.calculatedScore??"—"} → {assessment.calculatedScore??"—"}</span><span>Status: {row.previousAssessment.readinessStatus} → {assessment.readinessStatus??"NOT_ASSESSED"}</span></div>}</div></section>
    {assessment.id&&<><section className="indicator-step"><div className="step-label"><b>3–5</b><span>Analisis, evaluasi, tindak lanjut, LED</span></div><div className="assessment-grid text"><label><span>Analisis hasil *</span><textarea name="analysis" defaultValue={assessment.analysis??""} placeholder="Apa arti hasil ini terhadap indikator?"/></label><label><span>Evaluasi dan gap *</span><textarea name="evaluationNote" defaultValue={assessment.evaluationNote??""} placeholder="Apa yang belum tercapai dan penyebabnya?"/></label><label><span>Rencana tindak lanjut *</span><textarea name="followupPlan" defaultValue={assessment.followupPlan??""} placeholder="Tindakan, penanggung jawab, dan target perbaikan"/></label><label><span>Catatan LED *</span><textarea name="ledNote" defaultValue={assessment.ledNote??""} placeholder="Narasi yang perlu dimasukkan ke LED"/></label></div></section>
    <section className="indicator-step"><div className="step-label"><b>6</b><span>Evidence</span></div><div className="source-row"><label><span>Tipe sumber</span><input name="sourceSubjectType" defaultValue={source.sourceSubjectType??""} placeholder="KPI / VMTS / KURIKULUM / ..."/></label><label><span>ID data</span><input name="sourceSubjectId" type="number" defaultValue={source.sourceSubjectId??""}/></label><label><span>Judul evidence</span><input name="referenceTitle" defaultValue={source.referenceTitle??""}/></label><label><span>Catatan evidence</span><input name="sourceNote" defaultValue={source.note??""}/></label></div></section>
    <section className="indicator-step publication-step"><div className="step-label"><b>7</b><span>Keputusan</span></div><label><span>Keputusan publikasi</span><select name="publicationDecision" defaultValue={assessment.publicationDecision??"INTERNAL_ONLY"}><option value="INTERNAL_ONLY">Internal / LED saja</option><option value="PUBLIC_CANDIDATE">Ajukan sebagai kandidat publik</option></select></label><label className="check"><input type="checkbox" name="includeInPublic" defaultChecked={source.includeInPublic??false}/><span>Evidence ini boleh tampil publik</span></label></section></>}
    <footer>{canAssess&&row.canFill&&assessment.workflowStatus!=="APPROVED"&&assessment.workflowStatus!=="PUBLISHED"&&<><button type="button" onClick={event=>void saveForm(event.currentTarget.form!,"DRAFT")}>{assessment.id?"Simpan evaluasi":"Simpan input & hitung"}</button>{assessment.id&&<button type="submit">Ajukan ke Kajur</button>}</>}{canApprove&&row.canValidate&&assessment.id&&assessment.workflowStatus==="SUBMITTED"&&<><button type="button" onClick={()=>void action("APPROVE")}>Validasi</button><button className="secondary" type="button" onClick={()=>void action("RETURN")}>Kembalikan</button></>}{canPublish&&row.canValidate&&assessment.id&&assessment.workflowStatus==="APPROVED"&&assessment.publicationDecision==="PUBLIC_CANDIDATE"&&<button className="publish" type="button" onClick={()=>void action("PUBLISH")}>Publikasikan</button>}{!assessment.id&&row.canFill&&<span>Setelah input disimpan dan dihitung, formulir evaluasi akan dibuka.</span>}</footer>
  </form></article>;
}
