import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { curricula } from "@/src/db/schema-phase5";
import { getSession } from "@/src/lib/auth";
import { can } from "@/src/lib/rbac";
import { audit } from "@/src/lib/audit";
import { canAccessProgram } from "@/src/services/academic-scope";
const patch=z.object({title:z.string().min(3).max(500).optional(),academicYearStart:z.number().int().nullable().optional(),academicYearEnd:z.number().int().nullable().optional(),totalCredits:z.number().nonnegative().nullable().optional(),description:z.string().nullable().optional(),lifecycleStatus:z.enum(["DRAFT","SUBMITTED","ARCHIVED"]).optional()});
async function idOf(params:Promise<{id:string}>){const{id}=await params;const n=Number(id);return Number.isInteger(n)&&n>0?n:null;}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(s,"curriculum.manage")||can(s,"data.update")))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patch.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(curricula).where(eq(curricula.id,id)).limit(1);if(!before)return NextResponse.json({error:"Not found"},{status:404});if(!(await canAccessProgram(s,before.studyProgramId)))return NextResponse.json({error:"Scope Program Studi tidak sesuai."},{status:403});if(!["DRAFT","SUBMITTED"].includes(before.lifecycleStatus))return NextResponse.json({error:"Kurikulum efektif/published tidak diedit in-place; buat versi baru."},{status:409});const values:any={...p.data};if("totalCredits" in values)values.totalCredits=values.totalCredits==null?null:String(values.totalCredits);await db.update(curricula).set(values).where(eq(curricula.id,id));await audit({actorId:s.userId,action:"UPDATE_CURRICULUM",subjectType:"CURRICULUM",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(s,"curriculum.manage")||can(s,"data.update")))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(curricula).where(eq(curricula.id,id)).limit(1);if(!before)return NextResponse.json({error:"Not found"},{status:404});if(!(await canAccessProgram(s,before.studyProgramId)))return NextResponse.json({error:"Scope Program Studi tidak sesuai."},{status:403});if(!["DRAFT","SUBMITTED"].includes(before.lifecycleStatus))return NextResponse.json({error:"Kurikulum efektif/published tidak dapat dihapus langsung."},{status:409});await db.update(curricula).set({lifecycleStatus:"ARCHIVED"}).where(eq(curricula.id,id));await audit({actorId:s.userId,action:"ARCHIVE_CURRICULUM",subjectType:"CURRICULUM",subjectId:id,before,after:{lifecycleStatus:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
