import {and,eq,inArray} from "drizzle-orm";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireDb} from "@/src/db";
import {organizations,studyPrograms} from "@/src/db/schema";
import {accreditationAssessments,accreditationCriteria,accreditationIndicators,studyProgramAccreditationFrameworks} from "@/src/db/schema-accreditation";
import {accreditationRtmItems,accreditationRtmSessions,evaluationPeriods} from "@/src/db/schema-evaluation-modules";
import {audit} from "@/src/lib/audit";
import {getSession} from "@/src/lib/auth";
import {hasRole,scopeAllows} from "@/src/lib/rbac";

const periodPattern=/^\d{4}\/\d{4}-(GANJIL|GENAP)$/;
const sessionInput=z.object({organizationId:z.number().int().positive(),period:z.string().regex(periodPattern),title:z.string().min(3).max(255),meetingDate:z.string().optional(),summary:z.string().optional(),strengths:z.string().optional(),gaps:z.string().optional(),conclusion:z.string().optional(),signedDocumentKey:z.string().max(1000).optional()});
const itemInput=z.object({sessionId:z.number().int().positive(),assessmentId:z.number().int().positive(),discussionNote:z.string().optional(),finding:z.string().optional(),rootCause:z.string().optional(),recommendation:z.string().optional(),actionPlan:z.string().optional(),ownerName:z.string().max(255).optional(),dueDate:z.string().optional(),followupStatus:z.enum(["OPEN","IN_PROGRESS","CLOSED"]).default("OPEN"),publicationDecision:z.enum(["INTERNAL_ONLY","PUBLIC_SUMMARY","PUBLIC_SCORE","PUBLIC_EVIDENCE"]).default("INTERNAL_ONLY")});
const actionInput=z.object({sessionId:z.number().int().positive(),action:z.enum(["SUBMIT","APPROVE","REOPEN"])});

function manager(session:NonNullable<Awaited<ReturnType<typeof getSession>>>){return hasRole(session,"ADMIN_DATA")||hasRole(session,"KAJUR")||hasRole(session,"ADMIN_SYSTEM");}
function kajur(session:NonNullable<Awaited<ReturnType<typeof getSession>>>){return hasRole(session,"KAJUR")||hasRole(session,"ADMIN_SYSTEM");}
function previousPeriod(period:string){const match=period.match(/^(\d{4})\/(\d{4})-(GANJIL|GENAP)$/);if(!match)return null;const start=Number(match[1]);return match[3]==="GENAP"?`${match[1]}/${match[2]}-GANJIL`:`${start-1}/${start}-GENAP`;}

export async function GET(req:Request){
 const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});
 const url=new URL(req.url),organizationId=Number(url.searchParams.get("organizationId")),period=url.searchParams.get("period")??"";
 if(!organizationId||!periodPattern.test(period))return NextResponse.json({error:"Organisasi dan periode wajib dipilih."},{status:400});
 if(!scopeAllows(session,organizationId,null))return NextResponse.json({error:"Scope Jurusan tidak sesuai."},{status:403});
 const db=requireDb(),[organization]=await db.select().from(organizations).where(eq(organizations.id,organizationId)).limit(1);if(!organization)return NextResponse.json({error:"Jurusan tidak ditemukan."},{status:404});
 const[rtm]=await db.select().from(accreditationRtmSessions).where(and(eq(accreditationRtmSessions.organizationId,organizationId),eq(accreditationRtmSessions.period,period))).limit(1);
 const programs=await db.select({id:studyPrograms.id,name:studyPrograms.name,code:studyPrograms.code}).from(studyPrograms).where(eq(studyPrograms.organizationId,organizationId)),programIds=programs.map(row=>row.id);
 const assignments=programIds.length?await db.select({id:studyProgramAccreditationFrameworks.id,studyProgramId:studyProgramAccreditationFrameworks.studyProgramId}).from(studyProgramAccreditationFrameworks).where(and(inArray(studyProgramAccreditationFrameworks.studyProgramId,programIds),eq(studyProgramAccreditationFrameworks.assignmentStatus,"ACTIVE"))):[],assignmentIds=assignments.map(row=>row.id);
 const assessments=assignmentIds.length?await db.select({id:accreditationAssessments.id,assignmentId:accreditationAssessments.assignmentId,indicatorId:accreditationAssessments.indicatorId,readinessStatus:accreditationAssessments.readinessStatus,moduleCalculatedScore:accreditationAssessments.moduleCalculatedScore,calculatedScore:accreditationAssessments.calculatedScore,scoreSource:accreditationAssessments.scoreSource,analysis:accreditationAssessments.analysis,evaluationNote:accreditationAssessments.evaluationNote,followupPlan:accreditationAssessments.followupPlan,ledNote:accreditationAssessments.ledNote,publicationDecision:accreditationAssessments.publicationDecision,workflowStatus:accreditationAssessments.workflowStatus}).from(accreditationAssessments).where(and(inArray(accreditationAssessments.assignmentId,assignmentIds),eq(accreditationAssessments.period,period))):[];
 const prior=previousPeriod(period),priorAssessments=prior&&assignmentIds.length?await db.select({assignmentId:accreditationAssessments.assignmentId,indicatorId:accreditationAssessments.indicatorId,calculatedScore:accreditationAssessments.calculatedScore,readinessStatus:accreditationAssessments.readinessStatus}).from(accreditationAssessments).where(and(inArray(accreditationAssessments.assignmentId,assignmentIds),eq(accreditationAssessments.period,prior))):[];
 const indicatorIds=[...new Set(assessments.map(row=>row.indicatorId))],indicators=indicatorIds.length?await db.select({id:accreditationIndicators.id,code:accreditationIndicators.code,name:accreditationIndicators.name,criterionCode:accreditationCriteria.code,criterionName:accreditationCriteria.name}).from(accreditationIndicators).innerJoin(accreditationCriteria,eq(accreditationCriteria.id,accreditationIndicators.criterionId)).where(inArray(accreditationIndicators.id,indicatorIds)):[];
 const items=rtm?await db.select().from(accreditationRtmItems).where(eq(accreditationRtmItems.sessionId,rtm.id)):[];
 const rows=assessments.map(assessment=>{const assignment=assignments.find(row=>row.id===assessment.assignmentId),program=programs.find(row=>row.id===assignment?.studyProgramId),indicator=indicators.find(row=>row.id===assessment.indicatorId),previous=priorAssessments.find(row=>row.assignmentId===assessment.assignmentId&&row.indicatorId===assessment.indicatorId),item=items.find(row=>row.assessmentId===assessment.id);return {...assessment,program,indicator,previousPeriod:prior,previous,item:item??null};});
 return NextResponse.json({organization,period,previousPeriod:prior,session:rtm??null,items:rows,summary:{assessments:rows.length,submitted:rows.filter(row=>row.workflowStatus==="SUBMITTED").length,approved:rows.filter(row=>["APPROVED","PUBLISHED"].includes(row.workflowStatus)).length,discussed:rows.filter(row=>row.item).length,openFollowups:rows.filter(row=>row.item&&row.item.followupStatus!=="CLOSED").length}});
}

export async function POST(req:Request){
 const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(!manager(session))return NextResponse.json({error:"Hanya Admin Jurusan atau Kajur yang dapat menyiapkan RTM."},{status:403});
 const parsed=sessionInput.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});const input=parsed.data;if(!scopeAllows(session,input.organizationId,null))return NextResponse.json({error:"Scope Jurusan tidak sesuai."},{status:403});
 const db=requireDb(),[period]=await db.select().from(evaluationPeriods).where(and(eq(evaluationPeriods.organizationId,input.organizationId),eq(evaluationPeriods.label,input.period))).limit(1);if(!period)return NextResponse.json({error:"Periode belum dibuat oleh Admin Jurusan."},{status:409});
 const meetingDate=input.meetingDate?new Date(`${input.meetingDate}T00:00:00`):null,values={...input,meetingDate,signedDocumentKey:input.signedDocumentKey||null,createdBy:session.userId};await db.insert(accreditationRtmSessions).values(values).onDuplicateKeyUpdate({set:{title:input.title,meetingDate,summary:input.summary,strengths:input.strengths,gaps:input.gaps,conclusion:input.conclusion,signedDocumentKey:input.signedDocumentKey||null,updatedAt:new Date()}});
 const[rtm]=await db.select().from(accreditationRtmSessions).where(and(eq(accreditationRtmSessions.organizationId,input.organizationId),eq(accreditationRtmSessions.period,input.period))).limit(1);await audit({actorId:session.userId,action:"SAVE_RTM_SESSION",subjectType:"ACCREDITATION_RTM",subjectId:rtm.id,after:input});return NextResponse.json(rtm,{status:201});
}

export async function PUT(req:Request){
 const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(!manager(session))return NextResponse.json({error:"Forbidden"},{status:403});const parsed=itemInput.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});const input=parsed.data,db=requireDb();
 const[rtm]=await db.select().from(accreditationRtmSessions).where(eq(accreditationRtmSessions.id,input.sessionId)).limit(1);if(!rtm||!scopeAllows(session,rtm.organizationId,null))return NextResponse.json({error:"RTM tidak ditemukan dalam scope Jurusan."},{status:404});if(rtm.status==="APPROVED")return NextResponse.json({error:"RTM sudah disahkan Kajur dan harus dibuka kembali sebelum diedit."},{status:409});
 const[assessment]=await db.select({id:accreditationAssessments.id,organizationId:studyPrograms.organizationId}).from(accreditationAssessments).innerJoin(studyProgramAccreditationFrameworks,eq(studyProgramAccreditationFrameworks.id,accreditationAssessments.assignmentId)).innerJoin(studyPrograms,eq(studyPrograms.id,studyProgramAccreditationFrameworks.studyProgramId)).where(and(eq(accreditationAssessments.id,input.assessmentId),eq(accreditationAssessments.period,rtm.period))).limit(1);if(!assessment||assessment.organizationId!==rtm.organizationId)return NextResponse.json({error:"Asesmen bukan bagian dari Jurusan dan periode RTM."},{status:409});
 const dueDate=input.dueDate?new Date(`${input.dueDate}T00:00:00`):null;await db.insert(accreditationRtmItems).values({...input,dueDate,updatedBy:session.userId}).onDuplicateKeyUpdate({set:{discussionNote:input.discussionNote,finding:input.finding,rootCause:input.rootCause,recommendation:input.recommendation,actionPlan:input.actionPlan,ownerName:input.ownerName,dueDate,followupStatus:input.followupStatus,publicationDecision:input.publicationDecision,updatedBy:session.userId,updatedAt:new Date()}});
 await db.update(accreditationAssessments).set({publicationDecision:input.publicationDecision==="INTERNAL_ONLY"?"INTERNAL_ONLY":"PUBLIC_CANDIDATE",updatedAt:new Date()}).where(eq(accreditationAssessments.id,input.assessmentId));await audit({actorId:session.userId,action:"SAVE_RTM_ITEM",subjectType:"ACCREDITATION_ASSESSMENT",subjectId:input.assessmentId,after:input});return NextResponse.json({saved:true});
}

export async function PATCH(req:Request){
 const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const parsed=actionInput.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});const db=requireDb(),[rtm]=await db.select().from(accreditationRtmSessions).where(eq(accreditationRtmSessions.id,parsed.data.sessionId)).limit(1);if(!rtm||!scopeAllows(session,rtm.organizationId,null))return NextResponse.json({error:"RTM tidak ditemukan."},{status:404});
 if(parsed.data.action==="SUBMIT"){if(!manager(session))return NextResponse.json({error:"Forbidden"},{status:403});const items=await db.select().from(accreditationRtmItems).where(eq(accreditationRtmItems.sessionId,rtm.id));if(!items.length)return NextResponse.json({error:"Belum ada indikator yang dibahas dalam RTM."},{status:409});await db.update(accreditationRtmSessions).set({status:"SUBMITTED",updatedAt:new Date()}).where(eq(accreditationRtmSessions.id,rtm.id));}
 if(parsed.data.action==="APPROVE"){if(!kajur(session))return NextResponse.json({error:"Hanya Kajur yang dapat mengesahkan RTM."},{status:403});const items=await db.select().from(accreditationRtmItems).where(eq(accreditationRtmItems.sessionId,rtm.id));if(!items.length||!rtm.summary?.trim()||!rtm.conclusion?.trim())return NextResponse.json({error:"Ringkasan, kesimpulan, dan pembahasan indikator wajib lengkap sebelum RTM disahkan."},{status:409});const assessmentIds=items.map(row=>row.assessmentId);await db.transaction(async tx=>{await tx.update(accreditationRtmSessions).set({status:"APPROVED",approvedBy:session.userId,updatedAt:new Date()}).where(eq(accreditationRtmSessions.id,rtm.id));await tx.update(accreditationAssessments).set({workflowStatus:"APPROVED",approvedBy:session.userId,updatedAt:new Date()}).where(and(inArray(accreditationAssessments.id,assessmentIds),eq(accreditationAssessments.workflowStatus,"SUBMITTED")));await tx.update(evaluationPeriods).set({status:"CLOSED",updatedAt:new Date()}).where(and(eq(evaluationPeriods.organizationId,rtm.organizationId),eq(evaluationPeriods.label,rtm.period)));});}
 if(parsed.data.action==="REOPEN"){if(!kajur(session))return NextResponse.json({error:"Hanya Kajur yang dapat membuka kembali RTM."},{status:403});await db.update(accreditationRtmSessions).set({status:"DRAFT",approvedBy:null,updatedAt:new Date()}).where(eq(accreditationRtmSessions.id,rtm.id));await db.update(evaluationPeriods).set({status:"OPEN",updatedAt:new Date()}).where(and(eq(evaluationPeriods.organizationId,rtm.organizationId),eq(evaluationPeriods.label,rtm.period)));}
 await audit({actorId:session.userId,action:`${parsed.data.action}_RTM_SESSION`,subjectType:"ACCREDITATION_RTM",subjectId:rtm.id});return NextResponse.json({id:rtm.id,status:parsed.data.action==="APPROVE"?"APPROVED":parsed.data.action==="SUBMIT"?"SUBMITTED":"DRAFT"});
}
