import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { laboratoryEquipment } from "@/src/db/schema-phase6";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { canReadResourceScope,canWriteResourceScope,getEquipmentScope,getLaboratoryScope } from "@/src/services/resource-scope";
const createInput=z.object({laboratoryId:z.number().int().positive(),assetCode:z.string().max(100).optional(),name:z.string().min(2).max(255),category:z.string().max(100).optional(),quantity:z.number().int().positive().default(1),unit:z.string().max(50).optional(),conditionStatus:z.enum(["GOOD","FAIR","POOR","OUT_OF_SERVICE"]).default("GOOD"),acquisitionYear:z.number().int().min(1900).max(2200).optional(),notes:z.string().optional()});
const patchInput=z.object({assetCode:z.string().max(100).nullable().optional(),name:z.string().min(2).max(255).optional(),category:z.string().max(100).nullable().optional(),quantity:z.number().int().positive().optional(),unit:z.string().max(50).nullable().optional(),conditionStatus:z.enum(["GOOD","FAIR","POOR","OUT_OF_SERVICE"]).optional(),acquisitionYear:z.number().int().min(1900).max(2200).nullable().optional(),notes:z.string().nullable().optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional()});
function queryId(req:Request,key="id"){const n=Number(new URL(req.url).searchParams.get(key));return Number.isInteger(n)&&n>0?n:null;}
export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const laboratoryId=queryId(req,"laboratoryId");const db=requireDb();const rows=laboratoryId?await db.select().from(laboratoryEquipment).where(eq(laboratoryEquipment.laboratoryId,laboratoryId)):await db.select().from(laboratoryEquipment);const allowed=[];for(const row of rows){const lab=await getLaboratoryScope(row.laboratoryId);if(lab&&canReadResourceScope(s,lab.organizationId,null))allowed.push(row);}return NextResponse.json(allowed);}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const p=createInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const lab=await getLaboratoryScope(p.data.laboratoryId);if(!lab)return NextResponse.json({error:"Laboratorium tidak ditemukan."},{status:404});if(!canWriteResourceScope(s,lab.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const x=await db.insert(laboratoryEquipment).values({...p.data,status:"ACTIVE"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_LAB_EQUIPMENT",subjectType:"LAB_EQUIPMENT",subjectId:id,after:p.data});return NextResponse.json({id,status:"ACTIVE"},{status:201});}
export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=queryId(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patchInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const scope=await getEquipmentScope(id);if(!scope||!canWriteResourceScope(s,scope.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const[before]=await db.select().from(laboratoryEquipment).where(eq(laboratoryEquipment.id,id)).limit(1);await db.update(laboratoryEquipment).set({...p.data,updatedAt:new Date()}).where(eq(laboratoryEquipment.id,id));await audit({actorId:s.userId,action:"UPDATE_LAB_EQUIPMENT",subjectType:"LAB_EQUIPMENT",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=queryId(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const scope=await getEquipmentScope(id);if(!scope||!canWriteResourceScope(s,scope.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const[before]=await db.select().from(laboratoryEquipment).where(eq(laboratoryEquipment.id,id)).limit(1);await db.update(laboratoryEquipment).set({status:"ARCHIVED",updatedAt:new Date()}).where(eq(laboratoryEquipment.id,id));await audit({actorId:s.userId,action:"ARCHIVE_LAB_EQUIPMENT",subjectType:"LAB_EQUIPMENT",subjectId:id,before,after:{status:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
