import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { cpmk,curriculumCourses } from "@/src/db/schema-phase5";
import { getSession } from "@/src/lib/auth";
import { can } from "@/src/lib/rbac";
import { audit } from "@/src/lib/audit";
import { canAccessCurriculum } from "@/src/services/academic-scope";
const patch=z.object({semester:z.number().int().min(1).max(14).optional(),creditsOverride:z.number().positive().nullable().optional()});
async function idOf(params:Promise<{id:string}>){const{id}=await params;const n=Number(id);return Number.isInteger(n)&&n>0?n:null;}
async function getRow(id:number){const db=requireDb();const[row]=await db.select().from(curriculumCourses).where(eq(curriculumCourses.id,id)).limit(1);return row??null;}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(s,"curriculum.manage")||can(s,"data.update")))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patch.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const before=await getRow(id);if(!before)return NextResponse.json({error:"Not found"},{status:404});if(!(await canAccessCurriculum(s,before.curriculumId)))return NextResponse.json({error:"Scope kurikulum tidak sesuai."},{status:403});const values:any={...p.data};if("creditsOverride" in values)values.creditsOverride=values.creditsOverride==null?null:String(values.creditsOverride);const db=requireDb();await db.update(curriculumCourses).set(values).where(eq(curriculumCourses.id,id));await audit({actorId:s.userId,action:"UPDATE_CURRICULUM_COURSE",subjectType:"CURRICULUM_COURSE",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(s,"curriculum.manage")||can(s,"data.update")))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const before=await getRow(id);if(!before)return NextResponse.json({error:"Not found"},{status:404});if(!(await canAccessCurriculum(s,before.curriculumId)))return NextResponse.json({error:"Scope kurikulum tidak sesuai."},{status:403});const db=requireDb();const used=await db.select({id:cpmk.id}).from(cpmk).where(eq(cpmk.curriculumCourseId,id)).limit(1);if(used[0])return NextResponse.json({error:"Mapping mata kuliah sudah memiliki CPMK; arsipkan CPMK terlebih dahulu dan pertahankan histori mapping."},{status:409});await db.delete(curriculumCourses).where(eq(curriculumCourses.id,id));await audit({actorId:s.userId,action:"DELETE_UNUSED_CURRICULUM_COURSE",subjectType:"CURRICULUM_COURSE",subjectId:id,before});return NextResponse.json({id,status:"DELETED"});}
