import {and,eq} from "drizzle-orm";
import {NextResponse} from "next/server";
import {z} from "zod";
import {requireDb} from "@/src/db";
import {studyPrograms} from "@/src/db/schema";
import {evaluationPeriods} from "@/src/db/schema-evaluation-modules";
import {personnel,personnelSemesterAssignments} from "@/src/db/schema-phase6";
import {audit} from "@/src/lib/audit";
import {getSession} from "@/src/lib/auth";
import {scopeAllows} from "@/src/lib/rbac";
import {canWriteResourceScope} from "@/src/services/resource-scope";

const periodPattern=/^\d{4}\/\d{4}-(GANJIL|GENAP)$/;
const createInput=z.object({personnelId:z.number().int().positive(),studyProgramId:z.number().int().positive(),period:z.string().regex(periodPattern),courseCode:z.string().min(1).max(80),courseName:z.string().min(2).max(500),credits:z.number().min(0).max(40).optional(),expertiseAligned:z.boolean().default(false),bokAligned:z.boolean().default(false),tridharmaActive:z.boolean().default(false)});
const deleteInput=z.object({id:z.number().int().positive()});
const qualifies=(row:{lecturerStatus:string|null;expertiseAligned:boolean;bokAligned:boolean;tridharmaActive:boolean})=>["HOMEBASE","PERMANENT_POLBENG"].includes(row.lecturerStatus??"")&&row.expertiseAligned&&row.bokAligned&&row.tridharmaActive;

export async function GET(req:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const url=new URL(req.url),period=url.searchParams.get("period")??"",studyProgramId=Number(url.searchParams.get("studyProgramId"));if(!periodPattern.test(period)||!studyProgramId)return NextResponse.json({error:"Periode dan Program Studi wajib dipilih."},{status:400});const db=requireDb(),[program]=await db.select().from(studyPrograms).where(eq(studyPrograms.id,studyProgramId)).limit(1);if(!program||!scopeAllows(session,program.organizationId,program.id))return NextResponse.json({error:"Scope Program Studi tidak sesuai."},{status:403});const rows=await db.select({id:personnelSemesterAssignments.id,personnelId:personnelSemesterAssignments.personnelId,personnelName:personnel.name,lecturerStatus:personnel.lecturerStatus,studyProgramId:personnelSemesterAssignments.studyProgramId,period:personnelSemesterAssignments.period,courseCode:personnelSemesterAssignments.courseCode,courseName:personnelSemesterAssignments.courseName,credits:personnelSemesterAssignments.credits,expertiseAligned:personnelSemesterAssignments.expertiseAligned,bokAligned:personnelSemesterAssignments.bokAligned,tridharmaActive:personnelSemesterAssignments.tridharmaActive}).from(personnelSemesterAssignments).innerJoin(personnel,eq(personnel.id,personnelSemesterAssignments.personnelId)).where(and(eq(personnelSemesterAssignments.studyProgramId,studyProgramId),eq(personnelSemesterAssignments.period,period)));return NextResponse.json(rows.map(row=>({...row,isDtps:qualifies(row)})));}

export async function POST(req:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const parsed=createInput.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});const db=requireDb(),[program]=await db.select().from(studyPrograms).where(eq(studyPrograms.id,parsed.data.studyProgramId)).limit(1);if(!program||!canWriteResourceScope(session,program.organizationId,program.id,false))return NextResponse.json({error:"Scope Program Studi tidak sesuai."},{status:403});const[period]=await db.select().from(evaluationPeriods).where(and(eq(evaluationPeriods.organizationId,program.organizationId),eq(evaluationPeriods.label,parsed.data.period),eq(evaluationPeriods.status,"OPEN"))).limit(1);if(!period)return NextResponse.json({error:"Gunakan periode aktif yang sudah dibuat Admin Jurusan."},{status:409});const[lecturer]=await db.select().from(personnel).where(and(eq(personnel.id,parsed.data.personnelId),eq(personnel.organizationId,program.organizationId),eq(personnel.personnelType,"LECTURER"),eq(personnel.status,"ACTIVE"))).limit(1);if(!lecturer)return NextResponse.json({error:"Dosen aktif tidak ditemukan pada Jurusan ini."},{status:409});const result=await db.insert(personnelSemesterAssignments).values({...parsed.data,credits:parsed.data.credits==null?null:String(parsed.data.credits)}).onDuplicateKeyUpdate({set:{courseName:parsed.data.courseName,credits:parsed.data.credits==null?null:String(parsed.data.credits),expertiseAligned:parsed.data.expertiseAligned,bokAligned:parsed.data.bokAligned,tridharmaActive:parsed.data.tridharmaActive,updatedAt:new Date()}});const isDtps=qualifies({...parsed.data,lecturerStatus:lecturer.lecturerStatus});await audit({actorId:session.userId,action:"SAVE_PERSONNEL_SEMESTER_ASSIGNMENT",subjectType:"PERSONNEL_ASSIGNMENT",subjectId:Number(result[0].insertId)||null,after:{...parsed.data,isDtps}});return NextResponse.json({saved:true,isDtps});}

export async function DELETE(req:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});const parsed=deleteInput.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:"ID penugasan tidak valid."},{status:400});const db=requireDb(),[before]=await db.select().from(personnelSemesterAssignments).where(eq(personnelSemesterAssignments.id,parsed.data.id)).limit(1);if(!before)return NextResponse.json({error:"Penugasan tidak ditemukan."},{status:404});const[program]=await db.select().from(studyPrograms).where(eq(studyPrograms.id,before.studyProgramId)).limit(1);if(!program||!canWriteResourceScope(session,program.organizationId,program.id,false))return NextResponse.json({error:"Forbidden"},{status:403});await db.delete(personnelSemesterAssignments).where(eq(personnelSemesterAssignments.id,before.id));await audit({actorId:session.userId,action:"DELETE_PERSONNEL_SEMESTER_ASSIGNMENT",subjectType:"PERSONNEL_ASSIGNMENT",subjectId:before.id,before,after:null});return NextResponse.json({id:before.id,deleted:true});}
