import Link from "next/link";
import {redirect} from "next/navigation";
import {getSession} from "@/src/lib/auth";
export const dynamic="force-dynamic";
const roleNames:Record<string,string>={ADMIN_SYSTEM:"Super Admin Sistem",ADMIN_DATA:"Admin Jurusan",KAPRODI:"Ketua Program Studi",GKM:"Gugus Kendali Mutu",SEKJUR:"Sekretaris Jurusan",KAJUR:"Ketua Jurusan",VIEWER_INTERNAL:"Pengguna Internal"};
const steps=[
 {no:"01",title:"Isi data sesuai scope",text:"Isi VMTS manual, kurikulum, KPI, SDM, laboratorium, penelitian, PkM, mahasiswa, lulusan, kerja sama, dan berita.",links:[["VMTS & Renstra","/internal/vmts"],["Akademik & OBE","/internal/academic"],["Sumber daya & tridharma","/internal/resources"],["Berita Jurusan","/internal/admin"]]},
 {no:"02",title:"Ukur dan analisis",text:"Isi target dan realisasi KPI. Sistem menghitung capaian; evaluator mencatat analisis, temuan, rekomendasi, dan tindak lanjut.",links:[["Pengukuran & evaluasi","/internal/workflow"]]},
 {no:"03",title:"Pilih template dan nilai indikator",text:"Kaprodi memilih template LAM untuk Prodinya. Setelah itu hubungkan data sebagai bukti, isi perhitungan, analisis, evaluasi, dan catatan LED.",links:[["Pilih template Prodi","/internal/accreditation"],["Cockpit akreditasi","/internal/accreditation/cockpit"]]},
 {no:"04",title:"Persetujuan dan publikasi",text:"Kaprodi menyetujui data dalam scope Prodi. Kajur/UPPS menjalankan publikasi pada lingkup UPPS.",links:[["Antrian evaluasi","/internal/workflow"],["Portal publik","/"],["Informasi akreditasi","/akreditasi"]]}
];
function ScopeCard({role,scope}:{role:string;scope:{organizationId:number;studyProgramId?:number|null}|undefined}){return <div className="workspace-identity"><span>Peran aktif</span><strong>{role}</strong><span>Cakupan kerja</span><strong>{scope?.studyProgramId?`Prodi #${scope.studyProgramId} pada Organisasi #${scope.organizationId}`:`Seluruh Prodi pada Organisasi #${scope?.organizationId??"—"}`}</strong></div>}
export default async function InternalHome(){
 const session=await getSession();if(!session)redirect("/internal/login");
 const scope=session.scopes?.[0],displayRoles=session.roles.map(role=>roleNames[role]??role).join(", "),isSuperAdmin=session.roles.includes("ADMIN_SYSTEM"),isKaprodi=session.roles.includes("KAPRODI"),isKajur=session.roles.includes("KAJUR");
 if(isSuperAdmin)return <main className="workspace-home"><section className="workspace-welcome superadmin"><div><span className="workspace-kicker">Pusat kendali sistem</span><h1>Super Admin</h1><p>Satu instalasi melayani satu Jurusan. Super Admin mengatur aplikasi lokal dan memonitor instalasi Jurusan lain melalui jalur federasi.</p></div><ScopeCard role={displayRoles} scope={scope}/></section><section className="role-boundary"><div><span>APLIKASI JURUSAN</span><h2>Mandiri per Jurusan</h2><p>Setiap Jurusan memiliki database, pengguna, workflow, approval, dan portal publik sendiri.</p></div><div><span>MONITORING PUSAT</span><h2>Ringkasan federatif</h2><p>Pusat membaca status dan ringkasan terautentikasi tanpa menyalin evidence, LED, password, atau data personal.</p></div></section><section className="workspace-flow"><article><div className="workspace-number">01</div><div><h2>Konfigurasi aplikasi Jurusan</h2><p>Atur identitas Jurusan lokal, Prodi, akun, role, dan cakupan kerja.</p><div className="workspace-actions"><Link href="/internal/admin">Administrasi sistem <span>→</span></Link></div></div></article><article><div className="workspace-number">02</div><div><h2>Registry akreditasi lokal</h2><p>Kelola framework, indikator, variabel, rumus, rubrik, evidence, dan assignment Prodi Jurusan ini.</p><div className="workspace-actions"><Link href="/internal/accreditation">Registry framework <span>→</span></Link></div></div></article><article><div className="workspace-number">03</div><div><h2>Monitoring aplikasi Jurusan</h2><p>Tambah, sinkronkan, pantau, atau lepaskan instalasi Jurusan lain dari dashboard pusat.</p><div className="workspace-actions"><Link href="/internal/federation">Buka monitoring pusat <span>→</span></Link></div></div></article><article><div className="workspace-number">04</div><div><h2>Kebijakan publikasi lokal</h2><p>Tentukan status, persetujuan, dan field aplikasi Jurusan ini yang boleh tampil publik.</p><div className="workspace-actions"><Link href="/internal/publication-policies">Atur kebijakan <span>→</span></Link></div></div></article></section></main>;
 const heading=isKaprodi?"Ruang kerja Kaprodi":isKajur?"Ruang kerja Kajur / UPPS":"Ruang kerja Admin Jurusan";
 const duty=isKaprodi?"Isi dan setujui data hanya dalam scope Program Studi Anda.":isKajur?"Kelola persetujuan dan publikasi pada lingkup UPPS/Jurusan.":"Isi dan ajukan data dalam lingkup Jurusan; Anda tidak mengatur sistem.";
 return <main className="workspace-home"><section className="workspace-welcome"><div><span className="workspace-kicker">{heading}</span><h1>Selamat datang, {session.name}</h1><p>{duty}</p></div><ScopeCard role={displayRoles} scope={scope}/></section><section className="workspace-flow">{steps.map(step=><article key={step.no}><div className="workspace-number">{step.no}</div><div><h2>{step.title}</h2><p>{step.text}</p><div className="workspace-actions">{step.links.map(([label,href])=><Link key={href} href={href}>{label}<span>→</span></Link>)}</div></div></article>)}</section><aside className="workspace-note"><strong>{isKaprodi?"Kaprodi: input dan persetujuan hanya pada Prodi sendiri.":isKajur?"Kajur/UPPS: persetujuan dan publikasi pada lingkup UPPS.":"Admin Jurusan: input dan pengajuan data, bukan konfigurasi sistem."}</strong><p>Super Admin mengatur struktur dan hak akses. Setiap tindakan tetap dibatasi oleh role, scope organisasi/Prodi, lifecycle, dan audit trail.</p></aside></main>;
}
