import Link from "next/link";
import {redirect} from "next/navigation";
import {getSession} from "@/src/lib/auth";
import {isMasterApplication} from "@/src/lib/application-mode";
export const dynamic="force-dynamic";
const roleNames:Record<string,string>={ADMIN_SYSTEM:"Super Admin Sistem",ADMIN_DATA:"Admin Jurusan",KAPRODI:"Ketua Program Studi",GKM:"Gugus Kendali Mutu",SEKJUR:"Sekretaris Jurusan",KAJUR:"Ketua Jurusan",VIEWER_INTERNAL:"Pengguna Internal"};
function ScopeCard({role,scope}:{role:string;scope:{organizationId:number;studyProgramId?:number|null}|undefined}){return <div className="workspace-identity"><span>Peran aktif</span><strong>{role}</strong><span>Cakupan kerja</span><strong>{scope?.studyProgramId?`Prodi #${scope.studyProgramId} pada Organisasi #${scope.organizationId}`:`Seluruh Prodi pada Organisasi #${scope?.organizationId??"—"}`}</strong></div>}
export default async function InternalHome(){
 const session=await getSession();if(!session)redirect("/internal/login");
 if(isMasterApplication())redirect("/master");
 const scope=session.scopes?.[0],displayRoles=session.roles.map(role=>roleNames[role]??role).join(", "),isSuperAdmin=session.roles.includes("ADMIN_SYSTEM"),isKaprodi=session.roles.includes("KAPRODI"),isKajur=session.roles.includes("KAJUR");
 if(isSuperAdmin)return <main className="workspace-home"><section className="workspace-welcome superadmin"><div><span className="workspace-kicker">Administrator teknis Tenant</span><h1>Administrasi Aplikasi Jurusan</h1><p>Akun ini hanya mengelola instalasi Jurusan ini. Provisioning Tenant, registry global LAM, dan federasi berada pada aplikasi Master.</p></div><ScopeCard role={displayRoles} scope={scope}/></section><section className="workspace-flow"><article><div className="workspace-number">01</div><div><h2>Identitas dan akun lokal</h2><p>Kelola identitas Jurusan, Prodi, pengguna, role, dan scope database Tenant ini.</p><div className="workspace-actions"><Link href="/internal/admin">Administrasi Tenant <span>→</span></Link></div></div></article><article><div className="workspace-number">02</div><div><h2>Operasional evaluasi</h2><p>Periksa pengisian, pengukuran, evaluasi, approval, dan publikasi Tenant.</p><div className="workspace-actions"><Link href="/internal/workflow">Workflow Tenant <span>→</span></Link></div></div></article></section></main>;
 const heading=isKaprodi?"Ruang kerja Kaprodi":isKajur?"Ruang kerja Kajur / UPPS":"Ruang kerja Admin Jurusan";
 const duty=isKaprodi?"Isi dan evaluasi indikator yang dimandatkan hanya dalam scope Program Studi Anda.":isKajur?"Validasi hasil pengisian dan tentukan publikasi pada lingkup UPPS/Jurusan.":"Buat akun penerima mandat dan petakan indikator kepada Prodi atau Jurusan/UPPS.";
 const steps=session.roles.includes("ADMIN_DATA")?[
  {no:"01",title:"Buat periode pengisian",text:"Tetapkan tahun akademik dan semester. Periode menjadi batas seluruh isian, perhitungan, mandat, RTM, dan LED.",links:[["Kelola periode & modul","/internal/modules"]]},
  {no:"02",title:"Atur akun, sumber modul, dan mandat",text:"Buat akun Kaprodi/Kajur, terapkan rekomendasi awal, lalu koreksi pembagian indikator kepada Prodi atau Jurusan/UPPS.",links:[["Konfigurasi pekerjaan","/internal/mandates"]]},
  {no:"03",title:"Lengkapi data modul",text:"Setiap pemegang mandat mengisi data operasional sesuai scope. Sistem menghitung kelengkapan dan nilai awal dari database.",links:[["Modul evaluasi semester","/internal/modules"],["Pantau indikator","/internal/accreditation/cockpit"]]},
  {no:"04",title:"Ajukan hasil untuk evaluasi",text:"Indikator lengkap dapat dianalisis, dibandingkan dengan semester sebelumnya, lalu diajukan kepada Kajur.",links:[["Cockpit akreditasi","/internal/accreditation/cockpit"]]},
  {no:"05",title:"RTM, LED, dan publikasi",text:"Bahas temuan dan tindak lanjut bersama Kajur, cetak resume LED, lalu publikasikan hanya hasil yang disahkan.",links:[["RTM Jurusan & LED","/internal/rtm"]]},
 ]:isKaprodi?[
  {no:"01",title:"Lengkapi data Program Studi",text:"Isi kurikulum, OBE, mahasiswa, lulusan, lalu perbarui snapshot modul evaluasi semester.",links:[["Akademik & OBE","/internal/academic"],["Modul evaluasi semester","/internal/modules"]]},
  {no:"02",title:"Isi indikator mandat Prodi",text:"Cockpit hanya mengizinkan Anda menyimpan indikator yang ditugaskan kepada Prodi sendiri.",links:[["Cockpit akreditasi","/internal/accreditation/cockpit"]]},
  {no:"03",title:"Ajukan kepada Kajur",text:"Setelah sumber modul lengkap, periksa hasil hitung, beri analisis, lalu ajukan untuk dibahas dalam RTM Jurusan.",links:[["Cockpit akreditasi","/internal/accreditation/cockpit"],["RTM Jurusan","/internal/rtm"]]},
 ]:[
  {no:"01",title:"Periksa pengajuan",text:"Tinjau hasil pengisian indikator dari Prodi dan Jurusan/UPPS.",links:[["Cockpit akreditasi","/internal/accreditation/cockpit"]]},
  {no:"02",title:"Pimpin RTM Jurusan",text:"Bandingkan semester, sahkan temuan dan tindak lanjut, serta tetapkan isi resume LED.",links:[["RTM Jurusan & LED","/internal/rtm"]]},
  {no:"03",title:"Sahkan dan pilih publikasi",text:"Tutup periode setelah RTM lengkap dan publikasikan hanya ringkasan, capaian, atau bukti yang dipilih.",links:[["Cockpit akreditasi","/internal/accreditation/cockpit"],["Portal publik","/"]]},
 ];
 return <main className="workspace-home"><section className="workspace-welcome"><div><span className="workspace-kicker">{heading}</span><h1>Selamat datang, {session.name}</h1><p>{duty}</p></div><ScopeCard role={displayRoles} scope={scope}/></section><section className="workspace-flow">{steps.map(step=><article key={step.no}><div className="workspace-number">{step.no}</div><div><h2>{step.title}</h2><p>{step.text}</p><div className="workspace-actions">{step.links.map(([label,href])=><Link key={href} href={href}>{label}<span>→</span></Link>)}</div></div></article>)}</section><aside className="workspace-note"><strong>{isKaprodi?"Kaprodi: input dan evaluasi hanya pada indikator yang dimandatkan ke Prodi sendiri.":isKajur?"Kajur/UPPS: validator hasil pengisian dan pelaksana publikasi pada lingkup UPPS.":"Admin Jurusan: pembuat akun, pembagi mandat indikator, dan pengisi bagian UPPS/Jurusan."}</strong><p>Master menetapkan instrumen LAM. Tenant membagi pekerjaan tanpa mengubah isi template global.</p></aside></main>;
}
