import { and,eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { cpl,cpmk,cpmkCplMappings,curriculumCourses } from "@/src/db/schema-phase5";
import { getSession } from "@/src/lib/auth";
import { can } from "@/src/lib/rbac";
import { audit } from "@/src/lib/audit";
import { canAccessCurriculum } from "@/src/services/academic-scope";
const input=z.object({cpmkId:z.number().int().positive(),cplId:z.number().int().positive(),weight:z.number().nonnegative().optional()});
async function context(cpmkId:number,cplId:number){const db=requireDb();const [cpmkRow]=await db.select({curriculumCourseId:cpmk.curriculumCourseId}).from(cpmk).where(eq(cpmk.id,cpmkId)).limit(1);if(!cpmkRow)return null;const [cc]=await db.select({curriculumId:curriculumCourses.curriculumId}).from(curriculumCourses).where(eq(curriculumCourses.id,cpmkRow.curriculumCourseId)).limit(1);const [cplRow]=await db.select({curriculumId:cpl.curriculumId}).from(cpl).where(eq(cpl.id,cplId)).limit(1);if(!cc||!cplRow||cc.curriculumId!==cplRow.curriculumId)return null;return cc.curriculumId;}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(s,"curriculum.manage")||can(s,"data.create")))return NextResponse.json({error:"Forbidden"},{status:403});const p=input.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const curriculumId=await context(p.data.cpmkId,p.data.cplId);if(!curriculumId)return NextResponse.json({error:"CPMK dan CPL harus berasal dari kurikulum yang sama."},{status:409});if(!(await canAccessCurriculum(s,curriculumId)))return NextResponse.json({error:"Scope kurikulum tidak sesuai."},{status:403});const db=requireDb();await db.insert(cpmkCplMappings).values({cpmkId:p.data.cpmkId,cplId:p.data.cplId,weight:p.data.weight?.toString()}).onDuplicateKeyUpdate({set:{weight:p.data.weight?.toString()}});await audit({actorId:s.userId,action:"MAP_CPMK_CPL",subjectType:"CURRICULUM",subjectId:curriculumId,after:p.data});return NextResponse.json({status:"SAVED"});}
export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(s,"curriculum.manage")||can(s,"data.update")))return NextResponse.json({error:"Forbidden"},{status:403});const p=input.pick({cpmkId:true,cplId:true}).safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const curriculumId=await context(p.data.cpmkId,p.data.cplId);if(!curriculumId||!(await canAccessCurriculum(s,curriculumId)))return NextResponse.json({error:"Scope kurikulum tidak sesuai."},{status:403});const db=requireDb();await db.delete(cpmkCplMappings).where(and(eq(cpmkCplMappings.cpmkId,p.data.cpmkId),eq(cpmkCplMappings.cplId,p.data.cplId)));await audit({actorId:s.userId,action:"UNMAP_CPMK_CPL",subjectType:"CURRICULUM",subjectId:curriculumId,before:p.data});return NextResponse.json({status:"DELETED"});}
