import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { evaluations,findings,recommendations } from "@/src/db/schema";
import { curriculumReviewCycles } from "@/src/db/schema-phase5";
import { getSession } from "@/src/lib/auth";
import { can } from "@/src/lib/rbac";
import { audit } from "@/src/lib/audit";
import { canAccessCurriculum } from "@/src/services/academic-scope";
const input=z.object({curriculumId:z.number().int().positive(),period:z.string().min(1).max(50),reviewType:z.string().max(80).default("PERIODIC"),stakeholders:z.array(z.string()).optional(),standardReference:z.string().optional(),analysis:z.string().min(5),rootCause:z.string().optional(),publicSummary:z.string().optional(),finding:z.string().optional(),severity:z.string().optional(),recommendation:z.string().optional(),priority:z.string().optional()});
export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const curriculumId=Number(new URL(req.url).searchParams.get("curriculumId"));if(!curriculumId||!(await canAccessCurriculum(s,curriculumId)))return NextResponse.json({error:"Scope kurikulum tidak sesuai."},{status:403});const db=requireDb();return NextResponse.json(await db.select().from(curriculumReviewCycles).where(eq(curriculumReviewCycles.curriculumId,curriculumId)));}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"evaluation.create"))return NextResponse.json({error:"Forbidden: evaluasi kurikulum harus dilakukan role evaluator."},{status:403});const p=input.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});if(!(await canAccessCurriculum(s,p.data.curriculumId)))return NextResponse.json({error:"Scope kurikulum tidak sesuai."},{status:403});const db=requireDb();const {curriculumId,reviewType,stakeholders,finding,severity,recommendation,priority,...evalData}=p.data;const er=await db.insert(evaluations).values({subjectType:"CURRICULUM",subjectId:curriculumId,period:evalData.period,standardReference:evalData.standardReference,analysis:evalData.analysis,rootCause:evalData.rootCause,publicSummary:evalData.publicSummary,evaluatorId:s.userId,status:"SUBMITTED",evaluatedAt:new Date()});const evaluationId=Number(er[0].insertId);if(finding)await db.insert(findings).values({evaluationId,description:finding,severity});if(recommendation)await db.insert(recommendations).values({evaluationId,recommendationText:recommendation,priority,status:"OPEN"});const rr=await db.insert(curriculumReviewCycles).values({curriculumId,period:evalData.period,reviewType,stakeholders:stakeholders??[],evaluationId,status:"SUBMITTED"});const reviewId=Number(rr[0].insertId);await audit({actorId:s.userId,action:"EVALUATE_CURRICULUM",subjectType:"CURRICULUM",subjectId:curriculumId,after:{reviewId,evaluationId,period:evalData.period,stakeholders}});return NextResponse.json({reviewId,evaluationId,status:"SUBMITTED"},{status:201});}
