import { and,eq,inArray } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { accreditationFrameworks,accreditationIndicators,accreditationIndicatorVariables,accreditationScoringRubrics } from "@/src/db/schema-accreditation";
import { audit } from "@/src/lib/audit";
import { getSession } from "@/src/lib/auth";
import { can } from "@/src/lib/rbac";

const variable=z.object({entity:z.literal("VARIABLE"),indicatorId:z.number().int().positive(),code:z.string().min(1).max(100),label:z.string().min(2).max(500),valueType:z.enum(["NUMBER","TEXT","BOOLEAN"]).default("NUMBER"),unit:z.string().max(80).optional(),required:z.boolean().default(true),sourceSubjectType:z.string().max(120).optional(),sourceField:z.string().max(255).optional(),defaultValue:z.string().max(255).optional(),sequence:z.number().int().positive().default(1)});
const rubric=z.object({entity:z.literal("RUBRIC"),indicatorId:z.number().int().positive(),score:z.number(),label:z.string().min(1).max(255),description:z.string().optional(),conditionRule:z.unknown().optional(),sequence:z.number().int().positive().default(1)});
const createInput=z.discriminatedUnion("entity",[variable,rubric]);
const variablePatch=z.object({entity:z.literal("VARIABLE"),id:z.number().int().positive(),label:z.string().min(2).optional(),valueType:z.enum(["NUMBER","TEXT","BOOLEAN"]).optional(),unit:z.string().nullable().optional(),required:z.boolean().optional(),sourceSubjectType:z.string().nullable().optional(),sourceField:z.string().nullable().optional(),defaultValue:z.string().nullable().optional(),sequence:z.number().int().positive().optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional()});
const rubricPatch=z.object({entity:z.literal("RUBRIC"),id:z.number().int().positive(),score:z.number().optional(),label:z.string().min(1).optional(),description:z.string().nullable().optional(),conditionRule:z.unknown().optional(),sequence:z.number().int().positive().optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional()});
const patchInput=z.discriminatedUnion("entity",[variablePatch,rubricPatch]);

async function editableIndicator(indicatorId:number){const db=requireDb();const[row]=await db.select({indicator:accreditationIndicators,framework:accreditationFrameworks}).from(accreditationIndicators).innerJoin(accreditationFrameworks,eq(accreditationIndicators.frameworkId,accreditationFrameworks.id)).where(eq(accreditationIndicators.id,indicatorId)).limit(1);return row?.framework.lifecycleStatus==="DRAFT"?row.indicator:null;}
async function guard(){const session=await getSession();if(!session)return {response:NextResponse.json({error:"Unauthorized"},{status:401})};if(!can(session,"accreditation.framework.manage"))return {response:NextResponse.json({error:"Forbidden"},{status:403})};return {session};}

export async function GET(req:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(session,"accreditation.read"))return NextResponse.json({error:"Forbidden"},{status:403});const frameworkId=Number(new URL(req.url).searchParams.get("frameworkId"));if(!frameworkId)return NextResponse.json({error:"frameworkId wajib."},{status:400});const db=requireDb();const indicators=await db.select({id:accreditationIndicators.id}).from(accreditationIndicators).where(eq(accreditationIndicators.frameworkId,frameworkId));const ids=indicators.map(row=>row.id);if(!ids.length)return NextResponse.json({variables:[],rubrics:[]});const[variables,rubrics]=await Promise.all([db.select().from(accreditationIndicatorVariables).where(inArray(accreditationIndicatorVariables.indicatorId,ids)),db.select().from(accreditationScoringRubrics).where(inArray(accreditationScoringRubrics.indicatorId,ids))]);return NextResponse.json({variables,rubrics});}

export async function POST(req:Request){const auth=await guard();if(auth.response)return auth.response;const parsed=createInput.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});if(!(await editableIndicator(parsed.data.indicatorId)))return NextResponse.json({error:"Rumus hanya dapat diubah saat framework DRAFT."},{status:409});const db=requireDb();if(parsed.data.entity==="VARIABLE"){const{entity,...data}=parsed.data;const code=data.code.toUpperCase().replace(/\s+/g,"_");const[exists]=await db.select({id:accreditationIndicatorVariables.id}).from(accreditationIndicatorVariables).where(and(eq(accreditationIndicatorVariables.indicatorId,data.indicatorId),eq(accreditationIndicatorVariables.code,code))).limit(1);if(exists)return NextResponse.json({error:"Kode variabel sudah ada."},{status:409});const result=await db.insert(accreditationIndicatorVariables).values({...data,code,status:"ACTIVE"});const id=Number(result[0].insertId);await audit({actorId:auth.session!.userId,action:"CREATE_ACCREDITATION_VARIABLE",subjectType:"ACCREDITATION_VARIABLE",subjectId:id,after:{...data,code}});return NextResponse.json({id,code},{status:201});}const{entity,score,...data}=parsed.data;const result=await db.insert(accreditationScoringRubrics).values({...data,score:String(score),status:"ACTIVE"});const id=Number(result[0].insertId);await audit({actorId:auth.session!.userId,action:"CREATE_ACCREDITATION_RUBRIC",subjectType:"ACCREDITATION_RUBRIC",subjectId:id,after:parsed.data});return NextResponse.json({id},{status:201});}

export async function PATCH(req:Request){const auth=await guard();if(auth.response)return auth.response;const parsed=patchInput.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});const db=requireDb();if(parsed.data.entity==="VARIABLE"){const{entity,id,...changes}=parsed.data;const[before]=await db.select().from(accreditationIndicatorVariables).where(eq(accreditationIndicatorVariables.id,id)).limit(1);if(!before)return NextResponse.json({error:"Variabel tidak ditemukan."},{status:404});if(!(await editableIndicator(before.indicatorId)))return NextResponse.json({error:"Rumus framework aktif tidak boleh diubah."},{status:409});await db.update(accreditationIndicatorVariables).set({...changes,updatedAt:new Date()}).where(eq(accreditationIndicatorVariables.id,id));await audit({actorId:auth.session!.userId,action:"UPDATE_ACCREDITATION_VARIABLE",subjectType:"ACCREDITATION_VARIABLE",subjectId:id,before,after:changes});return NextResponse.json({id,...changes});}const{entity,id,score,...changes}=parsed.data;const[before]=await db.select().from(accreditationScoringRubrics).where(eq(accreditationScoringRubrics.id,id)).limit(1);if(!before)return NextResponse.json({error:"Rubrik tidak ditemukan."},{status:404});if(!(await editableIndicator(before.indicatorId)))return NextResponse.json({error:"Rubrik framework aktif tidak boleh diubah."},{status:409});const values={...changes,...(score===undefined?{}:{score:String(score)}),updatedAt:new Date()};await db.update(accreditationScoringRubrics).set(values).where(eq(accreditationScoringRubrics.id,id));await audit({actorId:auth.session!.userId,action:"UPDATE_ACCREDITATION_RUBRIC",subjectType:"ACCREDITATION_RUBRIC",subjectId:id,before,after:values});return NextResponse.json({id,...values});}
