"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
type Row=Record<string,any>;
const entryPaths:Record<string,string>={VMTS_PROFILE:"/internal/vmts",LEARNING:"/internal/academic",STUDENTS_GRADUATES:"/internal/resources",HUMAN_RESOURCES:"/internal/resources",FACILITIES_K3L:"/internal/resources",RESEARCH_PKM:"/internal/resources",COOPERATION:"/internal/resources",GOVERNANCE_QUALITY:"/internal/workflow"};
async function request(url:string,method="GET",body?:unknown){const response=await fetch(url,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Operasi gagal.");return data;}

export default function ModuleWorkspace({assignments,canManagePeriods}:{assignments:Row[];canManagePeriods:boolean}){
 const[assignmentId,setAssignmentId]=useState(assignments[0]?.assignmentId??0),[period,setPeriod]=useState(""),[periods,setPeriods]=useState<Row[]>([]),[modules,setModules]=useState<Row[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[showOther,setShowOther]=useState(false);const selected=assignments.find(row=>row.assignmentId===assignmentId);
 async function loadPeriods(){const rows=await request("/api/internal/evaluation-periods");setPeriods(rows);if(!period&&rows[0])setPeriod(rows[0].label);}
 async function load(){if(!assignmentId||!period)return setModules([]);try{const data=await request(`/api/internal/evaluation-modules?assignmentId=${assignmentId}&period=${encodeURIComponent(period)}`);setModules(data.modules);}catch(error){setMessage(error instanceof Error?error.message:"Modul gagal dimuat.");}}
 useEffect(()=>{void loadPeriods()},[]);useEffect(()=>{void load()},[assignmentId,period]);
 async function createPeriod(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=event.currentTarget,data=new FormData(form);try{const result=await request("/api/internal/evaluation-periods","POST",{organizationId:selected.organizationId,academicYear:data.get("academicYear"),semester:data.get("semester")});form.reset();setPeriod(result.label);setMessage(`Langkah 1 selesai. Periode ${result.label.replace("-"," ")} dibuat. Lanjutkan dengan menyiapkan modul dan mandat.`);await loadPeriods();}catch(error){setMessage(error instanceof Error?error.message:"Periode gagal dibuat.");}}
 async function deletePeriod(item:Row){if(!window.confirm(`Hapus permanen periode ${item.label.replace("-"," ")} beserta ringkasan modul, asesmen, dan RTM-nya?`))return;try{await request("/api/internal/evaluation-periods","DELETE",{id:item.id});setPeriod("");setModules([]);setMessage("Periode dan data evaluasi turunannya telah dihapus permanen.");await loadPeriods();}catch(error){setMessage(error instanceof Error?error.message:"Periode gagal dihapus.");}}
 async function setup(){if(!period||!selected)return;setBusy(true);try{const result=await request("/api/internal/evaluation-setup","POST",{organizationId:selected.organizationId,period});setMessage(`Langkah 2 selesai. ${result.mappingsCreated} sumber modul dan ${result.mandatesCreated} mandat baru disiapkan. Pemetaan sebelumnya tetap dipertahankan.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Modul dan mandat gagal disiapkan.");}finally{setBusy(false)}}
 async function processModule(moduleId:number,action:"INSPECT"|"CALCULATE"|"REUSE_PREVIOUS"){if(!period)return;setBusy(true);try{const data=await request("/api/internal/evaluation-modules","POST",{assignmentId,period,moduleId,action}),result=data.results?.[0];setMessage(action==="REUSE_PREVIOUS"?(result?.message??"Data periode sebelumnya selesai diperiksa."):action==="INSPECT"?(result?.sourceCompleteness>=100?`${result.moduleName} lengkap 100%. Sekarang tekan Hitung hasil modul.`:`${result?.moduleName??"Modul"} baru ${result?.sourceCompleteness??0}% lengkap. Buka ruang input dan lengkapi data yang masih kosong.`):`${result.moduleName} berhasil dihitung dengan skor ${result.sourceScore} dari 4.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Pemrosesan modul gagal.");}finally{setBusy(false)}}
 const configured=modules.some(row=>row.mappedIndicators>0),assignedModules=useMemo(()=>modules.filter(row=>row.canInput&&row.assignedIndicators>0),[modules]),otherModules=useMemo(()=>modules.filter(row=>!row.canInput||row.assignedIndicators===0),[modules]),allChecked=assignedModules.length>0&&assignedModules.every(row=>row.snapshot),allComplete=allChecked&&assignedModules.every(row=>Number(row.snapshot?.sourceCompleteness??0)>=100),allCalculated=allComplete&&assignedModules.every(row=>row.snapshot?.sourceScore!==null&&row.snapshot?.sourceScore!==undefined);
 const steps=[{n:"01",label:"Buat periode",done:Boolean(period)},{n:"02",label:"Siapkan modul & mandat",done:configured},{n:"03",label:"Isi modul sesuai mandat",done:allChecked},{n:"04",label:"Periksa kelengkapan",done:allComplete},{n:"05",label:"Hitung",done:allCalculated},{n:"06",label:"Ajukan evaluasi",done:false}];
 return <main className="module-shell"><header><span>ALUR EVALUASI SEMESTER</span><h1>Pengisian modul sesuai mandat</h1><p>Kerjakan berurutan. Sistem hanya membuka modul yang menjadi tanggung jawab akun pada periode terpilih.</p></header>
 <nav className="module-stepper">{steps.map(step=><div className={step.done?"done":""} key={step.n}><b>{step.done?"✓":step.n}</b><span>{step.label}</span></div>)}</nav>
 {canManagePeriods&&<section className="period-manager"><div><span className="flow-label">LANGKAH 1</span><h2>Buat atau pilih periode pengisian</h2><p>Satu periode berlaku untuk mandat, data modul, perhitungan, evaluasi, RTM, dan LED.</p></div><form onSubmit={createPeriod}><label><span>Tahun akademik</span><input name="academicYear" required pattern="\d{4}/\d{4}" placeholder="2025/2026"/></label><label><span>Semester</span><select name="semester"><option value="GANJIL">Ganjil</option><option value="GENAP">Genap</option></select></label><button>Buat periode</button></form><div className="period-list">{periods.map(item=><div key={item.id}><button className={period===item.label?"active":""} onClick={()=>setPeriod(item.label)}>{item.label.replace("-"," ")} · {item.status}</button><button className="delete" onClick={()=>void deletePeriod(item)}>Hapus permanen</button></div>)}</div></section>}
 <section className="module-controls"><label><span>Program Studi yang diperiksa</span><select value={assignmentId} onChange={event=>setAssignmentId(Number(event.target.value))}>{assignments.map(row=><option key={row.assignmentId} value={row.assignmentId}>{row.organizationName} · {row.programName}</option>)}</select></label><label><span>Periode aktif</span><select value={period} onChange={event=>setPeriod(event.target.value)}><option value="">Pilih periode</option>{periods.map(item=><option key={item.id} value={item.label}>{item.label.replace("-"," ")} · {item.status}</option>)}</select></label></section>
 {message&&<div className="module-message">{message}<button onClick={()=>setMessage("")}>Tutup</button></div>}{!period&&<p className="module-empty">Langkah 1 belum selesai. Admin Jurusan harus membuat periode pengisian.</p>}
 {period&&<section className={`setup-stage ${configured?"complete":""}`}><div><span className="flow-label">LANGKAH 2</span><h2>Siapkan modul dan mandat</h2><p>{configured?"Indikator sudah terhubung. Admin Jurusan masih dapat mengedit scope dan modul sumber.":"Terapkan rekomendasi awal agar indikator dibagi ke Prodi atau UPPS dan dihubungkan ke salah satu modul default."}</p></div><div>{canManagePeriods&&<button disabled={busy} onClick={()=>void setup()}>{configured?"Periksa / lengkapi konfigurasi":"Siapkan otomatis"}</button>}<Link href="/internal/mandates">Edit pembagian secara rinci</Link></div></section>}
 {period&&configured&&<section className="assigned-stage"><header><div><span className="flow-label">LANGKAH 3–5</span><h2>Modul yang menjadi mandat akun ini</h2><p>Isi data, periksa kelengkapan, lalu hitung hasil modul. Ketiga tindakan tidak lagi digabung.</p></div><strong>{assignedModules.length} modul tugas</strong></header>{!assignedModules.length&&<p className="module-empty">Tidak ada modul yang dimandatkan kepada akun ini. Masuk menggunakan akun penerima mandat yang sesuai atau periksa pembagian oleh Admin Jurusan.</p>}<div className="module-list assigned">{assignedModules.map(module=><ModuleCard key={module.id} module={module} period={period} studyProgramId={selected?.studyProgramId} busy={busy} processModule={processModule}/>)}</div></section>}
 {period&&configured&&otherModules.length>0&&<section className="other-stage"><button onClick={()=>setShowOther(value=>!value)}>{showOther?"Sembunyikan":"Lihat"} {otherModules.length} modul milik peran lain</button>{showOther&&<div className="module-list muted">{otherModules.map(module=><ModuleCard key={module.id} module={module} period={period} studyProgramId={selected?.studyProgramId} busy={busy} processModule={processModule}/>)}</div>}</section>}
 {assignedModules.length>0&&<section className={`evaluation-gate ${allCalculated?"ready":""}`}><div><span className="flow-label">LANGKAH 6</span><h2>{allCalculated?"Semua modul sudah dihitung—ajukan evaluasi":"Selesaikan modul secara berurutan"}</h2><p>{allCalculated?"Seluruh modul mandat lengkap dan telah dihitung. Beri analisis indikator, lalu ajukan kepada Kajur.":!allChecked?"Isi data dan tekan Periksa kelengkapan pada setiap modul.":!allComplete?"Masih ada data wajib yang belum lengkap.":"Kelengkapan sudah 100%. Tekan Hitung hasil modul pada setiap tugas."}</p></div>{allCalculated?<Link href="/internal/accreditation/cockpit">Buka evaluasi & ajukan →</Link>:<span>Belum dapat diajukan</span>}</section>}
 <aside className="database-note"><b>Data utama tersimpan di database Tenant.</b><p>Ringkasan periode dipertahankan agar hasil semester dapat dibandingkan. Dokumen LED bertanda tangan dicatat kemudian pada ruang RTM Jurusan.</p></aside><footer><Link href="/internal">← Ruang kerja</Link>{allComplete&&<Link href="/internal/accreditation/cockpit">Lanjut ke evaluasi →</Link>}</footer></main>;
}

function ModuleCard({module,period,studyProgramId,busy,processModule}:{module:Row;period:string;studyProgramId:number|undefined;busy:boolean;processModule:(id:number,action:"INSPECT"|"CALCULATE"|"REUSE_PREVIOUS")=>Promise<void>}){const summary=module.snapshot,data=summary?.snapshotData as Row|undefined,complete=Number(summary?.sourceCompleteness??0)>=100,calculated=complete&&summary?.sourceScore!==null&&summary?.sourceScore!==undefined,inputUrl=`${entryPaths[module.code]??"/internal"}?focus=${module.code}&period=${encodeURIComponent(period)}&studyProgramId=${studyProgramId??""}`;return <article className={calculated?"complete":""}><div><span>{module.scopeType}</span><h2>{module.name}</h2><p>{module.description}</p></div><ol className="card-flow"><li className={module.canInput?"active":""}><b>1</b><span>{module.canInput?"Isi data":"Bukan mandat akun"}</span></li><li className={summary?"active":""}><b>2</b><span>Periksa</span></li><li className={calculated?"active":""}><b>3</b><span>Hitung</span></li></ol><div className={`module-actions ${module.previousSnapshot?"four":"three"}`}>{module.canInput?<Link href={inputUrl}>Isi modul</Link>:<span className="not-assigned">Tidak dapat diisi akun ini</span>}{module.canInput&&module.previousSnapshot&&<button className="reuse-data" disabled={busy} onClick={()=>{if(window.confirm(`Gunakan data ${module.previousPeriod?.replace("-"," ")} sebagai data awal ${period.replace("-"," ")}? Data lama tetap tersimpan.`))void processModule(module.id,"REUSE_PREVIOUS")}}>Gunakan data lama</button>}<button disabled={busy||!module.canInput} onClick={()=>void processModule(module.id,"INSPECT")}>Periksa kelengkapan</button><button disabled={busy||!module.canInput||!complete} onClick={()=>void processModule(module.id,"CALCULATE")}>{calculated?"Hitung ulang":"Hitung hasil modul"}</button></div><dl><div><dt>Kelengkapan sesuai mandat</dt><dd>{summary?`${summary.sourceCompleteness}%`:"Belum diperiksa"}</dd></div><div><dt>Hasil hitung modul</dt><dd>{summary?.sourceScore??"—"} / 4</dd></div><div><dt>Indikator mandat/terhubung</dt><dd>{module.assignedIndicators??0} / {module.mappedIndicators}</dd></div></dl>{data?.facts&&<div className="module-facts">{Object.entries(data.facts).map(([key,value])=><span key={key}><small>{key.replaceAll(/([A-Z])/g," $1")}</small><b>{String(value??"—")}</b></span>)}</div>}</article>}
