import { hash } from "bcryptjs";
import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { users } from "@/src/db/schema";
import { getSession } from "@/src/lib/auth";
import { can } from "@/src/lib/rbac";
import { audit } from "@/src/lib/audit";

const patch=z.object({name:z.string().min(2).optional(),email:z.string().email().optional(),password:z.string().min(10).optional(),status:z.enum(["ACTIVE","INACTIVE","ARCHIVED"]).optional()});
async function idOf(params:Promise<{id:string}>){const {id}=await params;const n=Number(id);return Number.isInteger(n)&&n>0?n:null;}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"users.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patch.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const [before]=await db.select({id:users.id,name:users.name,email:users.email,status:users.status}).from(users).where(eq(users.id,id)).limit(1);if(!before)return NextResponse.json({error:"Not found"},{status:404});const values:any={...p.data};if(p.data.email)values.email=p.data.email.toLowerCase();if(p.data.password){values.passwordHash=await hash(p.data.password,12);delete values.password;}await db.update(users).set(values).where(eq(users.id,id));await audit({actorId:s.userId,action:"UPDATE_USER",subjectType:"USER",subjectId:id,before,after:{...values,passwordHash:values.passwordHash?"[UPDATED]":undefined}});return NextResponse.json({id,status:values.status??before.status});}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"users.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});if(id===s.userId)return NextResponse.json({error:"Admin tidak dapat menonaktifkan dirinya sendiri melalui endpoint ini."},{status:409});const db=requireDb();const [before]=await db.select({id:users.id,name:users.name,email:users.email,status:users.status}).from(users).where(eq(users.id,id)).limit(1);if(!before)return NextResponse.json({error:"Not found"},{status:404});await db.update(users).set({status:"ARCHIVED"}).where(eq(users.id,id));await audit({actorId:s.userId,action:"ARCHIVE_USER",subjectType:"USER",subjectId:id,before,after:{status:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
