"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
type Row=Record<string,any>;

async function request(url:string,method="GET",body?:unknown){const response=await fetch(url,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Operasi gagal.");return data;}

export default function MandateConsole(){
 const[programs,setPrograms]=useState<Row[]>([]),[users,setUsers]=useState<Row[]>([]),[mandates,setMandates]=useState<Row[]>([]),[role,setRole]=useState("KAPRODI"),[filter,setFilter]=useState(""),[message,setMessage]=useState("");
 async function load(){try{const[p,u,m]=await Promise.all([request("/api/internal/study-programs"),request("/api/internal/users"),request("/api/internal/accreditation/mandates")]);setPrograms(p);setUsers(u);setMandates(m);}catch(error){setMessage(error instanceof Error?error.message:"Data mandat tidak dapat dimuat.");}}
 useEffect(()=>{void load()},[]);
 const organizationId=programs[0]?.organizationId;
 function assignmentLabel(assignment:Row){const program=programs.find(row=>row.id===assignment.studyProgramId);return `${assignment.roleCode} · ${assignment.studyProgramId?(program?.name??`Prodi #${assignment.studyProgramId}`):"seluruh Jurusan"}`;}
 const visible=useMemo(()=>{const text=filter.toLowerCase();return mandates.filter(row=>!text||`${row.studyProgramName} ${row.indicatorCode} ${row.indicatorName} ${row.criterionName}`.toLowerCase().includes(text));},[filter,mandates]);
 async function createUser(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);try{await request("/api/internal/users","POST",{name:data.get("name"),email:data.get("email"),password:data.get("password"),roleCode:role,organizationId,studyProgramId:role==="KAPRODI"?Number(data.get("studyProgramId")):null});form.reset();setMessage(`Akun ${role==="KAPRODI"?"Kaprodi":"Kajur"} berhasil dibuat.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Akun gagal dibuat.");}}
 async function assign(row:Row,responsibilityScope:string){try{await request("/api/internal/accreditation/mandates","POST",{assignmentId:row.assignmentId,indicatorId:row.indicatorId,responsibilityScope});setMessage(`${row.indicatorCode} ditugaskan kepada ${responsibilityScope==="PRODI"?"Kaprodi":"Admin Jurusan/UPPS"}; validasi oleh Kajur.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Mandat gagal disimpan.");}}
 return <>
  {message&&<div className="mandate-message"><span>{message}</span><button onClick={()=>setMessage("")}>Tutup</button></div>}
  <section className="mandate-summary"><div><b>{programs.length}</b><span>Program Studi</span></div><div><b>{users.filter(u=>u.assignments?.some((a:Row)=>a.roleCode==="KAPRODI")).length}</b><span>Akun Kaprodi</span></div><div><b>{users.filter(u=>u.assignments?.some((a:Row)=>a.roleCode==="KAJUR")).length}</b><span>Akun Kajur</span></div><div><b>{mandates.filter(m=>m.responsibilityScope).length}/{mandates.length}</b><span>Indikator dipetakan</span></div></section>
  <div className="mandate-grid"><section className="mandate-card"><span className="eyebrow">LANGKAH 1</span><h2>Buat akun penerima mandat</h2><p>Kaprodi hanya bekerja pada Prodinya. Kajur bekerja pada scope Jurusan sebagai validator.</p><form onSubmit={createUser}><label><span>Jenis akun</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="KAPRODI">Ketua Program Studi</option><option value="KAJUR">Ketua Jurusan / validator</option></select></label>{role==="KAPRODI"&&<label><span>Program Studi</span><select name="studyProgramId" required><option value="">Pilih Prodi</option>{programs.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label>}<label><span>Nama lengkap</span><input name="name" required/></label><label><span>Email login</span><input name="email" type="email" required/></label><label><span>Password awal</span><input name="password" type="password" minLength={10} required/></label><button disabled={!organizationId}>Buat akun dan pasang scope</button></form><h3>Akun yang sudah ada</h3><div className="account-list">{users.filter(u=>u.assignments?.some((a:Row)=>["KAPRODI","KAJUR"].includes(a.roleCode))).map(user=><div key={user.id}><b>{user.name}</b><span>{user.email}</span><small>{user.assignments.map(assignmentLabel).join(", ")}</small></div>)}</div></section>
  <section className="mandate-card"><span className="eyebrow">LANGKAH 2</span><h2>Petakan indikator instrumen</h2><p>Pilih berdasarkan isi indikator: kurikulum dan pembelajaran biasanya Prodi; laboratorium, SDM bersama, tata kelola, dan sumber daya bersama biasanya Jurusan/UPPS. Keputusan tetap ditetapkan Admin Jurusan.</p><input className="mandate-search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Cari nama/kode indikator atau Prodi"/><div className="indicator-list">{visible.map(row=><article key={`${row.assignmentId}-${row.indicatorId}`}><div><small>{row.studyProgramName} · {row.criterionCode}</small><b>{row.indicatorCode} · {row.indicatorName}</b><span>{row.criterionName}</span></div><label><span>Penanggung jawab pengisian</span><select value={row.responsibilityScope??""} onChange={e=>void assign(row,e.target.value)}><option value="" disabled>Belum dipetakan</option><option value="PRODI">Prodi — Kaprodi</option><option value="UPPS">Jurusan/UPPS — Admin Jurusan</option></select><small>Validator: Kajur</small></label></article>)}</div></section></div>
  <footer className="mandate-footer"><Link href="/internal">← Dashboard Tenant</Link><Link href="/internal/accreditation/cockpit">Lanjut ke pengisian indikator →</Link></footer>
 </>;
}
