import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { permissions,rolePermissions,roles } from "@/src/db/schema";
import { roleSettings } from "@/src/db/schema-admin";
import { getSession } from "@/src/lib/auth";
import { can } from "@/src/lib/rbac";
import { audit } from "@/src/lib/audit";

const input=z.object({code:z.string().min(2).max(100),name:z.string().min(2).max(255),permissionCodes:z.array(z.string().min(2)).default([])});
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"roles.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const roleRows=await db.select({id:roles.id,code:roles.code,name:roles.name,status:roleSettings.status,isSystemRole:roleSettings.isSystemRole}).from(roles).leftJoin(roleSettings,eq(roleSettings.roleId,roles.id));const grants=await db.select({roleId:rolePermissions.roleId,permissionCode:permissions.code}).from(rolePermissions).innerJoin(permissions,eq(permissions.id,rolePermissions.permissionId));const permissionRows=await db.select().from(permissions);return NextResponse.json({roles:roleRows.map(r=>({...r,status:r.status??"ACTIVE",permissionCodes:grants.filter(g=>g.roleId===r.id).map(g=>g.permissionCode)})),permissions:permissionRows});}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"roles.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const p=input.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const code=p.data.code.toUpperCase().replace(/[^A-Z0-9_]+/g,"_");const [existing]=await db.select({id:roles.id}).from(roles).where(eq(roles.code,code)).limit(1);if(existing)return NextResponse.json({error:"Kode role sudah digunakan."},{status:409});const x=await db.insert(roles).values({code,name:p.data.name});const roleId=Number(x[0].insertId);await db.insert(roleSettings).values({roleId,status:"ACTIVE",isSystemRole:false});for(const permissionCode of p.data.permissionCodes){const [perm]=await db.select({id:permissions.id}).from(permissions).where(eq(permissions.code,permissionCode)).limit(1);if(perm){const [grant]=await db.select().from(rolePermissions).where(and(eq(rolePermissions.roleId,roleId),eq(rolePermissions.permissionId,perm.id))).limit(1);if(!grant)await db.insert(rolePermissions).values({roleId,permissionId:perm.id});}}await audit({actorId:s.userId,action:"CREATE_ROLE",subjectType:"ROLE",subjectId:roleId,after:{code,name:p.data.name,permissionCodes:p.data.permissionCodes}});return NextResponse.json({id:roleId,code},{status:201});}
