export const ROLE_NAMES:Record<string,string>={ADMIN_SYSTEM:"Admin Sistem",ADMIN_DATA:"Admin Jurusan",KAPRODI:"Kaprodi",GKM:"GKM",SEKJUR:"Sekjur",KAJUR:"Kajur",VIEWER_INTERNAL:"Viewer Internal"};
export const PERMISSIONS=["system.configure","users.manage","roles.manage","master.manage","audit.read","data.create","data.update","evidence.upload","publication.execute","news.manage","program.read","program.update","curriculum.manage","kpi.measure","followup.execute","quality.read","evidence.verify","evaluation.create","finding.create","recommendation.create","followup.verify","publication.recommend","data.verify","workflow.coordinate","publication.review","approval.final","evaluation.approve","publication.approve","report.approve","internal.read","resources.read","resources.manage","resources.contribute","accreditation.read","accreditation.framework.manage","accreditation.assign","accreditation.assess","accreditation.approve","accreditation.publish"] as const;
export const ROLE_GRANTS:Record<string,readonly string[]>={
  ADMIN_SYSTEM:["system.configure","users.manage","roles.manage","master.manage","audit.read","internal.read","program.read","resources.read","quality.read","accreditation.read","accreditation.framework.manage","accreditation.assign"],
  ADMIN_DATA:["data.create","data.update","evidence.upload","news.manage","program.read","program.update","curriculum.manage","kpi.measure","evaluation.create","finding.create","recommendation.create","followup.execute","internal.read","resources.read","resources.manage","resources.contribute","accreditation.read","accreditation.assess"],
  KAPRODI:["data.create","data.update","program.read","program.update","curriculum.manage","kpi.measure","evidence.upload","evaluation.create","finding.create","recommendation.create","followup.execute","approval.final","evaluation.approve","internal.read","resources.read","resources.contribute","accreditation.read","accreditation.assess","accreditation.approve"],
  GKM:["quality.read","evidence.verify","evaluation.create","finding.create","recommendation.create","followup.verify","publication.recommend","internal.read","resources.read","accreditation.read","accreditation.assess"],
  SEKJUR:["data.verify","workflow.coordinate","publication.review","followup.verify","internal.read","resources.read","resources.manage","accreditation.read"],
  KAJUR:["data.create","data.update","approval.final","evaluation.approve","publication.approve","publication.execute","report.approve","internal.read","resources.read","resources.manage","accreditation.read","accreditation.approve","accreditation.publish"],
  VIEWER_INTERNAL:["internal.read","resources.read","accreditation.read"],
};
