"use client";
import { FormEvent, useEffect, useState } from "react";

type Row = Record<string, any>;
type Section = "structure" | "users" | "roles" | "news";

export default function AdminConsole({ permissions }: { permissions: string[] }) {
  const has = (permission: string) => permissions.includes(permission);
  const [active, setActive] = useState<Section>(has("master.manage") ? "structure" : "news");
  const [orgs,setOrgs]=useState<Row[]>([]), [prodis,setProdis]=useState<Row[]>([]), [users,setUsers]=useState<Row[]>([]), [roles,setRoles]=useState<Row[]>([]), [permissionRows,setPermissionRows]=useState<Row[]>([]), [categories,setCategories]=useState<Row[]>([]), [articles,setArticles]=useState<Row[]>([]), [message,setMessage]=useState("");
  async function request(url:string,method="GET",body?:unknown){const response=await fetch(url,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Operasi gagal");return data;}
  async function load(){try{if(has("internal.read")||has("master.manage")||has("news.manage")||has("users.manage")){setOrgs(await request("/api/internal/organizations"));setProdis(await request("/api/internal/study-programs"));}if(has("users.manage"))setUsers(await request("/api/internal/users"));if(has("roles.manage")){const data=await request("/api/internal/roles");setRoles(data.roles??[]);setPermissionRows(data.permissions??[]);}if(has("news.manage")||has("approval.final")||has("publication.execute")){setArticles(await request("/api/internal/news/articles"));if(has("news.manage"))setCategories(await request("/api/internal/news/categories"));}}catch(error){setMessage(error instanceof Error?error.message:"Gagal memuat data");}}
  useEffect(()=>{void load();},[]);
  async function act(fn:()=>Promise<unknown>,form?:HTMLFormElement){try{await fn();form?.reset();setMessage("Berhasil. Perubahan langsung diterapkan.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Operasi gagal");}}
  const data=(event:FormEvent<HTMLFormElement>)=>new FormData(event.currentTarget);
  const remove=(label:string,fn:()=>Promise<unknown>)=>{if(confirm(`Hapus permanen ${label}? Tindakan ini tidak dapat dibatalkan.`))void act(fn);};

  return <div className="admin-workspace">
    {message&&<div className="admin-feedback" role="status"><span>{message}</span><button onClick={()=>setMessage("")}>Tutup</button></div>}
    <nav className="admin-tabs" aria-label="Bagian administrasi">
      {has("master.manage")&&<Tab no="01" label="Jurusan & Prodi" detail="Identitas aplikasi" active={active==="structure"} onClick={()=>setActive("structure")}/>}
      {has("users.manage")&&<Tab no="02" label="Pengguna" detail="Akun dan cakupan" active={active==="users"} onClick={()=>setActive("users")}/>}
      {has("roles.manage")&&<Tab no="03" label="Role" detail="Hak akses sistem" active={active==="roles"} onClick={()=>setActive("roles")}/>}
      {(has("news.manage")||has("approval.final")||has("publication.execute"))&&<Tab no={has("master.manage")?"04":"01"} label="Konten publik" detail="Berita sampai terbit" active={active==="news"} onClick={()=>setActive("news")}/>}
    </nav>

    {active==="structure"&&has("master.manage")&&<section className="admin-panel">
      <header><span>Konfigurasi Super Admin</span><h2>Identitas aplikasi</h2><p>Nama di sini menjadi nama portal, menu atas, dan footer. Satu instalasi hanya untuk satu Jurusan.</p></header>
      {orgs.filter(x=>x.status==="ACTIVE").map(org=><article className="admin-record primary" key={org.id}><div><small>JURUSAN AKTIF</small><h3>{org.name}</h3><p>{org.type} · {org.code}</p></div><button onClick={()=>{const name=prompt("Nama Jurusan baru",org.name);if(name)void act(()=>request(`/api/internal/organizations/${org.id}`,"PATCH",{name}))}}>Ubah nama</button></article>)}
      <header><span>Struktur akademik</span><h2>Program Studi</h2><p>Tambah, ubah, atau hapus Prodi. Penghapusan permanen hanya diizinkan bila belum memiliki data terkait.</p></header>
      <form className="admin-form" onSubmit={event=>{event.preventDefault();const form=event.currentTarget,f=data(event);void act(()=>request("/api/internal/study-programs","POST",{organizationId:Number(f.get("organizationId")),code:String(f.get("code")),name:String(f.get("name")),level:String(f.get("level")||"")}),form)}}><select name="organizationId" required><option value="">Pilih Jurusan</option>{orgs.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="code" placeholder="Kode Prodi" required/><input name="name" placeholder="Nama lengkap Prodi" required/><input name="level" placeholder="Jenjang, mis. D3"/><button>Tambah Prodi</button></form>
      <div className="admin-list">{prodis.map(prodi=><article className="admin-record" key={prodi.id}><div><h3>{prodi.name}</h3><p>{prodi.code} · {prodi.level||"Jenjang belum diisi"}</p></div><div className="record-actions"><button onClick={()=>{const name=prompt("Nama Prodi baru",prodi.name);if(name)void act(()=>request(`/api/internal/study-programs/${prodi.id}`,"PATCH",{name}))}}>Ubah nama</button><button className="danger" onClick={()=>remove(prodi.name,()=>request(`/api/internal/study-programs/${prodi.id}`,"DELETE"))}>Hapus permanen</button></div></article>)}</div>
    </section>}

    {active==="users"&&has("users.manage")&&<section className="admin-panel"><header><span>Khusus Super Admin</span><h2>Pengguna dan cakupan kerja</h2><p>Pilih role dan Prodi agar setiap akun hanya melihat pekerjaan yang menjadi kewenangannya.</p></header><form className="admin-form" onSubmit={event=>{event.preventDefault();const form=event.currentTarget,f=data(event);void act(()=>request("/api/internal/users","POST",{name:String(f.get("name")),email:String(f.get("email")),password:String(f.get("password")),roleCode:String(f.get("roleCode")),organizationId:Number(f.get("organizationId")),studyProgramId:f.get("studyProgramId")?Number(f.get("studyProgramId")):null}),form)}}><input name="name" placeholder="Nama pengguna" required/><input name="email" type="email" placeholder="Email login" required/><input name="password" type="password" placeholder="Password minimal 10 karakter" required/><select name="roleCode" required><option value="">Pilih role</option>{roles.filter(x=>x.status!=="ARCHIVED").map(x=><option key={x.id} value={x.code}>{x.name}</option>)}</select><select name="organizationId" required><option value="">Pilih Jurusan</option>{orgs.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="studyProgramId"><option value="">Seluruh Jurusan</option>{prodis.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button>Tambah pengguna</button></form><div className="admin-list">{users.map(user=><article className="admin-record" key={user.id}><div><h3>{user.name}</h3><p>{user.email} · {(user.assignments??[]).map((a:Row)=>a.roleCode).join(", ")||"Tanpa role"}</p></div><button className="danger" onClick={()=>remove(user.email,()=>request(`/api/internal/users/${user.id}`,"DELETE"))}>Hapus permanen</button></article>)}</div></section>}

    {active==="roles"&&has("roles.manage")&&<section className="admin-panel"><header><span>Khusus Super Admin</span><h2>Role dan permission</h2><p>Role sistem dilindungi. Role tambahan dapat dibuat sesuai pembagian tugas lokal.</p></header><form className="admin-form" onSubmit={event=>{event.preventDefault();const form=event.currentTarget,f=data(event);void act(()=>request("/api/internal/roles","POST",{code:String(f.get("code")),name:String(f.get("name")),permissionCodes:String(f.get("permissions")||"").split(",").map(x=>x.trim()).filter(Boolean)}),form)}}><input name="code" placeholder="Kode role" required/><input name="name" placeholder="Nama role" required/><textarea name="permissions" placeholder="Permission dipisahkan koma"/><button>Tambah role</button></form><details><summary>Lihat permission tersedia</summary><p className="muted">{permissionRows.map(x=>x.code).join(", ")}</p></details><div className="admin-list">{roles.map(role=><article className="admin-record" key={role.id}><div><h3>{role.name}</h3><p>{role.code}{role.isSystemRole?" · role sistem":""}</p></div></article>)}</div></section>}

    {active==="news"&&<section className="admin-panel"><header><span>Ruang Admin Jurusan</span><h2>Konten publik</h2><p>Alur kerja: buat draft → ajukan → disetujui Kajur → dipublikasikan. Draft yang belum diajukan dapat dihapus permanen.</p></header>{has("news.manage")&&<><form className="admin-form compact" onSubmit={event=>{event.preventDefault();const form=event.currentTarget,f=data(event);void act(()=>request("/api/internal/news/categories","POST",{name:String(f.get("name"))}),form)}}><input name="name" placeholder="Kategori berita baru" required/><button>Tambah kategori</button></form><div className="admin-chips">{categories.map(category=><span key={category.id}>{category.name}<button aria-label={`Hapus ${category.name}`} onClick={()=>remove(category.name,()=>request(`/api/internal/news/categories/${category.id}`,"DELETE"))}>×</button></span>)}</div><form className="admin-form" onSubmit={event=>{event.preventDefault();const form=event.currentTarget,f=data(event);void act(()=>request("/api/internal/news/articles","POST",{organizationId:Number(f.get("organizationId")),categoryId:f.get("categoryId")?Number(f.get("categoryId")):null,title:String(f.get("title")),excerpt:String(f.get("excerpt")||""),body:String(f.get("body")),featured:false}),form)}}><select name="organizationId" required>{orgs.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="categoryId"><option value="">Tanpa kategori</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="title" placeholder="Judul berita" required/><textarea name="excerpt" placeholder="Ringkasan singkat"/><textarea name="body" placeholder="Isi berita" required/><button>Simpan sebagai draft</button></form></>}
      <div className="workflow-guide"><span>DRAFT</span><i>→</i><span>SUBMITTED</span><i>→</i><span>APPROVED</span><i>→</i><span>PUBLISHED</span></div><div className="admin-list">{articles.map(article=><article className="admin-record" key={article.id}><div><small>{article.category??"Tanpa kategori"}</small><h3>{article.title}</h3><p>Status: {article.lifecycleStatus}</p></div><div className="record-actions">{has("news.manage")&&article.lifecycleStatus==="DRAFT"&&<><button onClick={()=>void act(()=>request(`/api/internal/news/articles/${article.id}`,"PATCH",{lifecycleStatus:"SUBMITTED"}))}>Ajukan</button><button className="danger" onClick={()=>remove(article.title,()=>request(`/api/internal/news/articles/${article.id}`,"DELETE"))}>Hapus draft</button></>}{has("approval.final")&&article.lifecycleStatus==="SUBMITTED"&&<button onClick={()=>void act(()=>request("/api/internal/approvals","POST",{subjectType:"NEWS_ARTICLE",subjectId:article.id,decision:"APPROVED"}))}>Setujui</button>}{has("publication.execute")&&article.lifecycleStatus==="APPROVED"&&<button onClick={()=>void act(()=>request("/api/internal/publications","POST",{subjectType:"NEWS_ARTICLE",subjectId:article.id,publicTitle:article.title,publicSummary:article.excerpt??""}))}>Publikasikan</button>}</div></article>)}</div>
    </section>}
  </div>;
}

function Tab({no,label,detail,active,onClick}:{no:string;label:string;detail:string;active:boolean;onClick:()=>void}){return <button type="button" className={active?"active":""} onClick={onClick}><b>{no}</b><span>{label}<small>{detail}</small></span></button>}
