"use client";
import { FormEvent, useEffect, useState } from "react";

type Row=Record<string,any>;
export default function AdminConsole({permissions}:{permissions:string[]}){
 const has=(p:string)=>permissions.includes(p);
 const [orgs,setOrgs]=useState<Row[]>([]),[prodis,setProdis]=useState<Row[]>([]),[users,setUsers]=useState<Row[]>([]),[roles,setRoles]=useState<Row[]>([]),[permissionRows,setPermissionRows]=useState<Row[]>([]),[categories,setCategories]=useState<Row[]>([]),[articles,setArticles]=useState<Row[]>([]),[message,setMessage]=useState("");
 async function request(url:string,method="GET",body?:unknown){const r=await fetch(url,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error&&typeof data.error==="string"?data.error:"Operasi gagal");return data;}
 async function load(){try{if(has("internal.read")||has("master.manage")||has("news.manage")||has("users.manage")){setOrgs(await request("/api/internal/organizations"));setProdis(await request("/api/internal/study-programs"));}if(has("users.manage"))setUsers(await request("/api/internal/users"));if(has("roles.manage")){const d=await request("/api/internal/roles");setRoles(d.roles??[]);setPermissionRows(d.permissions??[]);}if(has("news.manage")||has("approval.final")||has("publication.execute")){setArticles(await request("/api/internal/news/articles"));if(has("news.manage"))setCategories(await request("/api/internal/news/categories"));}}catch(e){setMessage(e instanceof Error?e.message:"Gagal memuat data");}}
 useEffect(()=>{void load()},[]);
 async function act(fn:()=>Promise<unknown>){try{await fn();setMessage("Perubahan tersimpan.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Operasi gagal")}}
 const fd=(e:FormEvent<HTMLFormElement>)=>new FormData(e.currentTarget);
 return <div className="section">
  {message&&<div className="card" style={{marginBottom:16}}>{message}</div>}
  {has("master.manage")&&<>
   <h2>Organisasi / Jurusan / UPPS</h2><form className="card" onSubmit={e=>{e.preventDefault();const f=fd(e);void act(()=>request("/api/internal/organizations","POST",{type:String(f.get("type")),code:String(f.get("code")),name:String(f.get("name")),parentId:f.get("parentId")?Number(f.get("parentId")):null}))}}><input name="type" placeholder="Tipe: UPPS/JURUSAN" required/><input name="code" placeholder="Kode" required/><input name="name" placeholder="Nama organisasi" required/><select name="parentId"><option value="">Tanpa parent</option>{orgs.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="button">Tambah organisasi</button></form>
   <div className="grid">{orgs.map(x=><div className="card" key={x.id}><b>{x.name}</b><p className="muted">{x.type} · {x.code} · {x.status}</p><button onClick={()=>{const name=prompt("Nama baru",x.name);if(name)void act(()=>request(`/api/internal/organizations/${x.id}`,"PATCH",{name}))}}>Ubah</button> <button onClick={()=>void act(()=>request(`/api/internal/organizations/${x.id}`,x.status==="ARCHIVED"?"PATCH":"DELETE",x.status==="ARCHIVED"?{status:"ACTIVE"}:undefined))}>{x.status==="ARCHIVED"?"Aktifkan":"Arsipkan"}</button></div>)}</div>
   <h2>Program Studi</h2><form className="card" onSubmit={e=>{e.preventDefault();const f=fd(e);void act(()=>request("/api/internal/study-programs","POST",{organizationId:Number(f.get("organizationId")),code:String(f.get("code")),name:String(f.get("name")),level:String(f.get("level"))}))}}><select name="organizationId" required><option value="">Pilih Jurusan/UPPS</option>{orgs.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="code" placeholder="Kode Prodi" required/><input name="name" placeholder="Nama Prodi" required/><input name="level" placeholder="Jenjang, mis. D3"/><button className="button">Tambah Prodi</button></form>
   <div className="grid">{prodis.map(x=><div className="card" key={x.id}><b>{x.name}</b><p className="muted">{x.code} · {x.level} · {x.status}</p><button onClick={()=>{const name=prompt("Nama baru",x.name);if(name)void act(()=>request(`/api/internal/study-programs/${x.id}`,"PATCH",{name}))}}>Ubah</button> <button onClick={()=>void act(()=>request(`/api/internal/study-programs/${x.id}`,x.status==="ARCHIVED"?"PATCH":"DELETE",x.status==="ARCHIVED"?{status:"ACTIVE"}:undefined))}>{x.status==="ARCHIVED"?"Aktifkan":"Arsipkan"}</button></div>)}</div>
  </>}
  {has("roles.manage")&&<><h2>Role & Permission</h2><form className="card" onSubmit={e=>{e.preventDefault();const f=fd(e);void act(()=>request("/api/internal/roles","POST",{code:String(f.get("code")),name:String(f.get("name")),permissionCodes:String(f.get("permissions")||"").split(",").map(x=>x.trim()).filter(Boolean)}))}}><input name="code" placeholder="Kode role" required/><input name="name" placeholder="Nama role" required/><input name="permissions" placeholder="permission1, permission2"/><button className="button">Tambah role</button><p className="muted">Capability tersedia: {permissionRows.map(x=>x.code).join(", ")}</p></form><div className="grid">{roles.map(x=><div className="card" key={x.id}><b>{x.name}</b><p className="muted">{x.code} · {x.status}{x.isSystemRole?" · system":""}</p><small>{(x.permissionCodes??[]).join(", ")}</small>{!x.isSystemRole&&<p><button onClick={()=>void act(()=>request(`/api/internal/roles/${x.id}`,x.status==="ARCHIVED"?"PATCH":"DELETE",x.status==="ARCHIVED"?{status:"ACTIVE"}:undefined))}>{x.status==="ARCHIVED"?"Aktifkan":"Arsipkan"}</button></p>}</div>)}</div></>}
  {has("users.manage")&&<><h2>User</h2><form className="card" onSubmit={e=>{e.preventDefault();const f=fd(e);void act(()=>request("/api/internal/users","POST",{name:String(f.get("name")),email:String(f.get("email")),password:String(f.get("password")),roleCode:String(f.get("roleCode")),organizationId:Number(f.get("organizationId")),studyProgramId:f.get("studyProgramId")?Number(f.get("studyProgramId")):null}))}}><input name="name" placeholder="Nama" required/><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password minimal 10 karakter" required/><select name="roleCode" required><option value="">Pilih role</option>{roles.filter(x=>x.status!=="ARCHIVED").map(x=><option key={x.id} value={x.code}>{x.name}</option>)}</select><select name="organizationId" required><option value="">Pilih organisasi</option>{orgs.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="studyProgramId"><option value="">Tanpa scope Prodi</option>{prodis.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="button">Tambah user</button></form><div className="grid">{users.map(x=><div className="card" key={x.id}><b>{x.name}</b><p className="muted">{x.email} · {x.status}</p><small>{(x.assignments??[]).map((a:Row)=>a.roleCode).join(", ")}</small>{x.status==="ARCHIVED"?<p><button onClick={()=>void act(()=>request(`/api/internal/users/${x.id}`,"PATCH",{status:"ACTIVE"}))}>Aktifkan</button></p>:<p><button onClick={()=>void act(()=>request(`/api/internal/users/${x.id}`,"DELETE"))}>Arsipkan</button></p>}</div>)}</div></>}
  {has("news.manage")&&<><h2>Kategori Berita</h2><form className="card" onSubmit={e=>{e.preventDefault();const f=fd(e);void act(()=>request("/api/internal/news/categories","POST",{name:String(f.get("name"))}))}}><input name="name" placeholder="Nama kategori" required/><button className="button">Tambah kategori</button></form><div className="grid">{categories.map(x=><div className="card" key={x.id}><b>{x.name}</b><p className="muted">{x.status}</p><button onClick={()=>void act(()=>request(`/api/internal/news/categories/${x.id}`,x.status==="ARCHIVED"?"PATCH":"DELETE",x.status==="ARCHIVED"?{status:"ACTIVE"}:undefined))}>{x.status==="ARCHIVED"?"Aktifkan":"Arsipkan"}</button></div>)}</div>
   <h2>Berita</h2><form className="card" onSubmit={e=>{e.preventDefault();const f=fd(e);void act(()=>request("/api/internal/news/articles","POST",{organizationId:Number(f.get("organizationId")),categoryId:f.get("categoryId")?Number(f.get("categoryId")):null,title:String(f.get("title")),excerpt:String(f.get("excerpt")||""),body:String(f.get("body")),featured:false}))}}><select name="organizationId" required><option value="">Pilih organisasi</option>{orgs.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="categoryId"><option value="">Tanpa kategori</option>{categories.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="title" placeholder="Judul berita" required/><textarea name="excerpt" placeholder="Ringkasan"/><textarea name="body" placeholder="Isi berita" required/><button className="button">Tambah draft berita</button></form>
  </>}
  {(has("news.manage")||has("approval.final")||has("publication.execute"))&&<><h2>Workflow Berita</h2><div className="grid">{articles.map(x=><div className="card" key={x.id}><b>{x.title}</b><p className="muted">{x.category??"Tanpa kategori"} · {x.lifecycleStatus}</p>{has("news.manage")&&x.lifecycleStatus==="DRAFT"&&<button onClick={()=>void act(()=>request(`/api/internal/news/articles/${x.id}`,"PATCH",{lifecycleStatus:"SUBMITTED"}))}>Submit</button>} {has("approval.final")&&x.lifecycleStatus==="SUBMITTED"&&<button onClick={()=>void act(()=>request("/api/internal/approvals","POST",{subjectType:"NEWS_ARTICLE",subjectId:x.id,decision:"APPROVED"}))}>Approve</button>} {has("publication.execute")&&x.lifecycleStatus==="APPROVED"&&<button onClick={()=>void act(()=>request("/api/internal/publications","POST",{subjectType:"NEWS_ARTICLE",subjectId:x.id,publicTitle:x.title,publicSummary:x.excerpt??""}))}>Publish</button>} {has("news.manage")&&!(["APPROVED","PUBLISHED","ARCHIVED"].includes(x.lifecycleStatus))&&<button onClick={()=>void act(()=>request(`/api/internal/news/articles/${x.id}`,"DELETE"))}>Arsipkan</button>}</div>)}</div></>}
 </div>
}
