import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { federatedApplications } from "@/src/db/schema-admin";
import { audit } from "@/src/lib/audit";
import { getSession } from "@/src/lib/auth";
import { can } from "@/src/lib/rbac";
import { decryptFederationToken,encryptFederationToken,normalizedFederationUrl } from "@/src/services/federation-security";

const createInput=z.object({code:z.string().min(2).max(80),name:z.string().min(2).max(255),baseUrl:z.string().url().max(700),organizationCode:z.string().max(80).optional(),accessToken:z.string().min(24)});
const updateInput=z.object({id:z.number().int().positive(),action:z.literal("UPDATE"),name:z.string().min(2).max(255).optional(),baseUrl:z.string().url().max(700).optional(),organizationCode:z.string().max(80).nullable().optional(),accessToken:z.string().min(24).optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional()});
const syncInput=z.object({id:z.number().int().positive(),action:z.literal("SYNC")});
const patchInput=z.discriminatedUnion("action",[updateInput,syncInput]);
async function sessionGuard(){const session=await getSession();if(!session)return {response:NextResponse.json({error:"Unauthorized"},{status:401})};if(!can(session,"system.configure"))return {response:NextResponse.json({error:"Forbidden"},{status:403})};return {session};}

export async function GET(){const auth=await sessionGuard();if(auth.response)return auth.response;const rows=await requireDb().select().from(federatedApplications);return NextResponse.json(rows.map(({encryptedAccessToken,...row})=>({...row,hasAccessToken:Boolean(encryptedAccessToken)})));}
export async function POST(req:Request){const auth=await sessionGuard();if(auth.response)return auth.response;const parsed=createInput.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});const db=requireDb();let baseUrl:string;try{baseUrl=normalizedFederationUrl(parsed.data.baseUrl);}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"URL tidak valid."},{status:400});}const result=await db.insert(federatedApplications).values({code:parsed.data.code.toUpperCase(),name:parsed.data.name,baseUrl,organizationCode:parsed.data.organizationCode?.toUpperCase(),encryptedAccessToken:encryptFederationToken(parsed.data.accessToken),status:"ACTIVE",connectionStatus:"NOT_CHECKED"});const id=Number(result[0].insertId);await audit({actorId:auth.session!.userId,action:"CREATE_FEDERATED_APPLICATION",subjectType:"FEDERATED_APPLICATION",subjectId:id,after:{...parsed.data,accessToken:"[REDACTED]",baseUrl}});return NextResponse.json({id,status:"ACTIVE"},{status:201});}
export async function PATCH(req:Request){const auth=await sessionGuard();if(auth.response)return auth.response;const parsed=patchInput.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(federatedApplications).where(eq(federatedApplications.id,parsed.data.id)).limit(1);if(!before)return NextResponse.json({error:"Aplikasi Jurusan tidak ditemukan."},{status:404});if(parsed.data.action==="UPDATE"){const{id,action,accessToken,baseUrl,...changes}=parsed.data;let normalized=baseUrl;try{if(baseUrl)normalized=normalizedFederationUrl(baseUrl);}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"URL tidak valid."},{status:400});}const values={...changes,...(normalized?{baseUrl:normalized}:{}),...(accessToken?{encryptedAccessToken:encryptFederationToken(accessToken)}:{}),updatedAt:new Date()};await db.update(federatedApplications).set(values).where(eq(federatedApplications.id,id));await audit({actorId:auth.session!.userId,action:"UPDATE_FEDERATED_APPLICATION",subjectType:"FEDERATED_APPLICATION",subjectId:id,before:{...before,encryptedAccessToken:"[REDACTED]"},after:{...changes,accessToken:accessToken?"[REDACTED]":undefined}});return NextResponse.json({id,...changes});}if(before.status!=="ACTIVE")return NextResponse.json({error:"Aplikasi yang diarsipkan tidak dapat disinkronkan."},{status:409});try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);const response=await fetch(`${before.baseUrl}/api/federation/summary`,{headers:{authorization:`Bearer ${decryptFederationToken(before.encryptedAccessToken??"")}`},signal:controller.signal,cache:"no-store"});clearTimeout(timer);if(!response.ok)throw new Error(`Endpoint merespons HTTP ${response.status}.`);const snapshot=await response.json();if(snapshot?.schemaVersion!==1)throw new Error("Versi ringkasan federasi tidak didukung.");const now=new Date();await db.update(federatedApplications).set({connectionStatus:"ONLINE",lastHealthAt:now,lastSyncAt:now,lastError:null,summarySnapshot:snapshot,updatedAt:now}).where(eq(federatedApplications.id,before.id));await audit({actorId:auth.session!.userId,action:"SYNC_FEDERATED_APPLICATION",subjectType:"FEDERATED_APPLICATION",subjectId:before.id,after:{connectionStatus:"ONLINE",generatedAt:snapshot.generatedAt}});return NextResponse.json({id:before.id,connectionStatus:"ONLINE",summarySnapshot:snapshot});}catch(error){const message=error instanceof Error?error.message:"Sinkronisasi gagal.";await db.update(federatedApplications).set({connectionStatus:"OFFLINE",lastHealthAt:new Date(),lastError:message,updatedAt:new Date()}).where(eq(federatedApplications.id,before.id));return NextResponse.json({error:message,connectionStatus:"OFFLINE"},{status:502});}}
export async function DELETE(req:Request){const auth=await sessionGuard();if(auth.response)return auth.response;const id=Number(new URL(req.url).searchParams.get("id"));if(!id)return NextResponse.json({error:"id wajib."},{status:400});const db=requireDb();const[before]=await db.select().from(federatedApplications).where(eq(federatedApplications.id,id)).limit(1);if(!before)return NextResponse.json({error:"Aplikasi Jurusan tidak ditemukan."},{status:404});await db.update(federatedApplications).set({status:"ARCHIVED",connectionStatus:"DISCONNECTED",updatedAt:new Date()}).where(eq(federatedApplications.id,id));await audit({actorId:auth.session!.userId,action:"ARCHIVE_FEDERATED_APPLICATION",subjectType:"FEDERATED_APPLICATION",subjectId:id,before:{...before,encryptedAccessToken:"[REDACTED]"},after:{status:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
