"use client";
import { FormEvent,useEffect,useState } from "react";
type Tenant=Record<string,any>;
export default function MasterConsole(){
 const[rows,setRows]=useState<Tenant[]>([]),[message,setMessage]=useState(""),[deployment,setDeployment]=useState<Record<string,any>|null>(null);
 async function load(){const response=await fetch("/api/master/tenants");if(response.ok)setRows(await response.json());}
 useEffect(()=>{void load()},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);const programs=String(data.get("programs")).split("\n").map(line=>line.trim()).filter(Boolean).map(line=>{const[code,name,level,frameworkCode]=line.split("|").map(x=>x.trim());return{code,name,level:level||undefined,frameworkCode:frameworkCode||undefined}});setMessage("Membuat database, Prodi, template, dan admin awal...");setDeployment(null);const response=await fetch("/api/master/tenants",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:data.get("code"),name:data.get("name"),domain:data.get("domain"),databaseName:data.get("databaseName"),organizationType:data.get("organizationType"),programs,adminName:data.get("adminName"),adminEmail:data.get("adminEmail"),adminPassword:data.get("adminPassword")})});const result=await response.json().catch(()=>({}));setMessage(response.ok?result.message:typeof result.error==="string"?result.error:"Provisioning gagal.");if(response.ok){setDeployment(result.deployment);form.reset();await load();}}
 return <div className="master-grid"><section className="master-card"><h2>Buat aplikasi Jurusan</h2><p>Master membuat database Tenant baru dari codebase yang sama. Domain diarahkan ke deployment dengan mode TENANT.</p><nav className="master-links"><a href="/internal/accreditation">Registry LAM & template</a><a href="/internal/federation">Federasi Jurusan</a></nav><form onSubmit={submit}><input name="code" placeholder="Kode, mis. PERKAPALAN" required/><input name="name" placeholder="Nama Jurusan/UPPS" required/><input name="domain" type="url" placeholder="https://perkapalan.example.ac.id" required/><input name="databaseName" placeholder="jurusan_perkapalan" required/><select name="organizationType"><option>UPPS</option><option>JURUSAN</option><option>FAKULTAS</option></select><textarea name="programs" placeholder={'Kode Prodi | Nama Prodi | D3 | Kode framework ACTIVE\nTEKNIK-MESIN | Teknik Mesin | D3 | LAM-TEKNIK-D3'} required/><input name="adminName" placeholder="Nama Admin Jurusan" required/><input name="adminEmail" type="email" placeholder="Email Admin Jurusan" required/><input name="adminPassword" type="password" minLength={10} placeholder="Password awal minimal 10 karakter" required/><button>Buat database dan aplikasi</button></form>{message&&<div className="master-message">{message}</div>}{deployment&&<div className="deployment-result"><b>Konfigurasi deployment—simpan sekarang</b><code>APP_MODE=TENANT</code><code>DATABASE: {deployment.databaseName}</code><code>FEDERATION_EXPORT_TOKEN={deployment.federationToken}</code><small>Token hanya ditampilkan pada hasil provisioning ini.</small></div>}</section><section className="master-card"><h2>Aplikasi Jurusan</h2>{rows.length?rows.map(row=><article key={row.id}><div><b>{row.name}</b><small>{row.code} · {row.databaseName}</small><a href={row.domain} target="_blank" rel="noreferrer">{row.domain}</a></div><span>{row.deploymentStatus}</span></article>):<p>Belum ada aplikasi Jurusan yang diprovisioning.</p>}</section></div>;
}
