"use client";
import {FormEvent,useEffect,useState} from "react";
type Row=Record<string,any>;
type Program={code:string;name:string;level:string;frameworkCode:string};
const emptyProgram=():Program=>({code:"",name:"",level:"D3",frameworkCode:""});
const statusLabel:Record<string,string>={PROVISIONING:"Sedang dibuat",DATABASE_READY:"Database siap—belum online",TENANT_LOCAL_READY:"Folder lokal siap dijalankan",AWAITING_DATABASE:"Menunggu database",FAILED:"Gagal"};

export default function MasterConsole(){
 const[tenants,setTenants]=useState<Row[]>([]),[frameworks,setFrameworks]=useState<Row[]>([]),[programs,setPrograms]=useState<Program[]>([emptyProgram()]),[message,setMessage]=useState(""),[deployment,setDeployment]=useState<Row|null>(null),[detail,setDetail]=useState<Row|null>(null),[detailLoading,setDetailLoading]=useState<number|null>(null);
 async function load(){const[tenantResponse,frameworkResponse]=await Promise.all([fetch("/api/master/tenants"),fetch("/api/internal/accreditation/frameworks")]);if(tenantResponse.ok)setTenants(await tenantResponse.json());if(frameworkResponse.ok)setFrameworks((await frameworkResponse.json()).filter((row:Row)=>row.lifecycleStatus==="ACTIVE"));}
 useEffect(()=>{void load()},[]);
 function changeProgram(index:number,key:keyof Program,value:string){setPrograms(rows=>rows.map((row,i)=>i===index?{...row,[key]:value}:row));}
 async function removeTenant(row:Row){if(!confirm(`Hapus permanen aplikasi ${row.name}, database ${row.databaseName}, data provisioning, dan koneksi federasinya? Tindakan ini tidak dapat dibatalkan.`))return;const confirmationCode=prompt(`Ketik kode ${row.code} untuk melanjutkan:`);if(confirmationCode===null)return;setMessage(`Menghapus permanen ${row.name}...`);const response=await fetch(`/api/master/tenants?id=${row.id}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmationCode})});const result=await response.json().catch(()=>({}));setMessage(response.ok?result.message:result.error||"Penghapusan gagal.");if(response.ok)await load();}
 async function showDetail(row:Row){if(detail?.id===row.id){setDetail(null);return;}setDetailLoading(row.id);const response=await fetch(`/api/master/tenants?id=${row.id}`);const result=await response.json().catch(()=>({}));setDetailLoading(null);if(response.ok)setDetail(result);else setMessage(result.error||"Detail Jurusan tidak dapat dimuat.");}
 async function resetPassword(event:FormEvent<HTMLFormElement>,row:Row){event.preventDefault();const form=event.currentTarget,data=new FormData(form);if(!confirm(`Atur ulang password akun ${data.get("email")}?`))return;const response=await fetch("/api/master/tenants",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id,action:"RESET_ADMIN_PASSWORD",email:data.get("email"),newPassword:data.get("newPassword")})});const result=await response.json().catch(()=>({}));setMessage(response.ok?result.message:result.error||"Password gagal diatur ulang.");if(response.ok)form.reset();}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setMessage(data.get("deploymentTarget")==="LOCAL"?"Membuat database dan folder aplikasi Tenant lokal...":"Membuat database serta konfigurasi deployment VPS...");setDeployment(null);const response=await fetch("/api/master/tenants",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:data.get("code"),name:data.get("name"),domain:data.get("domain"),databaseName:data.get("databaseName"),organizationType:data.get("organizationType"),deploymentTarget:data.get("deploymentTarget"),programs,adminName:data.get("adminName"),adminEmail:data.get("adminEmail"),adminPassword:data.get("adminPassword")})});const result=await response.json().catch(()=>({}));const detail=typeof result.error==="string"?result.error:result.error?.formErrors?.join(" ")||Object.values(result.error?.fieldErrors??{}).flat().join(" ");setMessage(response.ok?result.message:detail||"Data belum lengkap atau provisioning gagal.");if(response.ok){setDeployment(result.deployment);setPrograms([emptyProgram()]);form.reset();await load();}}
 return <>
  <section className="master-prerequisite"><div><b>Prasyarat langkah 2</b><span>{frameworks.length?`${frameworks.length} instrumen ACTIVE tersedia dan dapat dipilih untuk setiap Prodi.`:"Belum ada instrumen ACTIVE. Selesaikan menu Template LAM terlebih dahulu."}</span></div><a href="/internal/accreditation">Buka Template LAM →</a></section>
  <div className="master-grid">
   <section className="master-card"><h2>2. Buat aplikasi Jurusan</h2><p>Isi identitas aplikasi, tentukan Program Studi beserta instrumennya, kemudian buat akun Admin Jurusan.</p><div className="deployment-explanation"><div><b>Simulasi lokal</b><span>Master membuat database, menyalin codebase ke folder Tenant baru, dan membuat .env.local. Jalankan Tenant pada port berbeda.</span></div><div><b>Server/VPS</b><span>Master membuat database dan konfigurasi. Codebase tetap harus dipasang di VPS lalu domain diarahkan ke instance Tenant.</span></div></div><form onSubmit={submit}>
    <label><span>Tujuan pemasangan</span><select name="deploymentTarget" required><option value="LOCAL">Simulasi lokal — buat folder Tenant otomatis</option><option value="VPS">Server/VPS — siapkan konfigurasi deployment</option></select></label>
    <input name="code" placeholder="Kode Jurusan, mis. PERKAPALAN" required/><input name="name" placeholder="Nama Jurusan/UPPS" required/><input name="domain" type="url" placeholder="https://perkapalan.example.ac.id" required/><input name="databaseName" placeholder="Nama database, mis. jurusan_perkapalan" required/><select name="organizationType"><option>UPPS</option><option>JURUSAN</option><option>FAKULTAS</option></select>
    <fieldset className="program-builder"><legend>Program Studi dan Instrumen Akreditasi</legend><p className="program-help">Setiap Program Studi wajib memilih satu instrumen LAM aktif untuk pengisian dan evaluasi.</p>{programs.map((program,index)=><div className="program-row" key={index}>
     <label><span>Kode Prodi</span><input value={program.code} onChange={event=>changeProgram(index,"code",event.target.value)} placeholder="Contoh: D3-TK" required/></label>
     <label><span>Nama Program Studi</span><input value={program.name} onChange={event=>changeProgram(index,"name",event.target.value)} placeholder="Nama lengkap Prodi" required/></label>
     <label><span>Jenjang</span><select value={program.level} onChange={event=>changeProgram(index,"level",event.target.value)} required><option>D3</option><option>D4</option><option>S1</option><option>S2</option><option>S3</option><option>PROFESI</option></select></label>
     <label><span>Instrumen yang digunakan</span><select value={program.frameworkCode} onChange={event=>changeProgram(index,"frameworkCode",event.target.value)} required><option value="">Pilih instrumen LAM</option>{frameworks.map(row=><option key={`${row.id}-${row.versionNumber}`} value={row.code}>{row.agencyCode} · {row.name} · {row.educationLevel??"Semua jenjang"} · v{row.versionNumber}</option>)}</select></label>
     {programs.length>1&&<button className="remove-program" type="button" onClick={()=>setPrograms(rows=>rows.filter((_,i)=>i!==index))}>Hapus Prodi</button>}
    </div>)}<button type="button" className="add-program" onClick={()=>setPrograms(rows=>[...rows,emptyProgram()])}>+ Tambah Program Studi</button></fieldset>
    <input name="adminName" placeholder="Nama Admin Jurusan" required/><input name="adminEmail" type="email" placeholder="Email Admin Jurusan" required/><input name="adminPassword" type="password" minLength={10} placeholder="Password awal minimal 10 karakter" required/><button disabled={!frameworks.length}>Buat database dan aplikasi</button>
   </form>{message&&<div className="master-message">{message}</div>}{deployment&&<div className="deployment-result"><b>{deployment.target==="LOCAL"?"Tenant lokal siap dijalankan":"Database siap—lanjutkan pemasangan di VPS"}</b>{deployment.localFolder&&<><span>Folder aplikasi Tenant</span><code>{deployment.localFolder}</code><span>Konfigurasi sudah dibuat otomatis</span><code>{deployment.environmentFile}</code><small>Buka PowerShell pada folder tersebut, jalankan npm install, lalu npm run dev -- -p PORT_YANG_KOSONG.</small></>} {!deployment.localFolder&&<><code>APP_MODE=TENANT</code><code>DATABASE: {deployment.databaseName}</code><code>DOMAIN: {deployment.domain}</code><code>FEDERATION_EXPORT_TOKEN={deployment.federationToken}</code><small>Salin codebase ke VPS, buat .env.local dari nilai ini, jalankan build/start, lalu arahkan domain. Pembuatan database tidak otomatis meng-online-kan domain.</small></>}</div>}</section>
   <section className="master-card"><h2>Aplikasi Jurusan</h2><p>Status “database siap” belum berarti domain sudah dapat dibuka.</p>{tenants.length?tenants.map(row=><div className="tenant-record" key={row.id}><article><div><b>{row.name}</b><small>{row.code} · {row.databaseName}</small><a href={row.domain} target="_blank" rel="noreferrer">{row.domain}</a></div><div className="tenant-actions"><span title={row.deploymentStatus}>{statusLabel[row.deploymentStatus]??row.deploymentStatus}</span><button type="button" onClick={()=>void showDetail(row)}>{detailLoading===row.id?"Memuat...":detail?.id===row.id?"Tutup detail":"Detail"}</button><button type="button" className="danger" onClick={()=>void removeTenant(row)}>Hapus permanen</button></div></article>{detail&&detail.id===row.id&&<section className="tenant-detail"><div className="tenant-detail-grid"><div><small>Identitas</small><b>{detail.name}</b><span>{detail.code} · {detail.organizationType}</span></div><div><small>Database</small><b>{detail.databaseName}</b><span>{statusLabel[detail.deploymentStatus]??detail.deploymentStatus}</span></div><div><small>Domain tujuan</small><b>{detail.domain}</b><span>Belum dianggap online sebelum federasi tersambung.</span></div></div><h3>Program Studi dan instrumen</h3><div className="detail-list">{detail.databaseDetails.programs.map((program:Row)=><div key={`${program.id}-${program.frameworkCode}`}><b>{program.name}</b><span>{program.code} · {program.level??"Jenjang belum diisi"}</span><small>{program.frameworkName?`${program.agencyName??program.agencyCode} · ${program.frameworkName} · v${program.frameworkVersion}`:"Instrumen belum terpasang"}</small></div>)}</div><h3>Pengelola dan pemulihan akun</h3><div className="detail-list">{detail.databaseDetails.admins.map((admin:Row)=><form key={`${admin.id}-${admin.roleCode??"NO_ROLE"}`} onSubmit={event=>void resetPassword(event,row)}><div><b>{admin.name}</b><span>{admin.email}</span><small>{admin.roleName??admin.roleCode??"Role belum terpasang—atur ulang password untuk memulihkan Admin Jurusan"} · {admin.status}</small></div><input type="hidden" name="email" value={admin.email}/><input name="newPassword" type="password" minLength={10} placeholder="Password baru minimal 10 karakter" required/><button>Atur ulang password</button></form>)}</div><p className="security-note">Password lama tidak dapat ditampilkan karena tidak disimpan sebagai teks. Super Admin hanya dapat menetapkan password baru.</p></section>}</div>):<p>Belum ada aplikasi Jurusan yang diprovisioning.</p>}</section>
  </div>
 </>;
}
