import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { publicationPolicies } from "@/src/db/schema";
import { audit } from "@/src/lib/audit";
import { getSession } from "@/src/lib/auth";
import { can } from "@/src/lib/rbac";
const create=z.object({subjectType:z.string().min(2).max(100),policyVersion:z.number().int().positive().default(1),allowedFields:z.array(z.string()).min(1),requiredLifecycleStatus:z.string().max(30).optional(),requiresApproval:z.boolean().default(true)});
const patch=z.object({id:z.number().int().positive(),allowedFields:z.array(z.string()).min(1).optional(),requiredLifecycleStatus:z.string().max(30).nullable().optional(),requiresApproval:z.boolean().optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional()});
async function guard(){const session=await getSession();if(!session)return {response:NextResponse.json({error:"Unauthorized"},{status:401})};if(!can(session,"system.configure"))return {response:NextResponse.json({error:"Forbidden"},{status:403})};return {session};}
export async function GET(){const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(session,"publication.execute")||can(session,"system.configure")))return NextResponse.json({error:"Forbidden"},{status:403});return NextResponse.json(await requireDb().select().from(publicationPolicies));}
export async function POST(req:Request){const auth=await guard();if(auth.response)return auth.response;const parsed=create.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});const result=await requireDb().insert(publicationPolicies).values({...parsed.data,subjectType:parsed.data.subjectType.toUpperCase(),status:"ACTIVE"});const id=Number(result[0].insertId);await audit({actorId:auth.session!.userId,action:"CREATE_PUBLICATION_POLICY",subjectType:"PUBLICATION_POLICY",subjectId:id,after:parsed.data});return NextResponse.json({id,status:"ACTIVE"},{status:201});}
export async function PATCH(req:Request){const auth=await guard();if(auth.response)return auth.response;const parsed=patch.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});const{id,...changes}=parsed.data;const db=requireDb();const[before]=await db.select().from(publicationPolicies).where(eq(publicationPolicies.id,id)).limit(1);if(!before)return NextResponse.json({error:"Kebijakan tidak ditemukan."},{status:404});await db.update(publicationPolicies).set(changes).where(eq(publicationPolicies.id,id));await audit({actorId:auth.session!.userId,action:"UPDATE_PUBLICATION_POLICY",subjectType:"PUBLICATION_POLICY",subjectId:id,before,after:changes});return NextResponse.json({id,...changes});}
export async function DELETE(req:Request){const auth=await guard();if(auth.response)return auth.response;const id=Number(new URL(req.url).searchParams.get("id"));if(!id)return NextResponse.json({error:"id wajib."},{status:400});return PATCH(new Request(req.url,{method:"PATCH",headers:{cookie:req.headers.get("cookie")??"","content-type":"application/json"},body:JSON.stringify({id,status:"ARCHIVED"})}));}
