import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { cooperations } from "@/src/db/schema-phase6";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { canReadResourceScope,canWriteResourceScope,validateProgramUnderOrganization } from "@/src/services/resource-scope";
const createInput=z.object({organizationId:z.number().int().positive(),studyProgramId:z.number().int().positive().nullable().optional(),partnerName:z.string().min(2).max(500),partnerType:z.string().max(100).optional(),scope:z.string().min(3),startDate:z.string().optional(),endDate:z.string().optional(),implementationSummary:z.string().optional(),cooperationStatus:z.enum(["PLANNED","ACTIVE","EXPIRED","TERMINATED"]).default("ACTIVE")});
const patchInput=createInput.omit({organizationId:true,studyProgramId:true}).partial().extend({lifecycleStatus:z.enum(["DRAFT","SUBMITTED","ARCHIVED"]).optional()});
function idParam(req:Request){const n=Number(new URL(req.url).searchParams.get("id"));return Number.isInteger(n)&&n>0?n:null;}
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const db=requireDb();const rows=await db.select().from(cooperations);return NextResponse.json(rows.filter(x=>canReadResourceScope(s,x.organizationId,x.studyProgramId)));}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const p=createInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const studyProgramId=p.data.studyProgramId??null;if(studyProgramId&&!(await validateProgramUnderOrganization(studyProgramId,p.data.organizationId)))return NextResponse.json({error:"Program Studi tidak sesuai dengan organisasi."},{status:409});if(!canWriteResourceScope(s,p.data.organizationId,studyProgramId,false))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const x=await db.insert(cooperations).values({...p.data,studyProgramId,lifecycleStatus:"DRAFT"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_COOPERATION",subjectType:"COOPERATION",subjectId:id,after:p.data});return NextResponse.json({id,status:"DRAFT"},{status:201});}
export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patchInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(cooperations).where(eq(cooperations.id,id)).limit(1);if(!before)return NextResponse.json({error:"Kerja sama tidak ditemukan."},{status:404});if(!canWriteResourceScope(s,before.organizationId,before.studyProgramId,false))return NextResponse.json({error:"Forbidden"},{status:403});if(!["DRAFT","SUBMITTED"].includes(before.lifecycleStatus))return NextResponse.json({error:"Record yang sudah disahkan/published tidak diedit in-place."},{status:409});const contentKeys=Object.keys(p.data).filter(k=>k!=="lifecycleStatus");if(before.lifecycleStatus==="SUBMITTED"&&contentKeys.length)return NextResponse.json({error:"SUBMITTED harus kembali DRAFT sebelum isi diubah."},{status:409});await db.update(cooperations).set({...p.data,updatedAt:new Date()}).where(eq(cooperations.id,id));await audit({actorId:s.userId,action:"UPDATE_COOPERATION",subjectType:"COOPERATION",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(cooperations).where(eq(cooperations.id,id)).limit(1);if(!before)return NextResponse.json({error:"Kerja sama tidak ditemukan."},{status:404});if(!canWriteResourceScope(s,before.organizationId,before.studyProgramId,false))return NextResponse.json({error:"Forbidden"},{status:403});if(before.lifecycleStatus!=="DRAFT")return NextResponse.json({error:"Hanya DRAFT yang belum diajukan dapat dihapus permanen."},{status:409});await db.delete(cooperations).where(eq(cooperations.id,id));await audit({actorId:s.userId,action:"DELETE_COOPERATION",subjectType:"COOPERATION",subjectId:id,before,after:null});return NextResponse.json({id,deleted:true});}
