"use client";
import { useState } from "react";

type Row=Record<string,any>;
type Data={plans:Row[];goals:Row[];kpis:Row[];targets:Row[];measurements:Row[];evaluations:Row[];recommendations:Row[];followups:Row[];approvals:Row[];publications:Row[]};
const steps=[{id:"perencanaan",n:"01",title:"Perencanaan",text:"Tetapkan KPI dan target periode."},{id:"pengukuran",n:"02",title:"Pengukuran",text:"Masukkan realisasi; sistem menghitung capaian."},{id:"analisis",n:"03",title:"Analisis Mutu",text:"Catat gap, analisis, temuan, dan rekomendasi."},{id:"approval",n:"04",title:"Approval",text:"Putuskan record submitted secara formal."},{id:"publikasi",n:"05",title:"Publikasi",text:"Terbitkan record approved ke portal publik."}];
async function request(url:string,body:Row){const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Permintaan gagal.");return data;}
const name=(rows:Row[],id:number,field="name")=>rows.find(row=>row.id===id)?.[field]??`#${id}`;

export default function WorkflowConsole({initialData}:{initialData:Data}){
 const[data,setData]=useState(initialData),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const reload=async()=>location.reload();
 const act=async(fn:()=>Promise<any>)=>{setBusy(true);setMessage("");try{const result=await fn();setMessage(`Berhasil: ${result.status??result.decision??"data tersimpan"}. Memuat ulang…`);await reload();}catch(error){setMessage(error instanceof Error?error.message:"Terjadi kesalahan.");setBusy(false)}};
 const kpiOptions=data.kpis.map(k=><option key={k.id} value={k.id}>{k.code} · {k.name}</option>);
 const submittedMeasurements=data.measurements.filter(m=>m.workflowStatus==="SUBMITTED");
 const submittedEvaluations=data.evaluations.filter(e=>e.status==="SUBMITTED");
 const approvedKeys=new Set(data.approvals.filter(a=>a.decision==="APPROVED").map(a=>`${a.subjectType}:${a.subjectId}`));
 const publishedKeys=new Set(data.publications.filter(p=>p.status==="PUBLISHED").map(p=>`${p.subjectType}:${p.subjectId}`));
 const publishReady=[...data.measurements.map(x=>({type:"KPI_MEASUREMENT",id:x.id,label:`Pengukuran ${name(data.kpis,x.kpiId)} · ${x.period}`})),...data.evaluations.map(x=>({type:"EVALUATION",id:x.id,label:`Evaluasi ${x.subjectType} #${x.subjectId} · ${x.period??"-"}`}))].filter(x=>approvedKeys.has(`${x.type}:${x.id}`)&&!publishedKeys.has(`${x.type}:${x.id}`));
 return <>
  <nav className="workflow-steps">{steps.map(step=><a href={`#${step.id}`} key={step.id}><span>{step.n}</span><strong>{step.title}</strong><small>{step.text}</small></a>)}</nav>
  {message&&<div className="workflow-message">{message}</div>}
  <section className="workflow-stage" id="perencanaan"><Stage n="01" title="Perencanaan & target" desc="Renstra dan KPI adalah INPUT. Pilih KPI existing lalu tetapkan target periode."><div className="workflow-stats"><Stat label="Renstra" value={data.plans.length}/><Stat label="Sasaran" value={data.goals.length}/><Stat label="KPI" value={data.kpis.length}/><Stat label="Target" value={data.targets.length}/></div><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>request("/api/internal/kpi-targets",{kpiId:Number(f.get("kpiId")),period:String(f.get("period")),targetValue:Number(f.get("targetValue"))}))}}><Select label="KPI" name="kpiId">{kpiOptions}</Select><Input label="Periode" name="period" defaultValue="2027"/><Input label="Target" name="targetValue" type="number"/><button disabled={busy}>Simpan target</button></form><DataTable rows={data.kpis.map(k=>({kode:k.code,kpi:k.name,status:k.lifecycleStatus}))}/></Stage></section>
  <section className="workflow-stage" id="pengukuran"><Stage n="02" title="Pengukuran & perhitungan" desc="Masukkan realisasi. Backend menghitung persentase capaian dan status terhadap target."><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>request("/api/internal/measurements",{kpiId:Number(f.get("kpiId")),period:String(f.get("period")),actualValue:Number(f.get("actualValue"))}))}}><Select label="KPI" name="kpiId">{kpiOptions}</Select><Input label="Periode target" name="period" defaultValue="2027"/><Input label="Realisasi" name="actualValue" type="number"/><button disabled={busy}>Hitung & submit</button></form><DataTable rows={data.measurements.map(m=>({kpi:name(data.kpis,m.kpiId),periode:m.period,realisasi:m.actualValue,capaian:`${m.achievementPercent??"-"}%`,status:m.workflowStatus}))}/></Stage></section>
  <section className="workflow-stage" id="analisis"><Stage n="03" title="Evaluasi, gap & tindak lanjut" desc="Analisis record submitted, buat rekomendasi, lalu turunkan menjadi action plan."><form className="wide-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>request("/api/internal/evaluations",{subjectType:"KPI_MEASUREMENT",subjectId:Number(f.get("subjectId")),period:String(f.get("period")),standardReference:String(f.get("standardReference")),standardValue:String(f.get("standardValue")),actualValue:String(f.get("actualValue")),gapValue:String(f.get("gapValue")),analysis:String(f.get("analysis")),rootCause:String(f.get("rootCause")),finding:String(f.get("finding")),severity:"MEDIUM",recommendation:String(f.get("recommendation")),priority:"HIGH"}))}}><Select label="Pengukuran submitted" name="subjectId">{submittedMeasurements.map(m=><option key={m.id} value={m.id}>{name(data.kpis,m.kpiId)} · {m.period}</option>)}</Select><Input label="Periode" name="period" defaultValue="2026"/><Input label="Referensi standar" name="standardReference" defaultValue="Target KPI periode"/><Input label="Nilai standar" name="standardValue"/><Input label="Realisasi" name="actualValue"/><Input label="Gap" name="gapValue"/><Textarea label="Analisis" name="analysis"/><Textarea label="Akar masalah" name="rootCause"/><Textarea label="Temuan" name="finding"/><Textarea label="Rekomendasi" name="recommendation"/><button disabled={busy||!submittedMeasurements.length}>Simpan evaluasi</button></form><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(()=>request("/api/internal/followups",{recommendationId:Number(f.get("recommendationId")),actionPlan:String(f.get("actionPlan")),dueDate:String(f.get("dueDate"))}))}}><Select label="Rekomendasi" name="recommendationId">{data.recommendations.filter(r=>r.status==="OPEN").map(r=><option key={r.id} value={r.id}>{r.recommendationText}</option>)}</Select><Input label="Rencana aksi" name="actionPlan"/><Input label="Tenggat" name="dueDate" type="date"/><button disabled={busy}>Buat tindak lanjut</button></form><DataTable rows={data.followups.map(f=>({aksi:f.actionPlan,progress:`${f.progressPercent}%`,status:f.status,tenggat:f.dueDate??"-"}))}/></Stage></section>
  <section className="workflow-stage" id="approval"><Stage n="04" title="Approval formal" desc="Approver memutuskan pengukuran atau evaluasi. Keputusan tercatat di audit trail."><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),raw=String(f.get("subject")).split(":");void act(()=>request("/api/internal/approvals",{subjectType:raw[0],subjectId:Number(raw[1]),decision:String(f.get("decision")),note:String(f.get("note"))}))}}><Select label="Record submitted" name="subject">{submittedMeasurements.map(m=><option key={`m${m.id}`} value={`KPI_MEASUREMENT:${m.id}`}>Pengukuran · {name(data.kpis,m.kpiId)} · {m.period}</option>)}{submittedEvaluations.map(e=><option key={`e${e.id}`} value={`EVALUATION:${e.id}`}>Evaluasi · {e.subjectType} #{e.subjectId}</option>)}</Select><Select label="Keputusan" name="decision"><option value="APPROVED">Setujui</option><option value="REVISION">Minta revisi</option><option value="REJECTED">Tolak</option></Select><Input label="Catatan" name="note"/><button disabled={busy}>Simpan keputusan</button></form><DataTable rows={data.approvals.map(a=>({objek:`${a.subjectType} #${a.subjectId}`,keputusan:a.decision,level:a.approvalLevel}))}/></Stage></section>
  <section className="workflow-stage" id="publikasi"><Stage n="05" title="Publikasi terkontrol" desc="Hanya record approved yang muncul dalam antrean dan dapat diproyeksikan ke portal publik."><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),raw=String(f.get("subject")).split(":");void act(()=>request("/api/internal/publications",{subjectType:raw[0],subjectId:Number(raw[1]),publicTitle:String(f.get("publicTitle")),publicSummary:String(f.get("publicSummary"))}))}}><Select label="Siap dipublikasikan" name="subject">{publishReady.map(x=><option key={`${x.type}:${x.id}`} value={`${x.type}:${x.id}`}>{x.label}</option>)}</Select><Input label="Judul publik" name="publicTitle"/><Textarea label="Ringkasan publik" name="publicSummary"/><button disabled={busy||!publishReady.length}>Publikasikan</button></form><DataTable rows={data.publications.map(p=>({objek:`${p.subjectType} #${p.subjectId}`,judul:p.publicTitle??"-",status:p.status}))}/></Stage></section>
 </>;
}
function Stage({n,title,desc,children}:{n:string;title:string;desc:string;children:React.ReactNode}){return <div className="stage-card"><header><span>{n}</span><div><h2>{title}</h2><p>{desc}</p></div></header>{children}</div>}
function Stat({label,value}:{label:string;value:number}){return <div><strong>{value}</strong><span>{label}</span></div>}
function Input({label,name,type="text",defaultValue}:{label:string;name:string;type?:string;defaultValue?:string}){return <label><span>{label}</span><input required name={name} type={type} defaultValue={defaultValue}/></label>}
function Textarea({label,name}:{label:string;name:string}){return <label><span>{label}</span><textarea required name={name}/></label>}
function Select({label,name,children}:{label:string;name:string;children:React.ReactNode}){return <label><span>{label}</span><select required name={name}>{children}</select></label>}
function DataTable({rows}:{rows:Row[]}){if(!rows.length)return <p className="empty-row">Belum ada data.</p>;const cols=Object.keys(rows[0]);return <div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.slice(0,8).map((row,i)=><tr key={i}>{cols.map(c=><td key={c}>{String(row[c]??"-")}</td>)}</tr>)}</tbody></table></div>}
