import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { laboratoryK3lChecks } from "@/src/db/schema-phase6";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { can } from "@/src/lib/rbac";
import { governanceWriteAllows } from "@/src/services/governance-scope";
import { canReadResourceScope,canWriteResourceScope,getLaboratoryScope } from "@/src/services/resource-scope";
const createInput=z.object({laboratoryId:z.number().int().positive(),checkDate:z.string().min(8).max(20),score:z.number().min(0).max(100).optional(),checklist:z.unknown().optional(),findings:z.string().optional(),correctiveAction:z.string().optional()});
const patchInput=z.object({checkDate:z.string().min(8).max(20).optional(),score:z.number().min(0).max(100).nullable().optional(),checklist:z.unknown().optional(),findings:z.string().nullable().optional(),correctiveAction:z.string().nullable().optional(),status:z.enum(["DRAFT","VERIFIED","CLOSED","ARCHIVED"]).optional()});
function idParam(req:Request,key="id"){const n=Number(new URL(req.url).searchParams.get(key));return Number.isInteger(n)&&n>0?n:null;}
function canInspect(user:NonNullable<Awaited<ReturnType<typeof getSession>>>,organizationId:number){return canWriteResourceScope(user,organizationId,null,true)||(can(user,"evaluation.create")&&governanceWriteAllows(user,organizationId,null));}
export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const laboratoryId=idParam(req,"laboratoryId");const db=requireDb();const rows=laboratoryId?await db.select().from(laboratoryK3lChecks).where(eq(laboratoryK3lChecks.laboratoryId,laboratoryId)):await db.select().from(laboratoryK3lChecks);const allowed=[];for(const row of rows){const lab=await getLaboratoryScope(row.laboratoryId);if(lab&&(canReadResourceScope(s,lab.organizationId,null)||can(s,"quality.read")))allowed.push(row);}return NextResponse.json(allowed);}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const p=createInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const lab=await getLaboratoryScope(p.data.laboratoryId);if(!lab)return NextResponse.json({error:"Laboratorium tidak ditemukan."},{status:404});if(!canInspect(s,lab.organizationId))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const x=await db.insert(laboratoryK3lChecks).values({laboratoryId:p.data.laboratoryId,checkDate:p.data.checkDate,score:p.data.score?.toString(),checklist:p.data.checklist,findings:p.data.findings,correctiveAction:p.data.correctiveAction,evaluatorId:s.userId,status:"DRAFT"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_K3L_CHECK",subjectType:"LAB_K3L",subjectId:id,after:p.data});return NextResponse.json({id,status:"DRAFT"},{status:201});}
export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patchInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(laboratoryK3lChecks).where(eq(laboratoryK3lChecks.id,id)).limit(1);if(!before)return NextResponse.json({error:"Record tidak ditemukan."},{status:404});const lab=await getLaboratoryScope(before.laboratoryId);if(!lab||!canInspect(s,lab.organizationId))return NextResponse.json({error:"Forbidden"},{status:403});const update={...p.data,score:p.data.score===undefined?undefined:p.data.score===null?null:p.data.score.toString(),updatedAt:new Date()};await db.update(laboratoryK3lChecks).set(update).where(eq(laboratoryK3lChecks.id,id));await audit({actorId:s.userId,action:"UPDATE_K3L_CHECK",subjectType:"LAB_K3L",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(laboratoryK3lChecks).where(eq(laboratoryK3lChecks.id,id)).limit(1);if(!before)return NextResponse.json({error:"Record tidak ditemukan."},{status:404});const lab=await getLaboratoryScope(before.laboratoryId);if(!lab||!canInspect(s,lab.organizationId))return NextResponse.json({error:"Forbidden"},{status:403});await db.update(laboratoryK3lChecks).set({status:"ARCHIVED",updatedAt:new Date()}).where(eq(laboratoryK3lChecks.id,id));await audit({actorId:s.userId,action:"ARCHIVE_K3L_CHECK",subjectType:"LAB_K3L",subjectId:id,before,after:{status:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
