import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { laboratoryProfiles } from "@/src/db/schema-phase6";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { canReadResourceScope,canWriteResourceScope,getLaboratoryScope } from "@/src/services/resource-scope";

const createInput=z.object({laboratoryId:z.number().int().positive(),name:z.string().min(2).max(255),description:z.string().optional(),location:z.string().max(500).optional(),picUserId:z.number().int().positive().nullable().optional()});
const patchInput=z.object({name:z.string().min(2).max(255).optional(),description:z.string().nullable().optional(),location:z.string().max(500).nullable().optional(),picUserId:z.number().int().positive().nullable().optional(),lifecycleStatus:z.enum(["DRAFT","SUBMITTED","ARCHIVED"]).optional()});
function idParam(req:Request,key="id"){const n=Number(new URL(req.url).searchParams.get(key));return Number.isInteger(n)&&n>0?n:null;}

export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const laboratoryId=idParam(req,"laboratoryId");if(!laboratoryId)return NextResponse.json({error:"laboratoryId wajib."},{status:400});const lab=await getLaboratoryScope(laboratoryId);if(!lab||!canReadResourceScope(s,lab.organizationId,null))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();return NextResponse.json(await db.select().from(laboratoryProfiles).where(eq(laboratoryProfiles.laboratoryId,laboratoryId)));}

export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const p=createInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const lab=await getLaboratoryScope(p.data.laboratoryId);if(!lab)return NextResponse.json({error:"Laboratorium tidak ditemukan."},{status:404});if(!canWriteResourceScope(s,lab.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const rows=await db.select({versionNumber:laboratoryProfiles.versionNumber,lifecycleStatus:laboratoryProfiles.lifecycleStatus}).from(laboratoryProfiles).where(eq(laboratoryProfiles.laboratoryId,p.data.laboratoryId));if(rows.some(x=>x.lifecycleStatus==="DRAFT"||x.lifecycleStatus==="SUBMITTED"))return NextResponse.json({error:"Masih ada versi profil DRAFT/SUBMITTED yang harus diselesaikan lebih dahulu."},{status:409});const versionNumber=rows.length?Math.max(...rows.map(x=>x.versionNumber))+1:1;const x=await db.insert(laboratoryProfiles).values({...p.data,picUserId:p.data.picUserId??null,versionNumber,lifecycleStatus:"DRAFT"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_LABORATORY_PROFILE_VERSION",subjectType:"LABORATORY_PROFILE",subjectId:id,after:{...p.data,versionNumber}});return NextResponse.json({id,versionNumber,status:"DRAFT"},{status:201});}

export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patchInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(laboratoryProfiles).where(eq(laboratoryProfiles.id,id)).limit(1);if(!before)return NextResponse.json({error:"Profil tidak ditemukan."},{status:404});const lab=await getLaboratoryScope(before.laboratoryId);if(!lab||!canWriteResourceScope(s,lab.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});if(!["DRAFT","SUBMITTED"].includes(before.lifecycleStatus))return NextResponse.json({error:"Profil yang sudah disahkan/published harus direvisi sebagai versi baru."},{status:409});const contentKeys=Object.keys(p.data).filter(k=>k!=="lifecycleStatus");if(before.lifecycleStatus==="SUBMITTED"&&contentKeys.length)return NextResponse.json({error:"Profil SUBMITTED harus dikembalikan ke DRAFT sebelum isi diubah."},{status:409});await db.update(laboratoryProfiles).set({...p.data,updatedAt:new Date()}).where(eq(laboratoryProfiles.id,id));await audit({actorId:s.userId,action:"UPDATE_LABORATORY_PROFILE",subjectType:"LABORATORY_PROFILE",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}

export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(laboratoryProfiles).where(eq(laboratoryProfiles.id,id)).limit(1);if(!before)return NextResponse.json({error:"Profil tidak ditemukan."},{status:404});const lab=await getLaboratoryScope(before.laboratoryId);if(!lab||!canWriteResourceScope(s,lab.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});if(before.lifecycleStatus!=="DRAFT")return NextResponse.json({error:"Hanya versi DRAFT yang dapat diarsipkan langsung."},{status:409});await db.update(laboratoryProfiles).set({lifecycleStatus:"ARCHIVED",updatedAt:new Date()}).where(eq(laboratoryProfiles.id,id));await audit({actorId:s.userId,action:"ARCHIVE_LABORATORY_PROFILE",subjectType:"LABORATORY_PROFILE",subjectId:id,before,after:{lifecycleStatus:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
