import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { newsArticles,newsCategories } from "@/src/db/schema-admin";
import { getSession } from "@/src/lib/auth";
import { can,scopeAllows } from "@/src/lib/rbac";
import { audit } from "@/src/lib/audit";

const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const input=z.object({organizationId:z.number().int().positive(),categoryId:z.number().int().positive().nullable().optional(),title:z.string().min(3).max(500),slug:z.string().max(550).optional(),excerpt:z.string().max(2000).optional(),body:z.string().min(1),coverImageUrl:z.string().url().optional().or(z.literal("")),featured:z.boolean().optional()});
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!["news.manage","approval.final","publication.execute"].some(p=>can(s,p)))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();return NextResponse.json(await db.select({id:newsArticles.id,organizationId:newsArticles.organizationId,categoryId:newsArticles.categoryId,category:newsCategories.name,title:newsArticles.title,slug:newsArticles.slug,excerpt:newsArticles.excerpt,lifecycleStatus:newsArticles.lifecycleStatus,featured:newsArticles.featured,authorId:newsArticles.authorId,createdAt:newsArticles.createdAt,updatedAt:newsArticles.updatedAt,publishedAt:newsArticles.publishedAt}).from(newsArticles).leftJoin(newsCategories,eq(newsArticles.categoryId,newsCategories.id)));}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"news.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const p=input.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});if(!scopeAllows(s,p.data.organizationId))return NextResponse.json({error:"Scope organisasi tidak sesuai."},{status:403});const db=requireDb();const slug=slugify(p.data.slug||p.data.title);const[existing]=await db.select({id:newsArticles.id}).from(newsArticles).where(eq(newsArticles.slug,slug)).limit(1);if(existing)return NextResponse.json({error:"Slug berita sudah digunakan."},{status:409});const x=await db.insert(newsArticles).values({organizationId:p.data.organizationId,categoryId:p.data.categoryId??null,title:p.data.title,slug,excerpt:p.data.excerpt,body:p.data.body,coverImageUrl:p.data.coverImageUrl||null,featured:p.data.featured??false,authorId:s.userId,lifecycleStatus:"DRAFT"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_NEWS_ARTICLE",subjectType:"NEWS_ARTICLE",subjectId:id,after:{organizationId:p.data.organizationId,categoryId:p.data.categoryId,title:p.data.title,slug}});return NextResponse.json({id,slug,status:"DRAFT"},{status:201});}
