import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { accreditationAgencies } from "@/src/db/schema-accreditation";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { can } from "@/src/lib/rbac";

const createInput=z.object({code:z.string().min(2).max(80),name:z.string().min(2).max(255),agencyType:z.string().min(2).max(40).default("LAM"),websiteUrl:z.string().url().optional()});
const patchInput=z.object({name:z.string().min(2).max(255).optional(),agencyType:z.string().min(2).max(40).optional(),websiteUrl:z.string().url().nullable().optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional()});
function idFrom(req:Request){const id=Number(new URL(req.url).searchParams.get("id"));return Number.isInteger(id)&&id>0?id:null;}

export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.read"))return NextResponse.json({error:"Forbidden"},{status:403});return NextResponse.json(await requireDb().select().from(accreditationAgencies));}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.framework.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const p=createInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const code=p.data.code.trim().toUpperCase();const[found]=await db.select({id:accreditationAgencies.id}).from(accreditationAgencies).where(eq(accreditationAgencies.code,code)).limit(1);if(found)return NextResponse.json({error:"Kode lembaga sudah digunakan."},{status:409});const x=await db.insert(accreditationAgencies).values({...p.data,code,status:"ACTIVE"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_ACCREDITATION_AGENCY",subjectType:"ACCREDITATION_AGENCY",subjectId:id,after:{...p.data,code}});return NextResponse.json({id,code,status:"ACTIVE"},{status:201});}
export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.framework.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const id=idFrom(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patchInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(accreditationAgencies).where(eq(accreditationAgencies.id,id)).limit(1);if(!before)return NextResponse.json({error:"Lembaga tidak ditemukan."},{status:404});await db.update(accreditationAgencies).set({...p.data,updatedAt:new Date()}).where(eq(accreditationAgencies.id,id));await audit({actorId:s.userId,action:"UPDATE_ACCREDITATION_AGENCY",subjectType:"ACCREDITATION_AGENCY",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.framework.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const id=idFrom(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(accreditationAgencies).where(eq(accreditationAgencies.id,id)).limit(1);if(!before)return NextResponse.json({error:"Lembaga tidak ditemukan."},{status:404});await db.update(accreditationAgencies).set({status:"ARCHIVED",updatedAt:new Date()}).where(eq(accreditationAgencies.id,id));await audit({actorId:s.userId,action:"ARCHIVE_ACCREDITATION_AGENCY",subjectType:"ACCREDITATION_AGENCY",subjectId:id,before,after:{status:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
