import { and,eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { studentAnnualStats } from "@/src/db/schema-phase6";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { canReadResourceScope,canWriteResourceScope,getProgramScope } from "@/src/services/resource-scope";
const createInput=z.object({studyProgramId:z.number().int().positive(),academicYear:z.string().min(4).max(20),activeStudents:z.number().int().nonnegative().default(0),newStudents:z.number().int().nonnegative().default(0),graduates:z.number().int().nonnegative().default(0),dropoutStudents:z.number().int().nonnegative().default(0)});
const patchInput=createInput.omit({studyProgramId:true,academicYear:true}).partial().extend({lifecycleStatus:z.enum(["DRAFT","SUBMITTED","ARCHIVED"]).optional()});
function idParam(req:Request){const n=Number(new URL(req.url).searchParams.get("id"));return Number.isInteger(n)&&n>0?n:null;}
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const db=requireDb();const rows=await db.select().from(studentAnnualStats);const allowed=[];for(const row of rows){const program=await getProgramScope(row.studyProgramId);if(program&&canReadResourceScope(s,program.organizationId,row.studyProgramId))allowed.push(row);}return NextResponse.json(allowed);}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const p=createInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const program=await getProgramScope(p.data.studyProgramId);if(!program||program.status!=="ACTIVE")return NextResponse.json({error:"Program Studi tidak ditemukan/aktif."},{status:404});if(!canWriteResourceScope(s,program.organizationId,p.data.studyProgramId,false))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const[existing]=await db.select({id:studentAnnualStats.id}).from(studentAnnualStats).where(and(eq(studentAnnualStats.studyProgramId,p.data.studyProgramId),eq(studentAnnualStats.academicYear,p.data.academicYear))).limit(1);if(existing)return NextResponse.json({error:"Statistik tahun akademik tersebut sudah ada."},{status:409});const x=await db.insert(studentAnnualStats).values({...p.data,lifecycleStatus:"DRAFT"});const id=Number(x[0].insertId);await audit({actorId:s.userId,action:"CREATE_STUDENT_STAT",subjectType:"STUDENT_ANNUAL_STAT",subjectId:id,after:p.data});return NextResponse.json({id,status:"DRAFT"},{status:201});}
export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patchInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(studentAnnualStats).where(eq(studentAnnualStats.id,id)).limit(1);if(!before)return NextResponse.json({error:"Statistik tidak ditemukan."},{status:404});const program=await getProgramScope(before.studyProgramId);if(!program||!canWriteResourceScope(s,program.organizationId,before.studyProgramId,false))return NextResponse.json({error:"Forbidden"},{status:403});if(!["DRAFT","SUBMITTED"].includes(before.lifecycleStatus))return NextResponse.json({error:"Statistik yang sudah disahkan/published tidak diedit in-place."},{status:409});const contentKeys=Object.keys(p.data).filter(k=>k!=="lifecycleStatus");if(before.lifecycleStatus==="SUBMITTED"&&contentKeys.length)return NextResponse.json({error:"SUBMITTED harus kembali DRAFT sebelum data diubah."},{status:409});await db.update(studentAnnualStats).set({...p.data,updatedAt:new Date()}).where(eq(studentAnnualStats.id,id));await audit({actorId:s.userId,action:"UPDATE_STUDENT_STAT",subjectType:"STUDENT_ANNUAL_STAT",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=idParam(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(studentAnnualStats).where(eq(studentAnnualStats.id,id)).limit(1);if(!before)return NextResponse.json({error:"Statistik tidak ditemukan."},{status:404});const program=await getProgramScope(before.studyProgramId);if(!program||!canWriteResourceScope(s,program.organizationId,before.studyProgramId,false))return NextResponse.json({error:"Forbidden"},{status:403});if(before.lifecycleStatus!=="DRAFT")return NextResponse.json({error:"Hanya DRAFT yang dapat diarsipkan langsung."},{status:409});await db.update(studentAnnualStats).set({lifecycleStatus:"ARCHIVED",updatedAt:new Date()}).where(eq(studentAnnualStats.id,id));await audit({actorId:s.userId,action:"ARCHIVE_STUDENT_STAT",subjectType:"STUDENT_ANNUAL_STAT",subjectId:id,before,after:{lifecycleStatus:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
