import {requireDb} from "../src/db";
import {organizations,roles,studyPrograms,userRoles,users} from "../src/db/schema";
import {federatedApplications} from "../src/db/schema-admin";
import {accreditationAgencies,accreditationAssessments,accreditationCriteria,accreditationEvidenceRequirements,accreditationFrameworks,accreditationIndicatorMandates,accreditationIndicators,accreditationIndicatorVariables,accreditationScoringRubrics,studyProgramAccreditationFrameworks} from "../src/db/schema-accreditation";
import {accreditationIndicatorModuleSources,evaluationModules,evaluationModuleSnapshots,evaluationPeriods} from "../src/db/schema-evaluation-modules";
type Problem={relation:string;count:number};
function missing<T extends Record<string,any>>(rows:T[],foreignKey:keyof T,parents:Set<number>){return rows.filter(row=>row[foreignKey]!=null&&!parents.has(Number(row[foreignKey]))).length;}
async function main(){
 const db=requireDb();
 const[orgs,programs,userRows,roleRows,grants,agencies,frameworks,criteria,indicators,variables,rubrics,evidence,assignments,mandates,assessments,federated,modules,moduleSnapshots,moduleSources,periodRows]=await Promise.all([db.select().from(organizations),db.select().from(studyPrograms),db.select().from(users),db.select().from(roles),db.select().from(userRoles),db.select().from(accreditationAgencies),db.select().from(accreditationFrameworks),db.select().from(accreditationCriteria),db.select().from(accreditationIndicators),db.select().from(accreditationIndicatorVariables),db.select().from(accreditationScoringRubrics),db.select().from(accreditationEvidenceRequirements),db.select().from(studyProgramAccreditationFrameworks),db.select().from(accreditationIndicatorMandates),db.select().from(accreditationAssessments),db.select().from(federatedApplications),db.select().from(evaluationModules),db.select().from(evaluationModuleSnapshots),db.select().from(accreditationIndicatorModuleSources),db.select().from(evaluationPeriods)]);
 const ids=(rows:Array<{id:number}>)=>new Set(rows.map(row=>row.id));
 const problems:Problem[]=[
  {relation:"study_programs.organization_id",count:missing(programs,"organizationId",ids(orgs))},{relation:"user_roles.user_id",count:missing(grants,"userId",ids(userRows))},{relation:"user_roles.role_id",count:missing(grants,"roleId",ids(roleRows))},{relation:"user_roles.organization_id",count:missing(grants,"organizationId",ids(orgs))},{relation:"frameworks.agency_id",count:missing(frameworks,"agencyId",ids(agencies))},{relation:"criteria.framework_id",count:missing(criteria,"frameworkId",ids(frameworks))},{relation:"indicators.framework_id",count:missing(indicators,"frameworkId",ids(frameworks))},{relation:"indicators.criterion_id",count:missing(indicators,"criterionId",ids(criteria))},{relation:"variables.indicator_id",count:missing(variables,"indicatorId",ids(indicators))},{relation:"rubrics.indicator_id",count:missing(rubrics,"indicatorId",ids(indicators))},{relation:"evidence.indicator_id",count:missing(evidence,"indicatorId",ids(indicators))},{relation:"assignments.study_program_id",count:missing(assignments,"studyProgramId",ids(programs))},{relation:"assignments.framework_id",count:missing(assignments,"frameworkId",ids(frameworks))},{relation:"indicator_mandates.assignment_id",count:missing(mandates,"assignmentId",ids(assignments))},{relation:"indicator_mandates.indicator_id",count:missing(mandates,"indicatorId",ids(indicators))},{relation:"indicator_mandates.assigned_by",count:missing(mandates,"assignedBy",ids(userRows))},{relation:"assessments.assignment_id",count:missing(assessments,"assignmentId",ids(assignments))},{relation:"assessments.indicator_id",count:missing(assessments,"indicatorId",ids(indicators))},{relation:"module_snapshots.module_id",count:missing(moduleSnapshots,"moduleId",ids(modules))},{relation:"module_snapshots.organization_id",count:missing(moduleSnapshots,"organizationId",ids(orgs))},{relation:"evaluation_periods.organization_id",count:missing(periodRows,"organizationId",ids(orgs))},{relation:"evaluation_periods.created_by",count:missing(periodRows,"createdBy",ids(userRows))},{relation:"module_sources.module_id",count:missing(moduleSources,"moduleId",ids(modules))},{relation:"module_sources.framework_id",count:missing(moduleSources,"frameworkId",ids(frameworks))},{relation:"module_sources.indicator_id",count:missing(moduleSources,"indicatorId",ids(indicators))}
 ];
 const orphaned=problems.filter(problem=>problem.count>0);
 const periodKeys=new Set(periodRows.map(row=>`${row.organizationId}:${row.label}`)),snapshotWithoutPeriod=moduleSnapshots.filter(row=>!periodKeys.has(`${row.organizationId}:${row.period}`)).length,legacyMandates=mandates.filter(row=>row.period==="LEGACY").length,activeFrameworkIds=new Set(assignments.filter(row=>row.assignmentStatus==="ACTIVE").map(row=>row.frameworkId)),inactiveIndicators=indicators.filter(row=>!activeFrameworkIds.has(row.frameworkId)).length,warnings=[...(legacyMandates?[{code:"LEGACY_MANDATES",count:legacyMandates,message:"Mandat lama belum dipindahkan ke periode evaluasi."}]:[]),...(snapshotWithoutPeriod?[{code:"SNAPSHOT_WITHOUT_PERIOD",count:snapshotWithoutPeriod,message:"Ringkasan modul tidak mempunyai periode resmi."}]:[]),...(inactiveIndicators?[{code:"INDICATORS_OUTSIDE_ACTIVE_ASSIGNMENT",count:inactiveIndicators,message:"Indikator tersimpan pada template yang tidak lagi ditugaskan."}]:[]),...(!moduleSources.length?[{code:"MODULE_SOURCES_EMPTY",count:0,message:"Belum ada indikator yang dipetakan ke modul evaluasi."}]:[])];
 console.log(JSON.stringify({status:orphaned.length?"PROBLEMS_FOUND":warnings.length?"CLEAN_WITH_WARNINGS":"CLEAN",counts:{organizations:orgs.length,activeOrganizations:orgs.filter(row=>row.status==="ACTIVE").length,studyPrograms:programs.length,users:userRows.length,roles:roleRows.length,frameworks:frameworks.length,indicators:indicators.length,indicatorsOnActiveAssignments:indicators.length-inactiveIndicators,indicatorMandates:mandates.length,legacyMandates,evaluationPeriods:periodRows.length,evaluationModules:modules.length,moduleSnapshots:moduleSnapshots.length,moduleSnapshotsWithoutPeriod:snapshotWithoutPeriod,indicatorModuleSources:moduleSources.length,variables:variables.length,rubrics:rubrics.length,assessments:assessments.length,federatedApplications:federated.length},warnings,orphanedRelations:orphaned},null,2));process.exit(orphaned.length?1:0);
}
main().catch(error=>{console.error(error);process.exit(1)});
