import { hash } from "bcryptjs";
import { and,eq } from "drizzle-orm";
import { requireDb } from "../src/db";
import { organizations,roles,studyPrograms,userRoles,users } from "../src/db/schema";

async function upsertUser(input:{name:string;email:string;password:string;roleCode:string;organizationId:number;studyProgramId:number|null}){
  const db=requireDb();const[role]=await db.select().from(roles).where(eq(roles.code,input.roleCode)).limit(1);if(!role)throw new Error(`Role ${input.roleCode} belum tersedia.`);let[user]=await db.select().from(users).where(eq(users.email,input.email)).limit(1);const passwordHash=await hash(input.password,12);if(!user){const result=await db.insert(users).values({name:input.name,email:input.email,passwordHash,status:"ACTIVE"});[user]=await db.select().from(users).where(eq(users.id,Number(result[0].insertId))).limit(1);}else await db.update(users).set({name:input.name,passwordHash,status:"ACTIVE"}).where(eq(users.id,user.id));const[grant]=await db.select().from(userRoles).where(and(eq(userRoles.userId,user.id),eq(userRoles.roleId,role.id))).limit(1);if(grant){await db.delete(userRoles).where(and(eq(userRoles.userId,grant.userId),eq(userRoles.roleId,grant.roleId),eq(userRoles.organizationId,grant.organizationId)));await db.insert(userRoles).values({userId:user.id,roleId:role.id,organizationId:input.organizationId,studyProgramId:input.studyProgramId});}else await db.insert(userRoles).values({userId:user.id,roleId:role.id,organizationId:input.organizationId,studyProgramId:input.studyProgramId});
}

async function main(){const db=requireDb();const[organization]=await db.select().from(organizations).where(eq(organizations.code,"KEMARITIMAN")).limit(1),[program]=await db.select().from(studyPrograms).where(eq(studyPrograms.code,"D3-NAUTIKA")).limit(1);if(!organization||!program)throw new Error("Jalankan db:seed terlebih dahulu.");await upsertUser({name:"CONTOH - Kaprodi D3 Nautika",email:process.env.DEMO_KAPRODI_EMAIL??"kaprodi.nautika@local.test",password:process.env.DEMO_KAPRODI_PASSWORD??"Kaprodi123!",roleCode:"KAPRODI",organizationId:organization.id,studyProgramId:program.id});await upsertUser({name:"CONTOH - Ketua Jurusan Kemaritiman",email:process.env.DEMO_KAJUR_EMAIL??"kajur.kemaritiman@local.test",password:process.env.DEMO_KAJUR_PASSWORD??"Kajur123!",roleCode:"KAJUR",organizationId:organization.id,studyProgramId:null});console.log("Akun simulasi Kaprodi dan Kajur siap.");}
main().then(()=>process.exit(0)).catch(error=>{console.error(error);process.exit(1)});
