import { and, eq } from "drizzle-orm";
import { requireDb } from "../src/db";
import { evaluations, followups, kpiMeasurements, kpis, kpiTargets, recommendations, strategicGoals, strategicPlans, strategicStatements, studyPrograms, users } from "../src/db/schema";
import { cpl, curricula, graduateProfiles } from "../src/db/schema-phase5";
import { communityServiceProjects, cooperations, graduateOutcomeStats, laboratoryEquipment, laboratoryK3lChecks, laboratoryProfiles, laboratoryUsage, laboratories, personnel, researchProjects, studentAnnualStats } from "../src/db/schema-phase6";
import { accreditationFrameworks, studyProgramAccreditationFrameworks } from "../src/db/schema-accreditation";

const YEAR = 2026;
const PERIOD = "2026";

async function main() {
  const db = requireDb();
  const [admin] = process.env.BOOTSTRAP_ADMIN_EMAIL
    ? await db.select().from(users).where(eq(users.email, process.env.BOOTSTRAP_ADMIN_EMAIL)).limit(1)
    : await db.select().from(users).limit(1);
  if (!admin) throw new Error("Bootstrap admin terlebih dahulu sebelum menjalankan seed demo.");
  const [program] = await db.select().from(studyPrograms).where(eq(studyPrograms.code, "D3-NAUTIKA")).limit(1);
  if (!program) throw new Error("Foundation seed belum dijalankan.");

  let [plan] = await db.select().from(strategicPlans).where(eq(strategicPlans.title, "CONTOH - Renstra UPPS 2025-2029")).limit(1);
  if (!plan) { const result = await db.insert(strategicPlans).values({ organizationId: program.organizationId, title: "CONTOH - Renstra UPPS 2025-2029", periodStart: 2025, periodEnd: 2029, lifecycleStatus: "EFFECTIVE", effectiveFrom: new Date("2025-01-01") }); [plan] = await db.select().from(strategicPlans).where(eq(strategicPlans.id, Number(result[0].insertId))).limit(1); }
  const [vision] = await db.select().from(strategicStatements).where(and(eq(strategicStatements.planId, plan.id), eq(strategicStatements.code, "CONTOH-VISI"))).limit(1);
  if (!vision) await db.insert(strategicStatements).values({ organizationId: program.organizationId, planId: plan.id, statementType: "VISION", code: "CONTOH-VISI", statement: "CONTOH - Menjadi UPPS kemaritiman terapan yang unggul, aman, dan relevan dengan industri.", lifecycleStatus: "EFFECTIVE", effectiveFrom: new Date("2025-01-01") });
  let [goal] = await db.select().from(strategicGoals).where(and(eq(strategicGoals.planId, plan.id), eq(strategicGoals.code, "CONTOH-SS1"))).limit(1);
  if (!goal) { const result = await db.insert(strategicGoals).values({ planId: plan.id, organizationId: program.organizationId, code: "CONTOH-SS1", title: "CONTOH - Meningkatkan mutu pembelajaran dan relevansi lulusan", lifecycleStatus: "EFFECTIVE" }); [goal] = await db.select().from(strategicGoals).where(eq(strategicGoals.id, Number(result[0].insertId))).limit(1); }
  let [kpi] = await db.select().from(kpis).where(eq(kpis.code, "CONTOH-KPI-01")).limit(1);
  if (!kpi) { const result = await db.insert(kpis).values({ strategicGoalId: goal.id, ownerOrganizationId: program.organizationId, code: "CONTOH-KPI-01", name: "CONTOH - Persentase lulusan bekerja sesuai bidang", definition: "Persentase lulusan terlacak yang bekerja pada bidang relevan.", formula: "Lulusan relevan / lulusan terlacak x 100", unit: "%", lifecycleStatus: "EFFECTIVE" }); [kpi] = await db.select().from(kpis).where(eq(kpis.id, Number(result[0].insertId))).limit(1); }
  if (!(await db.select().from(kpiTargets).where(and(eq(kpiTargets.kpiId, kpi.id), eq(kpiTargets.period, PERIOD))).limit(1))[0]) await db.insert(kpiTargets).values({ kpiId: kpi.id, period: PERIOD, targetValue: "80" });
  if (!(await db.select().from(kpiMeasurements).where(and(eq(kpiMeasurements.kpiId, kpi.id), eq(kpiMeasurements.period, PERIOD))).limit(1))[0]) await db.insert(kpiMeasurements).values({ kpiId: kpi.id, period: PERIOD, actualValue: "76", achievementPercent: "95", status: "NEAR_TARGET", workflowStatus: "SUBMITTED", measuredBy: admin.id });

  let [curriculum] = await db.select().from(curricula).where(and(eq(curricula.studyProgramId, program.id), eq(curricula.code, "CONTOH-KUR-2025"))).limit(1);
  if (!curriculum) { const result = await db.insert(curricula).values({ studyProgramId: program.id, code: "CONTOH-KUR-2025", title: "CONTOH - Kurikulum D3 Nautika 2025", versionNumber: 1, academicYearStart: 2025, academicYearEnd: 2029, totalCredits: "110", description: "Data demonstrasi untuk simulasi pengelolaan kurikulum OBE.", lifecycleStatus: "EFFECTIVE", effectiveFrom: new Date("2025-08-01") }); [curriculum] = await db.select().from(curricula).where(eq(curricula.id, Number(result[0].insertId))).limit(1); }
  if (!(await db.select().from(graduateProfiles).where(and(eq(graduateProfiles.curriculumId, curriculum.id), eq(graduateProfiles.code, "CONTOH-PL01"))).limit(1))[0]) await db.insert(graduateProfiles).values({ curriculumId: curriculum.id, code: "CONTOH-PL01", description: "Perwira pelayaran yang kompeten, profesional, dan berbudaya keselamatan." });
  if (!(await db.select().from(cpl).where(and(eq(cpl.curriculumId, curriculum.id), eq(cpl.code, "CONTOH-CPL01"))).limit(1))[0]) await db.insert(cpl).values({ curriculumId: curriculum.id, code: "CONTOH-CPL01", category: "KETERAMPILAN_KHUSUS", description: "Mampu melaksanakan navigasi dan operasi kapal sesuai prosedur keselamatan." });

  let [lab] = await db.select().from(laboratories).where(and(eq(laboratories.organizationId, program.organizationId), eq(laboratories.code, "CONTOH-LAB-NAV"))).limit(1);
  if (!lab) { const result = await db.insert(laboratories).values({ organizationId: program.organizationId, code: "CONTOH-LAB-NAV", operationalStatus: "ACTIVE" }); [lab] = await db.select().from(laboratories).where(eq(laboratories.id, Number(result[0].insertId))).limit(1); }
  if (!(await db.select().from(laboratoryProfiles).where(and(eq(laboratoryProfiles.laboratoryId, lab.id), eq(laboratoryProfiles.versionNumber, 1))).limit(1))[0]) await db.insert(laboratoryProfiles).values({ laboratoryId: lab.id, versionNumber: 1, name: "CONTOH - Laboratorium Simulator Navigasi", description: "Laboratorium demonstrasi untuk pembelajaran navigasi dan bridge resource management.", location: "Gedung Laboratorium - Lantai 2", picUserId: admin.id, lifecycleStatus: "APPROVED", effectiveFrom: "2026-01-01" });
  let [equipment] = await db.select().from(laboratoryEquipment).where(and(eq(laboratoryEquipment.laboratoryId, lab.id), eq(laboratoryEquipment.assetCode, "CONTOH-EQ-001"))).limit(1);
  if (!equipment) { const result = await db.insert(laboratoryEquipment).values({ laboratoryId: lab.id, assetCode: "CONTOH-EQ-001", name: "CONTOH - Bridge Navigation Simulator", category: "SIMULATOR", quantity: 1, unit: "unit", conditionStatus: "GOOD", acquisitionYear: 2024 }); [equipment] = await db.select().from(laboratoryEquipment).where(eq(laboratoryEquipment.id, Number(result[0].insertId))).limit(1); }
  if (!(await db.select().from(laboratoryUsage).where(and(eq(laboratoryUsage.laboratoryId, lab.id), eq(laboratoryUsage.title, "CONTOH - Praktik Bridge Resource Management"))).limit(1))[0]) await db.insert(laboratoryUsage).values({ laboratoryId: lab.id, studyProgramId: program.id, activityType: "PRACTICUM", title: "CONTOH - Praktik Bridge Resource Management", usageDate: "2026-08-10", participantCount: 24, durationHours: "4", recordedBy: admin.id });
  if (!(await db.select().from(laboratoryK3lChecks).where(and(eq(laboratoryK3lChecks.laboratoryId, lab.id), eq(laboratoryK3lChecks.checkDate, "2026-08-01"))).limit(1))[0]) await db.insert(laboratoryK3lChecks).values({ laboratoryId: lab.id, checkDate: "2026-08-01", score: "88", checklist: { emergencyExit: true, fireExtinguisher: true, briefing: true }, findings: "CONTOH - Label jalur evakuasi perlu diperbarui.", correctiveAction: "CONTOH - Penggantian label dijadwalkan bulan berjalan.", evaluatorId: admin.id, status: "SUBMITTED" });

  let [person] = await db.select().from(personnel).where(eq(personnel.employeeCode, "CONTOH-DOSEN-001")).limit(1);
  if (!person) { const result = await db.insert(personnel).values({ organizationId: program.organizationId, studyProgramId: program.id, personnelType: "LECTURER", employeeCode: "CONTOH-DOSEN-001", name: "CONTOH - Dr. Budi Santoso", academicRank: "Lektor", educationLevel: "S3", expertise: "Keselamatan dan Navigasi Maritim" }); [person] = await db.select().from(personnel).where(eq(personnel.id, Number(result[0].insertId))).limit(1); }
  if (!(await db.select().from(researchProjects).where(eq(researchProjects.title, "CONTOH - Sistem Peringatan Dini Keselamatan Pelayaran")).limit(1))[0]) await db.insert(researchProjects).values({ organizationId: program.organizationId, studyProgramId: program.id, title: "CONTOH - Sistem Peringatan Dini Keselamatan Pelayaran", year: YEAR, principalPersonnelId: person.id, fundingSource: "CONTOH - Internal", scheme: "Penelitian Terapan", outputSummary: "Prototipe dashboard peringatan dini.", projectStatus: "ONGOING", lifecycleStatus: "SUBMITTED" });
  if (!(await db.select().from(communityServiceProjects).where(eq(communityServiceProjects.title, "CONTOH - Pelatihan Keselamatan Pelayaran Nelayan")).limit(1))[0]) await db.insert(communityServiceProjects).values({ organizationId: program.organizationId, studyProgramId: program.id, title: "CONTOH - Pelatihan Keselamatan Pelayaran Nelayan", year: YEAR, leadPersonnelId: person.id, partner: "CONTOH - Kelompok Nelayan Bahari", fundingSource: "CONTOH - Internal", outputSummary: "Pelatihan dan modul keselamatan dasar.", projectStatus: "COMPLETED", lifecycleStatus: "APPROVED" });
  if (!(await db.select().from(studentAnnualStats).where(and(eq(studentAnnualStats.studyProgramId, program.id), eq(studentAnnualStats.academicYear, "2025/2026"))).limit(1))[0]) await db.insert(studentAnnualStats).values({ studyProgramId: program.id, academicYear: "2025/2026", activeStudents: 168, newStudents: 58, graduates: 42, dropoutStudents: 2, lifecycleStatus: "APPROVED" });
  if (!(await db.select().from(graduateOutcomeStats).where(and(eq(graduateOutcomeStats.studyProgramId, program.id), eq(graduateOutcomeStats.graduationYear, 2025))).limit(1))[0]) await db.insert(graduateOutcomeStats).values({ studyProgramId: program.id, graduationYear: 2025, graduates: 42, trackedGraduates: 38, employed: 27, entrepreneurship: 3, furtherStudy: 2, averageWaitingMonths: "2.8", relevantEmploymentPercent: "76", lifecycleStatus: "APPROVED" });
  if (!(await db.select().from(cooperations).where(eq(cooperations.partnerName, "CONTOH - PT Samudra Nusantara")).limit(1))[0]) await db.insert(cooperations).values({ organizationId: program.organizationId, studyProgramId: program.id, partnerName: "CONTOH - PT Samudra Nusantara", partnerType: "INDUSTRY", scope: "Praktik industri, kuliah praktisi, dan evaluasi kurikulum.", startDate: "2025-01-01", endDate: "2027-12-31", implementationSummary: "Kuliah praktisi dan penempatan 18 taruna telah dilaksanakan.", cooperationStatus: "ACTIVE", lifecycleStatus: "APPROVED" });

  let [evaluation] = await db.select().from(evaluations).where(and(eq(evaluations.subjectType, "KPI_MEASUREMENT"), eq(evaluations.subjectId, kpi.id), eq(evaluations.period, PERIOD))).limit(1);
  if (!evaluation) { const result = await db.insert(evaluations).values({ subjectType: "KPI_MEASUREMENT", subjectId: kpi.id, period: PERIOD, standardReference: "Target KPI 2026", standardValue: "80%", actualValue: "76%", gapValue: "-4%", analysis: "CONTOH - Capaian mendekati target namun tracer study perlu diperkuat.", rootCause: "CONTOH - Respons alumni belum merata.", evaluatorId: admin.id, status: "SUBMITTED", evaluatedAt: new Date() }); [evaluation] = await db.select().from(evaluations).where(eq(evaluations.id, Number(result[0].insertId))).limit(1); }
  let [recommendation] = await db.select().from(recommendations).where(and(eq(recommendations.evaluationId, evaluation.id), eq(recommendations.recommendationText, "CONTOH - Perbarui basis kontak alumni dan lakukan tracer study per semester."))).limit(1);
  if (!recommendation) { const result = await db.insert(recommendations).values({ evaluationId: evaluation.id, priority: "HIGH", recommendationText: "CONTOH - Perbarui basis kontak alumni dan lakukan tracer study per semester.", ownerOrganizationId: program.organizationId, targetCompletion: new Date("2026-12-15"), status: "OPEN" }); [recommendation] = await db.select().from(recommendations).where(eq(recommendations.id, Number(result[0].insertId))).limit(1); }
  if (!(await db.select().from(followups).where(and(eq(followups.recommendationId, recommendation.id), eq(followups.actionPlan, "CONTOH - Validasi kontak alumni dan distribusi survei tracer study tahap kedua."))).limit(1))[0]) await db.insert(followups).values({ recommendationId: recommendation.id, actionPlan: "CONTOH - Validasi kontak alumni dan distribusi survei tracer study tahap kedua.", picUserId: admin.id, startDate: new Date("2026-08-15"), dueDate: new Date("2026-10-31"), progressPercent: "35", status: "IN_PROGRESS" });
  const [framework] = await db.select().from(accreditationFrameworks).where(eq(accreditationFrameworks.code, "LAMTEKNIK-2025-REFERENCE")).limit(1);
  if (framework && !(await db.select().from(studyProgramAccreditationFrameworks).where(and(eq(studyProgramAccreditationFrameworks.studyProgramId, program.id), eq(studyProgramAccreditationFrameworks.frameworkId, framework.id))).limit(1))[0]) await db.insert(studyProgramAccreditationFrameworks).values({ studyProgramId: program.id, frameworkId: framework.id, isPrimary: true, assignmentStatus: "ACTIVE", assignedFrom: "2026-01-01", notes: "CONTOH - Assignment untuk simulasi lokal; konfirmasi instrumen resmi sebelum digunakan." });
  console.log("Demo seed selesai. Seluruh record contoh ditandai dengan awalan CONTOH.");
}

main().then(() => process.exit(0)).catch((error) => { console.error(error); process.exit(1); });
