import { and,eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { laboratories,laboratoryProfiles,laboratoryPrograms } from "@/src/db/schema-phase6";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { canReadResourceScope,canWriteResourceScope } from "@/src/services/resource-scope";

const createInput=z.object({organizationId:z.number().int().positive(),code:z.string().min(2).max(80),name:z.string().min(2).max(255),description:z.string().optional(),location:z.string().max(500).optional(),picUserId:z.number().int().positive().nullable().optional()});
const patchInput=z.object({operationalStatus:z.enum(["ACTIVE","INACTIVE","MAINTENANCE"]).optional(),status:z.enum(["ACTIVE","ARCHIVED"]).optional()});
function queryId(req:Request){const n=Number(new URL(req.url).searchParams.get("id"));return Number.isInteger(n)&&n>0?n:null;}

export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const db=requireDb();const labs=await db.select().from(laboratories);const profiles=await db.select().from(laboratoryProfiles);const mappings=await db.select().from(laboratoryPrograms);const allowed=[];for(const lab of labs){if(!canReadResourceScope(s,lab.organizationId,null))continue;const profile=profiles.filter(x=>x.laboratoryId===lab.id).sort((a,b)=>b.versionNumber-a.versionNumber)[0]??null;allowed.push({...lab,profile,studyProgramIds:mappings.filter(x=>x.laboratoryId===lab.id).map(x=>x.studyProgramId)});}return NextResponse.json(allowed);}

export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const p=createInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});if(!canWriteResourceScope(s,p.data.organizationId,null,true))return NextResponse.json({error:"Diperlukan resources.manage pada scope UPPS."},{status:403});const db=requireDb();const code=p.data.code.toUpperCase();const[existing]=await db.select({id:laboratories.id}).from(laboratories).where(and(eq(laboratories.organizationId,p.data.organizationId),eq(laboratories.code,code))).limit(1);if(existing)return NextResponse.json({error:"Kode laboratorium sudah digunakan pada UPPS ini."},{status:409});const x=await db.insert(laboratories).values({organizationId:p.data.organizationId,code,operationalStatus:"ACTIVE",status:"ACTIVE"});const laboratoryId=Number(x[0].insertId);const profileResult=await db.insert(laboratoryProfiles).values({laboratoryId,versionNumber:1,name:p.data.name,description:p.data.description,location:p.data.location,picUserId:p.data.picUserId??null,lifecycleStatus:"DRAFT"});const profileId=Number(profileResult[0].insertId);await audit({actorId:s.userId,action:"CREATE_LABORATORY",subjectType:"LABORATORY",subjectId:laboratoryId,after:{...p.data,code,profileId}});return NextResponse.json({id:laboratoryId,profileId,status:"ACTIVE",profileStatus:"DRAFT"},{status:201});}

export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=queryId(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patchInput.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(laboratories).where(eq(laboratories.id,id)).limit(1);if(!before)return NextResponse.json({error:"Laboratorium tidak ditemukan."},{status:404});if(!canWriteResourceScope(s,before.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});await db.update(laboratories).set({...p.data,updatedAt:new Date()}).where(eq(laboratories.id,id));await audit({actorId:s.userId,action:"UPDATE_LABORATORY",subjectType:"LABORATORY",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}

export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const id=queryId(req);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(laboratories).where(eq(laboratories.id,id)).limit(1);if(!before)return NextResponse.json({error:"Laboratorium tidak ditemukan."},{status:404});if(!canWriteResourceScope(s,before.organizationId,null,true))return NextResponse.json({error:"Forbidden"},{status:403});await db.update(laboratories).set({status:"ARCHIVED",operationalStatus:"INACTIVE",updatedAt:new Date()}).where(eq(laboratories.id,id));await audit({actorId:s.userId,action:"ARCHIVE_LABORATORY",subjectType:"LABORATORY",subjectId:id,before,after:{status:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
