import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { kpis } from "@/src/db/schema";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { can,scopeAllows } from "@/src/lib/rbac";
const patch=z.object({strategicGoalId:z.number().int().positive().optional(),code:z.string().min(2).optional(),name:z.string().min(3).optional(),definition:z.string().nullable().optional(),formula:z.string().nullable().optional(),unit:z.string().nullable().optional(),direction:z.enum(["HIGHER_IS_BETTER","LOWER_IS_BETTER","EXACT"]).optional(),lifecycleStatus:z.enum(["DRAFT","ARCHIVED"]).optional()});
async function idOf(params:Promise<{id:string}>){const{id}=await params;const n=Number(id);return Number.isInteger(n)&&n>0?n:null;}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(s,"data.update")||can(s,"program.update")))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const p=patch.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});const db=requireDb();const[before]=await db.select().from(kpis).where(eq(kpis.id,id)).limit(1);if(!before)return NextResponse.json({error:"Not found"},{status:404});if(!scopeAllows(s,before.ownerOrganizationId))return NextResponse.json({error:"Scope organisasi tidak sesuai."},{status:403});if(before.lifecycleStatus!=="DRAFT")return NextResponse.json({error:"KPI non-draft tidak diedit in-place; buat revisi/version baru."},{status:409});await db.update(kpis).set(p.data).where(eq(kpis.id,id));await audit({actorId:s.userId,action:"UPDATE",subjectType:"KPI",subjectId:id,before,after:p.data});return NextResponse.json({id,...p.data});}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(s,"data.update")||can(s,"program.update")))return NextResponse.json({error:"Forbidden"},{status:403});const id=await idOf(params);if(!id)return NextResponse.json({error:"Invalid id"},{status:400});const db=requireDb();const[before]=await db.select().from(kpis).where(eq(kpis.id,id)).limit(1);if(!before)return NextResponse.json({error:"Not found"},{status:404});if(before.lifecycleStatus!=="DRAFT")return NextResponse.json({error:"KPI non-draft tidak dapat dihapus langsung."},{status:409});await db.update(kpis).set({lifecycleStatus:"ARCHIVED"}).where(eq(kpis.id,id));await audit({actorId:s.userId,action:"ARCHIVE",subjectType:"KPI",subjectId:id,before,after:{lifecycleStatus:"ARCHIVED"}});return NextResponse.json({id,status:"ARCHIVED"});}
