import { hash } from "bcryptjs";
import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { roles,studyPrograms,userRoles,users } from "@/src/db/schema";
import { roleSettings } from "@/src/db/schema-admin";
import { getSession } from "@/src/lib/auth";
import { audit } from "@/src/lib/audit";
import { can,hasRole,scopeAllows } from "@/src/lib/rbac";

const input=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(10),roleCode:z.string().min(2).max(100),organizationId:z.number().int().positive(),studyProgramId:z.number().int().positive().nullable().optional()});
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"users.manage")&&!hasRole(s,"ADMIN_DATA"))return NextResponse.json({error:"Forbidden"},{status:403});const db=requireDb();const base=await db.select({id:users.id,name:users.name,email:users.email,status:users.status,createdAt:users.createdAt}).from(users);const assignments=await db.select({userId:userRoles.userId,roleCode:roles.code,organizationId:userRoles.organizationId,studyProgramId:userRoles.studyProgramId}).from(userRoles).innerJoin(roles,eq(userRoles.roleId,roles.id));return NextResponse.json(base.map(u=>({...u,assignments:assignments.filter(a=>a.userId===u.id)})).filter(u=>u.assignments.some(a=>scopeAllows(s,a.organizationId,a.studyProgramId))));}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const tenantAdmin=hasRole(s,"ADMIN_DATA");if(!can(s,"users.manage")&&!tenantAdmin)return NextResponse.json({error:"Forbidden"},{status:403});const p=input.safeParse(await req.json());if(!p.success)return NextResponse.json({error:p.error.flatten()},{status:400});if(!scopeAllows(s,p.data.organizationId,p.data.studyProgramId??null))return NextResponse.json({error:"Scope akun berada di luar Jurusan Anda."},{status:403});if(tenantAdmin&&!(["KAPRODI","KAJUR"] as string[]).includes(p.data.roleCode))return NextResponse.json({error:"Admin Jurusan hanya dapat membuat akun Kaprodi atau Kajur."},{status:403});if(p.data.roleCode==="KAPRODI"&&!p.data.studyProgramId)return NextResponse.json({error:"Akun Kaprodi wajib dipasangkan ke satu Program Studi."},{status:400});if(p.data.roleCode==="KAJUR"&&p.data.studyProgramId)return NextResponse.json({error:"Akun Kajur menggunakan scope seluruh Jurusan, bukan satu Prodi."},{status:400});const db=requireDb();if(p.data.studyProgramId){const[program]=await db.select().from(studyPrograms).where(eq(studyPrograms.id,p.data.studyProgramId)).limit(1);if(!program||program.organizationId!==p.data.organizationId)return NextResponse.json({error:"Program Studi tidak berada pada Jurusan yang dipilih."},{status:409});}const [role]=await db.select({id:roles.id,status:roleSettings.status}).from(roles).leftJoin(roleSettings,eq(roleSettings.roleId,roles.id)).where(eq(roles.code,p.data.roleCode)).limit(1);if(!role||role.status==="ARCHIVED")return NextResponse.json({error:"Role tidak ditemukan atau tidak aktif."},{status:409});const existing=await db.select({id:users.id}).from(users).where(eq(users.email,p.data.email.toLowerCase())).limit(1);if(existing[0])return NextResponse.json({error:"Email sudah digunakan."},{status:409});const x=await db.insert(users).values({name:p.data.name,email:p.data.email.toLowerCase(),passwordHash:await hash(p.data.password,12),status:"ACTIVE"});const userId=Number(x[0].insertId);await db.insert(userRoles).values({userId,roleId:role.id,organizationId:p.data.organizationId,studyProgramId:p.data.studyProgramId??null});await audit({actorId:s.userId,action:"CREATE_USER",subjectType:"USER",subjectId:userId,after:{name:p.data.name,email:p.data.email,roleCode:p.data.roleCode,organizationId:p.data.organizationId,studyProgramId:p.data.studyProgramId}});return NextResponse.json({id:userId,role:p.data.roleCode},{status:201});}
