import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireDb } from "@/src/db";
import { accreditationAssessments, accreditationAssessmentSources, accreditationClusters, accreditationCriteria, accreditationFrameworks, accreditationIndicatorClusters, accreditationIndicators, studyProgramAccreditationFrameworks } from "@/src/db/schema-accreditation";
import { studyPrograms } from "@/src/db/schema";
import { audit } from "@/src/lib/audit";
import { getSession } from "@/src/lib/auth";
import { can, scopeAllows } from "@/src/lib/rbac";

const saveInput=z.object({assignmentId:z.number().int().positive(),indicatorId:z.number().int().positive(),period:z.string().min(4),readinessStatus:z.enum(["NOT_ASSESSED","IN_PROGRESS","COMPLETE","GAP"]),actualValue:z.string().optional(),calculatedValue:z.string().optional(),calculationNote:z.string().optional(),analysis:z.string().optional(),evaluationNote:z.string().optional(),ledNote:z.string().optional(),publicationDecision:z.enum(["INTERNAL_ONLY","PUBLIC_CANDIDATE"]).default("INTERNAL_ONLY"),workflowStatus:z.enum(["DRAFT","SUBMITTED"]).default("DRAFT"),sourceSubjectType:z.string().optional(),sourceSubjectId:z.number().int().positive().optional(),referenceTitle:z.string().optional(),sourceNote:z.string().optional(),includeInPublic:z.boolean().default(false)});
const actionInput=z.object({assessmentId:z.number().int().positive(),action:z.enum(["APPROVE","RETURN","PUBLISH"])});

async function assignmentScope(id:number){const db=requireDb();const[row]=await db.select({organizationId:studyPrograms.organizationId,studyProgramId:studyPrograms.id,frameworkId:studyProgramAccreditationFrameworks.frameworkId}).from(studyProgramAccreditationFrameworks).innerJoin(studyPrograms,eq(studyProgramAccreditationFrameworks.studyProgramId,studyPrograms.id)).where(eq(studyProgramAccreditationFrameworks.id,id)).limit(1);return row??null;}

export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(s,"accreditation.read"))return NextResponse.json({error:"Forbidden"},{status:403});const url=new URL(req.url),assignmentId=Number(url.searchParams.get("assignmentId")),period=url.searchParams.get("period")??"";if(!assignmentId||!period)return NextResponse.json({error:"assignmentId dan period wajib diisi."},{status:400});const scope=await assignmentScope(assignmentId);if(!scope||!scopeAllows(s,scope.organizationId,scope.studyProgramId))return NextResponse.json({error:"Assignment di luar scope."},{status:403});const db=requireDb();const indicators=await db.select({id:accreditationIndicators.id,code:accreditationIndicators.code,name:accreditationIndicators.name,description:accreditationIndicators.description,unit:accreditationIndicators.unit,weight:accreditationIndicators.weight,scoringRule:accreditationIndicators.scoringRule,criterionId:accreditationCriteria.id,criterionCode:accreditationCriteria.code,criterionName:accreditationCriteria.name,sequence:accreditationIndicators.sequence}).from(accreditationIndicators).innerJoin(accreditationCriteria,eq(accreditationIndicators.criterionId,accreditationCriteria.id)).where(and(eq(accreditationIndicators.frameworkId,scope.frameworkId),eq(accreditationIndicators.status,"ACTIVE")));const clusterLinks=await db.select({indicatorId:accreditationIndicatorClusters.indicatorId,clusterCode:accreditationClusters.code,clusterName:accreditationClusters.name,semanticGroup:accreditationClusters.semanticGroup,isPrimary:accreditationIndicatorClusters.isPrimary}).from(accreditationIndicatorClusters).innerJoin(accreditationClusters,eq(accreditationIndicatorClusters.clusterId,accreditationClusters.id)).where(eq(accreditationClusters.frameworkId,scope.frameworkId));const assessments=await db.select().from(accreditationAssessments).where(and(eq(accreditationAssessments.assignmentId,assignmentId),eq(accreditationAssessments.period,period)));const sources=assessments.length?await db.select().from(accreditationAssessmentSources):[];return NextResponse.json({indicators:indicators.map(indicator=>({...indicator,clusters:clusterLinks.filter(link=>link.indicatorId===indicator.id),assessment:assessments.find(row=>row.indicatorId===indicator.id)??null,sources:sources.filter(source=>source.assessmentId===assessments.find(row=>row.indicatorId===indicator.id)?.id)}))});}

export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});if(!(can(s,"accreditation.assess")||can(s,"system.configure")))return NextResponse.json({error:"Forbidden"},{status:403});const parsed=saveInput.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});const scope=await assignmentScope(parsed.data.assignmentId);if(!scope||!scopeAllows(s,scope.organizationId,scope.studyProgramId))return NextResponse.json({error:"Assignment di luar scope."},{status:403});const db=requireDb();const[indicator]=await db.select({id:accreditationIndicators.id}).from(accreditationIndicators).where(and(eq(accreditationIndicators.id,parsed.data.indicatorId),eq(accreditationIndicators.frameworkId,scope.frameworkId))).limit(1);if(!indicator)return NextResponse.json({error:"Indikator tidak termasuk framework assignment."},{status:409});const{sourceSubjectType,sourceSubjectId,referenceTitle,sourceNote,includeInPublic,...values}=parsed.data;await db.insert(accreditationAssessments).values({...values,assessedBy:s.userId}).onDuplicateKeyUpdate({set:{...values,assessedBy:s.userId,updatedAt:new Date()}});const[assessment]=await db.select().from(accreditationAssessments).where(and(eq(accreditationAssessments.assignmentId,values.assignmentId),eq(accreditationAssessments.indicatorId,values.indicatorId),eq(accreditationAssessments.period,values.period))).limit(1);if(sourceSubjectType&&referenceTitle){await db.delete(accreditationAssessmentSources).where(eq(accreditationAssessmentSources.assessmentId,assessment.id));await db.insert(accreditationAssessmentSources).values({assessmentId:assessment.id,sourceSubjectType,sourceSubjectId,referenceTitle,note:sourceNote,includeInPublic});}await audit({actorId:s.userId,action:"SAVE_ACCREDITATION_ASSESSMENT",subjectType:"ACCREDITATION_ASSESSMENT",subjectId:assessment.id,after:parsed.data});return NextResponse.json({id:assessment.id,status:assessment.workflowStatus});}

export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Unauthorized"},{status:401});const parsed=actionInput.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:parsed.error.flatten()},{status:400});const db=requireDb();const[assessment]=await db.select().from(accreditationAssessments).where(eq(accreditationAssessments.id,parsed.data.assessmentId)).limit(1);if(!assessment)return NextResponse.json({error:"Assessment tidak ditemukan."},{status:404});const scope=await assignmentScope(assessment.assignmentId);if(!scope||!scopeAllows(s,scope.organizationId,scope.studyProgramId))return NextResponse.json({error:"Assessment di luar scope."},{status:403});if(parsed.data.action==="APPROVE"){if(!(can(s,"accreditation.approve")||can(s,"system.configure")))return NextResponse.json({error:"Forbidden"},{status:403});if(assessment.workflowStatus!=="SUBMITTED")return NextResponse.json({error:"Hanya assessment SUBMITTED yang dapat disetujui."},{status:409});await db.update(accreditationAssessments).set({workflowStatus:"APPROVED",approvedBy:s.userId,updatedAt:new Date()}).where(eq(accreditationAssessments.id,assessment.id));}if(parsed.data.action==="RETURN"){if(!(can(s,"accreditation.approve")||can(s,"system.configure")))return NextResponse.json({error:"Forbidden"},{status:403});await db.update(accreditationAssessments).set({workflowStatus:"DRAFT",approvedBy:null,updatedAt:new Date()}).where(eq(accreditationAssessments.id,assessment.id));}if(parsed.data.action==="PUBLISH"){if(!(can(s,"accreditation.publish")||can(s,"system.configure")))return NextResponse.json({error:"Forbidden"},{status:403});if(assessment.workflowStatus!=="APPROVED"||assessment.publicationDecision!=="PUBLIC_CANDIDATE")return NextResponse.json({error:"Publikasi memerlukan status APPROVED dan keputusan PUBLIC_CANDIDATE."},{status:409});await db.update(accreditationAssessments).set({workflowStatus:"PUBLISHED",updatedAt:new Date()}).where(eq(accreditationAssessments.id,assessment.id));}await audit({actorId:s.userId,action:`${parsed.data.action}_ACCREDITATION_ASSESSMENT`,subjectType:"ACCREDITATION_ASSESSMENT",subjectId:assessment.id});return NextResponse.json({id:assessment.id,status:parsed.data.action==="APPROVE"?"APPROVED":parsed.data.action==="RETURN"?"DRAFT":"PUBLISHED"});}
